### ISSUE TITLE
Colorize Enchants!

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#102]
Getting dat color set out, whoo! Making the lores pretty, I was thinking.. based on the level (out of it's max) of the enchantment would determine the color.

**Comment by cyberpwnn** [comment]
Not possible. Enchantapi is sending packets on top of my changes. Besides **This is the least important thing i should be working on**

Here is the commit, does not work though https://github.com/cyberpwnn/Effex/commit/a7d9e9bbe11826cd83ef2d924c85f3ee225c9596
