### ISSUE TITLE
Soul Eruption

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#105]
Add a message that sends to the player when this specific enchantment activates, even myself forgot about it and was wondering why I was losing health so much :P

**Comment by cyberpwnn** [comment]
A Message? Why not a sound and effect?

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/10b36cec00a87d68c28758744073d498b70b0a73

**Comment by SwiftSwamp** [comment]
The reason for a message.. is because not everyone plays with sound on or will know what the sound means like me for example, I was freaking out when it first happened haha.

**Comment by cyberpwnn** [comment]
``` java
user.sendMessage(C.RED + "* You sacrifice health to increase damage.");
```
