### ISSUE TITLE
Double Drop

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#106]
Double Drop needs to be able to pick what item it applies to, atm it's only being used for Pickaxes but it stops us from dropping anything freely :p

**Comment by cyberpwnn** [comment]
Does not comply with #14. Resolving.

**Comment by cyberpwnn** [comment]
### Commune 7.5 Released
https://github.com/cyberpwnn/Commune/commit/8874dac22c3052baf0672be8efdca35ebd5e0f84
