### ISSUE TITLE
Snare Doesn't Work

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#108]
I don't know if the actual enchantment doesn't work either but for some reason I can't drop enchant Snare I onto a Bow, it's ONLY Snare I on the Enchanted Book titled "&bEnchanted Book"

**Comment by cyberpwnn** [comment]
I Think bows are the issue #42 #54 #64  #90

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/blob/master/src/main/java/org/cyberpwn/effex/EffexController.java#L1284

**Comment by cyberpwnn** [comment]
### Effex 1.6 Released
https://github.com/cyberpwnn/Effex/commit/34594c7c5aa3571db4599353c6f9fec47fa19833
