### ISSUE TITLE
Night Vision Enchantment

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#115]
Night Vision is still having issues with it constantly flashing due to the timer being set to 0:0.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/1e1a1a04cf29a06ce4034ff4ee7b8ffad6494770

**Comment by cyberpwnn** [comment]
Was not working

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/294e40c08de42ed0d539c8b40c79adcdc375a494
