### ISSUE TITLE
Sell All Bug

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#116]
Sell All now sells one stack at a time, get 2 Diamonds, put one in a different slow and do /sell all, you'll see what I mean, also uploaded a screen shot.
![sell](https://cloud.githubusercontent.com/assets/3534551/19220755/9c88844c-8e02-11e6-9c46-712aa65ecf6b.png)

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/CurrencyShops/commit/c0c2f04b4885a82bb27f9c9ed39a2719374d3246
