### ISSUE TITLE
Tabbing an item in an Enchantment Table

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#118]
When you put an item in the table that is "unenchantable" and hotkey it out, your item is lost and you are left with a glitched book, doesn't' always happen.. but it ends up being that purple / black glitched looking black.

**Comment by cyberpwnn** [comment]
"Hotkey it out" - What does that mean.

**Comment by SwiftSwamp** [comment]
You know how when you hover over an item and hit a number on your numpad to auto move the item to that spot in your hotbar?

**Comment by cyberpwnn** [comment]
Ah, Thats clientside, damn,.

**Comment by SwiftSwamp** [comment]
So nothing we can do?

**Comment by cyberpwnn** [comment]
No.

**Comment by cyberpwnn** [comment]
The most we could do would be warn the player about doing that.
