### ISSUE TITLE
Unenchantable Fishing Rods

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#119]
Fishing Rods are considered an "Unenchantable" item so you cannot get any enchants for them.

**Comment by cyberpwnn** [comment]
So... What is the issue?

**Comment by SwiftSwamp** [comment]
We can't enchant Fishing Rods in an enchantment table because it's marked as "Unenchantable"

**Comment by cyberpwnn** [comment]
Did you disable them?

**Comment by cyberpwnn** [comment]
Bubumpdedump bump

**Comment by SwiftSwamp** [comment]
No but it doesn't matter.
