### ISSUE TITLE
Sorting Enchantments

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#120]
I want to have the ability to sort enchantments to what tiers I want.
Default for ya, I may be missing a few of the new ones,

Tier 1 - 4000xp
Cold Blooded
Deflect
Devil’s Grace
Forge
Nocturnal
Inferno (TNT)
Sticky (TNT)
Defusing (TNT)

Tier 2 - 8000xp
Beheading
Earthquake
Soulless
Alchemist
Blast (TNT)
Stamina

Tier 3 - 15000xp
Inferno
Longshot
Poison
Snare
Vampiric
Blessing
Demolition
Soul Stealer

Tier 4 - 25000xp
Frost
Nightmare
Soul Eruption
Empowerment
Reinforced
Anti-Gravity
Moss

Tier 5 - 40000xp
Rage
Shock

**Comment by cyberpwnn** [comment]
#120

**Comment by cyberpwnn** [comment]
Referenced text in #100
