### ISSUE TITLE
Fly Blizzard

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#122]
Fly Blizzards give you fly like normal during the duration of the blizzard on the other servers, however on Factions.. it allows you to fly anywhere except for the Warzone and Enemy territory, safely takes you out of fly and "lands" you when you're no longer flying and flying is automatically activated when you're on so you can just straight away double jump.

**Comment by cyberpwnn** [comment]
Waiting on #121

**Comment by cyberpwnn** [comment]
That isnt how minecraft works.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/c1cb5417d65408ae1e4fc99ce5782b2b3229980a
