### ISSUE TITLE
Kill Buff Blizzard

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#127]
This is currently only used for KitPvP, there was a small custom plugin made to reward Money & Experience per kill on it, this would of course give everyone online more, I've attached the SOURCE code so you can check it out or just add it to Commune to directly handle it. (NVM, sending over Skype because this is public)

**Comment by cyberpwnn** [comment]
Waiting on #121

**Comment by cyberpwnn** [comment]
I dont understand this
