### ISSUE TITLE
F Top MySQL

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#131]
This isn't an urgent issue but adding MySQL to F Top would be nice so we can display stats on a web ui and have previous maps shown / stored.

**Comment by cyberpwnn** [comment]
Just for stats?

like... not for sql stuff?

I dont like adding things to sql if it isnt needed for the plugin.

Instead why not just open up an api server which receives requests and sends json responses. That way any new information can be added in by the plugin and new web stats can be shown.

**Comment by SwiftSwamp** [comment]
Ahh okay, sure. I was just thinking with when there becomes a large influx of Factions.

**Comment by cyberpwnn** [comment]
Closed for now. Re open when needed
