### ISSUE TITLE
Request to Merge FRTP into Commune

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#132]
There is no point for tiny stray plugins

**Comment by SwiftSwamp** [comment]
Yeah, sure. Go for it, of course like always.. just make sure they're configurable to enable / disable.

**Comment by cyberpwnn** [comment]
Merged in afk https://github.com/cyberpwnn/Commune/commit/dda8ba0beb7d6a3ab234b8e6e2e5550febc594e0

**Comment by cyberpwnn** [comment]
### Commune 7.6 Updated

**Comment by cyberpwnn** [comment]
### Commune 7.7 Updated
https://github.com/cyberpwnn/Commune/commit/fd8068040181c22aa2f520531f6617647732a2fc
