### ISSUE TITLE
Mine Reset Should be better

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#133]
### BUT IT ISNT

@SwiftSwamp Contribute some ideas will ya?

**Comment by SwiftSwamp** [comment]
The Mines are meant to reset automatically when it get's mined out to a certain amount but for some reason it's not working anymore after me and Josh went over this tirelessly.

**Comment by cyberpwnn** [comment]
No i mean its just a bad plugin, should be recoded.

**Comment by SwiftSwamp** [comment]
Currently dealing with it, issue closed as this is a future item. No need to waste time on making it.
