### ISSUE TITLE
Essence EXP Rate Changes

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#134]
Currently the amount of Experience given is extremely op;

level 1: MAX = 90, AVG = 45 (20 * math.random)
level 2: MAX = 180, AVG = 90 (30 * math.random)
level 3: MAX = 270, AVG = 135 (40 * math.random)

Please make the new values;
Level 1: 5 (MAX = 18, AVG = 9)
Level 2: 6 (MAX = 36, AVG = 18)
Level 3: 7 (MAX = 54, AVG = 27)

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/35bc04131843b1cc1009bccc59447d96b73fa656

**Comment by cyberpwnn** [comment]
### Effex 1.8 Released

**Comment by cyberpwnn** [comment]
Still an issue for blocks

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/ec068f9f9993273efcc1c008ea38a0561a14126a
