### ISSUE TITLE
Blast Changes

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#139]
I'm going to assume it's because of NCP and with it not working correctly because of that but sometimes your Pickaxe will just vanish when using it with the Blast enchantment.

Blast currently one hits any block aside from Bedrock when mining, this is semi problematic i.e... if you're mining in a wooden box, you're destroying it, imo it should only apply to the things that tool is meant for.

**Comment by cyberpwnn** [comment]
It does. 

Go ahead, mine grass, dirt, wood, gravel, sand, and torches with a pickaxe.

**Comment by cyberpwnn** [comment]
Do you mean only mine stone-like stuff? Ill assume that,

**Comment by cyberpwnn** [comment]
Use the new Phantom protection system.

**Comment by cyberpwnn** [comment]
Added #140's issue to description of this issue

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/88a52ba0871996aff1fd869ad34f8b339bde1107
