### ISSUE TITLE
/wild puts you on the Nether Roof

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#141]
https://github.com/SwiftSwamp/GlacialRealms/issues/69

**Comment by cyberpwnn** [comment]
I think it isnt /wild. it is wild teleporting you to a place where you cannot be so it keeps teleporting you up until you hit something you can be in. That might be the case.

**Comment by cyberpwnn** [comment]
Waiting on #132

**Comment by cyberpwnn** [comment]
Commune now holds frtp, reopening issue

**Comment by cyberpwnn** [comment]
### Commune 7.8 Updated
https://github.com/cyberpwnn/Commune/commit/467589564c5cde0432b55c531201d7bd764c8497

**Comment by SwiftSwamp** [comment]
Not fixed.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/4fbc7405a51034903ae701610c2bcdb488aae3a3
