### ISSUE TITLE
Potion stacking can cause dupes

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#148]
You can get two stacks of 10 potions and click one of them and get a stack of 19 and you can keep doing this until you get a stack of 64.

**Comment by cyberpwnn** [comment]
PLEASE make your issue more than "category + issue". Its not helpful

**Comment by cyberpwnn** [comment]
#296 (split em up)

**Comment by cyberpwnn** [comment]
Wow

https://www.spigotmc.org/resources/potion-storage.10524/
https://www.spigotmc.org/resources/potionstacker.9703/
https://dev.bukkit.org/bukkit-plugins/potionstack/

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/d2d83e654cee8ad66fdcdbe3dc26fc0340c9e853
