### ISSUE TITLE
f who reformatting

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#158]
* Make it all pretty and reformat it as the following:

Description:
Land/Power/Maxpower:
Faction Value:
Faction Rank:
Koth Wins:
Allies:
Enemies:
Members Online:
Members Offline:

**Comment by leblancGR** [comment]
&3Description: &btext
&3Land/Power/Maxpower: &btext
&3Faction Value: &btext
&3Faction Rank: &btext
&3Koth Wins: &btext
&3Allies: &dtext
&3Enemies: &ctext
&3Members Online: &btext
&3Members Offline: &btext

**Comment by SwiftSwamp** [comment]
Not a priority, please suggest it again in the future.
This is the only.. thing not configurable by default with Factions.
