### ISSUE TITLE
GlacialRealms Trailer

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#162]
- Have an official Trailer made of the server and have it featured on various YouTube Channels

**Comment by UrBoyJoker** [comment]
Can't wait

**Comment by cyberpwnn** [comment]
And IM GOING TO DO IT

**Comment by SwiftSwamp** [comment]
PUT A TIME STAMP ON HOW LONG IT'LL TAKE DAN

**Comment by cyberpwnn** [comment]
HOW ABOUT ALL THE ENHANCEMENT BULLET ISSUES

**Comment by cyberpwnn** [comment]
I personally think that we shouldnt make a trailer... More specifically a trailer that states something like this

"We have skyblock and factions, and we are going to show you what they built and the spawn in shaders for 4 minutes."

I want the trailer to show 90% of stuff that ACTUALLY IS DIFFERENT THAN OTHER SERVERS. I dont want to bring up custom enchantments either. They arent custom, they are on every known faction server basically.

What if we held off on a "global" trailer, and instead buffed up an rpg trailer which "mostly" focuses on the RPG server but makes sure it is known that it is not the only thing on the network.

**Comment by SwiftSwamp** [comment]
Waiting until we have RPG out to have enough to focus on a custom trailer..

**Comment by SwiftSwamp** [comment]
Reopening, DAN!

**Comment by SwiftSwamp** [comment]
Moving to to High Priority, this will help greatly in finding YouTubers and for general promotion. Already have a few YouTubers who would be more likely to join the server if there was a trailer for them to watch prior.

**Comment by cyberpwnn** [comment]
Or they could just hop on for 5 minutes. 

Use high priority stuff for issues that would end up showing in the trailer.

**Comment by cyberpwnn** [comment]
Backlogging for now. If this comes up later, re-open it.
