### ISSUE TITLE
Command NPCs

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#163]
* Add NPCs in the Hub that display server count and allow you to click on them to teleport to said server
* Add NPCs in the other servers to go back to the hub, open up the auction house, help menu, island menu, prison enchants menu, factions help menu

**Comment by GetDerpy** [comment]
Added npc's to hub 1 (can they be copied to hub 2/3?) and prison/skyblock/factions.

However, the server npcs in hub, and hub npcs on servers give "unknown command" when executed.

**Comment by SwiftSwamp** [comment]
Resolved thanks to #207
