### ISSUE TITLE
Item Lending

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#17]
This allows a safe way for players to lend out items.  Ability to "Lend" an item to someone up to a certain amount of time with of course charging them through Vault currency. An item is returned to a users "Collection Box" (GUI Based) when the item time is up. 

When the item is lent, the item goes into the players 1st slot and cannot be removed, traded, cleared out, altered in any way aside from being fixed, the item will also go back to the users collection box if it get's under a certain amount of durability (Say 5-10%?)

**Comment by cyberpwnn** [comment]
So stale its dead

**Comment by SwiftSwamp** [comment]
Removed On Hold, while this would still be super cool to do. I believe this is better suited for Saron than anything and or could be thought of doing it in a more simpler way as it would only be for weapons, tools and armor. 

Reopening and tagging with Open Discussion.

**Comment by cyberpwnn** [comment]
This is way out of priority compared to some of the issues i see on the tracker.

**Comment by SwiftSwamp** [comment]
It was marked on Open Discussion to see if it's even still worth adding to the actual servers and wouldn't be something better suited for say Saron.
