### ISSUE TITLE
Essence Chat Spam

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#177]
While the way it lets you know how much Experience you're getting at the moment, it get's pretty spammy. What about adding a stfu command or making it display in the Action Bar so it's not spamming your chat.

**Comment by NoahOG** [comment]
![](http://i.imgur.com/IucRc9Q.png)

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/cf830325f5a3b4004d57e1bd667e9c075cde125c

**Comment by cyberpwnn** [comment]
Some sort of status of the xp you are getting is wanted by @SwiftSwamp

**Comment by cyberpwnn** [comment]
or not?
