### ISSUE TITLE
Essence Infinite Experience

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#178]
You can gain infinite experience if you mine something that's protected it'll still give you the experience despite the island protection, also works on worldguard / factions.

https://www.youtube.com/watch?time_continue=16&v=q2nL_z6rkvE

**Comment by cyberpwnn** [comment]
Turn off the enchantment.

**Comment by cyberpwnn** [comment]
### Effex 2.3 Released
https://github.com/cyberpwnn/Effex/commit/d2ee5d9a2f1fab16ed047b54efd49fe8c4f7f16b
