### ISSUE TITLE
Last Cegg Patch

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#182]
That last Creeper Egg patched has disallowed the use of any Monster Egg in general, we can't place anything anywhere.

**Comment by GetDerpy** [comment]
Can place ceggs anywhere in wilderness, even under the base, just not in the base.

Is it because inside the base is on the dry side of a wet wall? Idk what checks you do.

**Comment by cyberpwnn** [comment]
Its raytracing.  I was asked to increase the strictness. Ill reduce it again.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/a647f444a899f25001b6897caf5f2c8ee52a21c8

Reopen if this is still an issue upon release
