### ISSUE TITLE
Command Warmups / Cooldowns

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#183]
* Admins do not bypass cooldowns or warmups (i.e. /wild)
* When doing a command on a cooldown that also has a warmup, it'll ignore the cooldown and act like it's teleporting you but then quit and tell you.. "Hey! such and such seconds left remaining until you can use this command again!" , this was fixed previously but I guess the plugin merge messed it back up again, if you're currently waiting on a cooldown it should tell you instead of the warmup.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/b680feb047a06c7fe8e095c5bedaa9a0ad5c0509

Removed the frtp warmup
**USE THE WARMUP FEATURE IN COMMUNE**
