### ISSUE TITLE
Magnetic Override

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#189]
Magnetic allows you to override any protection and mine / take any block you want

**Comment by cyberpwnn** [comment]
* What enchantments are on the pickaxe
* What area should they not be allowed to modify

**Comment by SwiftSwamp** [comment]
Sorry, I should've phrased that better. All you need is Magnetic on your boots and you can even use your hand to take whatever block you want and same as usual, WorldGuard, ASkyBlock (Which uses WG anyways I think?) and Factions.

**Comment by cyberpwnn** [comment]
You should not be able to take from world guard regions or factions regions UNLESS YOU HAVE PERMISSION TO MODIFY IT IN THE FIRST PLACE

**Comment by SwiftSwamp** [comment]
I was trying on an alt and had a few random people test it, all they needed was Magnetic on their boots and they could grief any island / faction.

**Comment by cyberpwnn** [comment]
Did you test it recently?

Were you opped or had permission to modify in a faction you do not belong in?

**Comment by SwiftSwamp** [comment]
Yes, I just tested it a few minutes ago (Before 2.4, was using Effex 2.3).

**Comment by SwiftSwamp** [comment]
Just tested it again with 2.4, works.

**Comment by SwiftSwamp** [comment]
Yeah, I just griefed spawn too.

**Comment by cyberpwnn** [comment]
There is not enough information here to reproduce anything. Give reproduction steps.

**Comment by SwiftSwamp** [comment]
Add Magnetic to your boots, that's all you need to do.. then you can override any protection and destroy any blocks as if you had the permission to.

**Comment by cyberpwnn** [comment]
Destroy blocks with what
What region
What server
What versions of effex and phantom

I need reproduction steps that describe how i can do exactly what you did.

**Comment by SwiftSwamp** [comment]
Phantom S3, Effex 2.4
Skyblock / Factions (Currently only live on Skyblock).
Enchant boots with Magnetic 1.
Spawn, other Islands, anywhere.. you can bypass anything.

**Comment by cyberpwnn** [comment]
Nevermind ill just read through 200 lines of code.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/57aa2a5ac46021e11feb93c992cefc3aecc18b43
