### ISSUE TITLE
Scoreboard Auto Switching

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#19]
We spoke about this before so if you have any questions just let me know.
* When a KoTH is currently active it'll switch the current scoreboard over to the one predefined for KoTHs, I believe it does have an API which you can find all information here: https://www.spigotmc.org/resources/koth-king-of-the-hill.7689/
* I also went ahead and attached the plugin
* It's just a duplicate of the current scoreboard with a true / false of course hook for koth but will auto switch over to that scoreboard when a koth is active
* When someone types any of the mc top or stats command the Scoreboard should also auto switch over to McMMO's for the duration then switch back when it turns off (I think by default most mcmmo scoreboard stuff lasts 15 seconds)

[Koth Jar.zip](https://github.com/cyberpwnn/GlacialRealms/files/509636/Koth.Jar.zip)

**Comment by cyberpwnn** [comment]
On hold
