### ISSUE TITLE
Spawner Leveling Messages

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#190]
If you don't have enough money when trying to upgrade it doesn't tell you that you don't have enough.

**Comment by cyberpwnn** [comment]
Its red, and it makes a clink sound when you try to upgrade. The player is in an inventory, it would be weird to make a message display behind the inventory

**Comment by cyberpwnn** [comment]
Add it in the item meta when you click it

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/5ce9e1b003a2228b9790e6db9334dec006f702ee
