### ISSUE TITLE
Manual Overrides

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#192]
Because you love these, price to upgrade is set to $0 if they do not exist in the provided CurrencyShop, please allow for a manual override, much like the /f top manual override so I can define prices for those that do not exist.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/GlacialRealms/issues/32

**Comment by cyberpwnn** [comment]
Sometimes people do stupid things. Shutup :P

**Comment by SwiftSwamp** [comment]
Remember how I said you speak for everyone.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/b1be32e62e97c16e5132169b05c7f27b3215c792
