### ISSUE TITLE
Blast Issue

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#195]
When mining it doesn't remove the block you mined so it'll be a 3x3x3 cuboid removed.. **expect** for the block you initially mined.

**Comment by cyberpwnn** [comment]
Something must be canceling the event

**Comment by cyberpwnn** [comment]
This should fix it https://github.com/cyberpwnn/Effex/commit/41d66721e389bc79945342a31d24c255a0df72a0
