### ISSUE TITLE
Soul Stealer Bug

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#201]
Soul stealer is counting kills on the sword while pvping, even if there are no deaths. I have witnessed one sword collect "27 Kills" while pvping, yet nobody died in the fight.

**Comment by cyberpwnn** [comment]
Interesting

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/975ba0a569d5be103b14fb4abb1bd5676416498f
