### ISSUE TITLE
Rage 1/2 = Strength 1/2

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#204]
At the minute rage appears to be doing 3-4 hearts of damage per hit. Not sure if it's stacking with strength potions or not.

Would it be better to change Rage 1 to Perm Strength 1, and rage 2 to Perm Strength 2?

**Comment by cyberpwnn** [comment]
It simply adds damage, so if you have strength, it will add to that damage. Therefore it should work with anything that stacks damage.

**Comment by GetDerpy** [comment]
Adding additional damage to strength 2 seems a bit OP, which is why I am suggesting maybe replacing it with perm strength effects.

**Comment by cyberpwnn** [comment]
Ahhh, i diddnt understand, yeah, ill let @SwiftSwamp pile into this also when he gets back.

**Comment by SwiftSwamp** [comment]
Yeah that change is fine, it's meant to act as a Str Pot.. where if you drink a str pot it's the same ordeal instead of stacking, didn't think of that at the time.

**Comment by cyberpwnn** [comment]
Also did the same thing for Reinforced

https://github.com/cyberpwnn/Effex/commit/b252d9785ff1fd742f2c3c48c032caed4ab3f40b
