### ISSUE TITLE
Creative Keeps Crashing with this error;

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#206]
[New WinRAR ZIP archive (2).zip](https://github.com/cyberpwnn/GlacialRealms/files/530713/New.WinRAR.ZIP.archive.2.zip)

**Comment by cyberpwnn** [comment]
```
max-memory-percent: 95 >> 85
history: use-disk: false >> true
```

Reopen if this issue persists
