### ISSUE TITLE
Spawner Leveling

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#21]
* Spawners will have a max level of 7 by default (Configurable, however if I'm changing it mid game it'd only to add more levels)
* Each level grants you a higher spawn rate at a predefined rate that you can set. 
* Leveling up your Spawner costs vault economy (In-Game Money/Currency) which is goes off a formula (See the Example Below)
* You can view your current spawners level by simply punching it and what it's current efficiency is and how much it'd cost to upgrade it to the next level (I guess to level it up, look at the spawner then type a command /levelup spawner? and when you level up a spawner it tells you what it's new level is, new efficiency and how much it'll cost for the next level)
* When you break a leveled spawner it'll hold the extra data in the lore showing it's level / efficiency
* Make sure to include the Spawners actual total value in /f top (I.e If the spawner is worth 1m and you spent 5m on levels, it would now of course add 6m value to the spawners in /f top and of course total f top value)
* Spawner price is deteremined like so: 5% of the spawners buy price per level, so say the spawner is level 1 and you want to upgrade it to level 2 and the spawner is 1m, level 2 would cost $1,050,000. However the efficiency amount is also a factor.. Let me just give you an example below because I'm going brain ded.
Spawner Level || Efficiency || Cost || Notes/Other (Example, IG priced at 1m in /shop)
1 100% Free What the spawner starts at.
2 150% $525,000 (1,000,000 * 50% = 500,000 + 5% = 525,000)
3 175% $287,500 (1,000,000 * 75% = 750,000 + 5% = 787,500 - 500,000 = 287,500)
4 200% $300,000 (1,000,000 * 100% = 1,000,000 + 5% = 1,050,000 - 750,000 = 300,000)
5 250% $575,000 (1,000,000 * 150% = 1,500,000 + 5% = 1,575,000 - 1,000,000 = 575,000)
6 300%
7 350%

* To discourage users from mining Spawners every night before they go to sleep or before a raid, when you first place a spawner it'll start off at 60% efficiency (100% efficiency is the normal amount), every hour that the spawner has been placed it's efficiency goes up by 5%. This means that your spawner will be back to normal in 8 hours, 58 hours if you have a level 7 Spawner (Max Efficiency is 350% at level 7).

**Comment by cyberpwnn** [comment]
### Technic 1.0 Released!
https://github.com/cyberpwnn/Technic/commit/e53d66010ba9ab6be8344a92a1e9c5b8484aee7c
