### ISSUE TITLE
Potion Field Multiblock

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#213]
With this multiblock structure, it takes a potion and creates a potion effect in the given area that lasts for 3 seconds, but has a larger AoE. can be useful for killing off mobs

**Comment by CosmicFyre** [comment]
Could it be fueled? a hopper feeds items into the top of the structure. The effect given is determined by the item fed, like when you brew in vanilla, same ingredients too.

**Comment by cyberpwnn** [comment]
Yeah, that's the idea.

**Comment by cyberpwnn** [comment]
Really on hold now
