### ISSUE TITLE
Unable to craft Vacuum Hoppers or Ender Chests

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#214]
Currently cannot craft EnderChests or Vacuum Hoppers

**Comment by cyberpwnn** [comment]
DESCRIBE THE TITLE

**Comment by SwiftSwamp** [comment]
Shush :p Resolved.

**Comment by cyberpwnn** [comment]
Still an issue

**Comment by SwiftSwamp** [comment]
Assuming what you were making never got finished, reminder notes;

* Disable crafting of Beacons, Hoppers, Golden Apples with a Metadata of 1 (Allow normal Golden Apples to be crafted) then allow the crafting of Hoppers with the name and or lore of the Vacuum Hopper.

**Comment by cyberpwnn** [comment]
No, No. You are still blocking it. Im assuming YOU never finished your part on this. :P

I sure have https://github.com/cyberpwnn/GlacialRealms/issues/252

**Comment by cyberpwnn** [comment]
Why has this not been resolved
