### ISSUE TITLE
Vacuum Hoppers mispelled

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#216]
Spelled as "Vaccum"

**Comment by SwiftSwamp** [comment]
Now I know why I've been misspelling it...

**Comment by cyberpwnn** [comment]
Yeah, i realized it in the post.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/90a4f43d3e3e8ef51800f72416798d99208e53a0

**Comment by SwiftSwamp** [comment]
Dpeloyed
