### ISSUE TITLE
Nether core Multiblock Structure 

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#218]
- Multiblock structure: Nether core
- 3x3 size
- sets entities on fire inside it`s AoE

**Comment by cyberpwnn** [comment]
Open for discussion

**Comment by SwiftSwamp** [comment]
I like this, some may want to use this instead of the other one for say cows, could still use Beacon as the base block but change the other blocks to Obsidian, Quartz and Netherrack?

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/9dee9a23e69bbd60a2225beb6d4b7767bf3d6a4d
