### ISSUE TITLE
Multi Block Protection

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#220]
Anyone can break a Multi Block Structure regardless if they have the permission or not, same as the Blast and other issues regarding Island / WorldGuard protection, haven't tested it on Factions but assuming it's the same.

**Comment by cyberpwnn** [comment]
### Will Require Phantom S7

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/b1ca80ef640d919907eb82debc8592981149ee6a
