### ISSUE TITLE
Item Rename Bug

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#225]
Get the Source Code (YES, I HAVE IT, UNBELIEVABLE RIGHT?!?) off me.
There's actually a few bugs but my solution resolves all of them and is how it's meant to be anyways.

* Make it so you can't put anything in the second slot of an Item Rename Anvil GUI, I highlighted it in Red below.
![irn](https://cloud.githubusercontent.com/assets/3534551/19412473/215d704c-92e5-11e6-9a83-1a4b2364fbf7.png)

**Comment by cyberpwnn** [comment]
Drop support for multiple protocols to fix this.

**Comment by SwiftSwamp** [comment]
When I say that's how it's meant to be, I meant like could you make it that way :P It was never made to be that way to begin with and Skyblock doesn't support 1.7.

**Comment by cyberpwnn** [comment]
Why not just an inv gui

**Comment by SwiftSwamp** [comment]
Sure

**Comment by cyberpwnn** [comment]
#232
