### ISSUE TITLE
Enchantments are dropping levels if over max

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#226]
So I got kit snow when it first updated witch have eff8 and unbreaking 8 I used for couble day and I maxed out even spend 2 dollar on a item rename tag on it yester at like 2pm to 4 my pick was still eff8 and unbreaking 8 I went to work and came back at 8 to 9 found out my pick turned to eff5 and unbreaking 3 so can you guys please check what happen

**Comment by SwiftSwamp** [comment]
I mentioned in-game that without being able to recreate this there's nothing we can do about it, could you please give me more information. What are all of the enchantments on the pickaxe, what were you doing at the time with the pickaxe when it suddenly lost the enchantments?

**Comment by cyberpwnn** [comment]
MaxLevel: false

**Comment by dragonking1121** [comment]
I was using it in the morning when I com back I let ims ice girl borrow it and she did [item] I realized my pick turned to eff5 so I got the pick back and it stayed at eff5 and my enchant were eff8 and unbreaking 8 moss v forge 1 essence 3 and fortune 3

**Comment by dragonking1121** [comment]
I meant imsnicegirl

**Comment by dragonking1121** [comment]
And I traded with imsnicegirl maybe that the issue

**Comment by dragonking1121** [comment]
Swift I just found another bug I have a glaical pick I put mossv on it and all the other enchant then 30 to 20 min later my mossv is gone then I put another mossv on it so if I lose it agian I have proof

**Comment by cyberpwnn** [comment]
Please make another issue for that

**Comment by cyberpwnn** [comment]
Merged #244

**Comment by cyberpwnn** [comment]
Someone resolve this
