### ISSUE TITLE
Blast durability hits negative

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#227]
Enchantments on tested pickaxe (in order): Efficiency 5, Unbreaking 3, Fortune 3, Blast 5.

It's hammering away at the Durability easily, not even 15 seconds of mining and it already went through the 1500 durability from only mining about 100 blocks and it's allowing us to go into negative durability.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/0d4e52df9be93c8cbc4ed743c5fa95e5b76b3ad1
