### ISSUE TITLE
Kitpvp auto potion macro

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#228]
Kitpvp is a hackfest.

**Comment by Puretie** [comment]
Super srs dood. like, I was totally about to bone my girlfriend, but then some guy auto dropped a splash potion, and she said 'dere was nooooooooo way.

**Comment by SwiftSwamp** [comment]
How's it feel to get marked Stale?

**Comment by cyberpwnn** [comment]
Not as bad as more than 10 issues that dont get done marked as stale.
