### ISSUE TITLE
Rage 2 only gives strength 1

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#233]
Rage 1 and rage 2 currently both give strength 1, giving no real difference between the two.

Rage 1 also cancels out your strength 2 potion effect when a potion is drank.

**Comment by cyberpwnn** [comment]
Same for Reinforced

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/9e12b65865f8dac6af331c6f79cbb0409bc5f32b
