### ISSUE TITLE
Block Coiflip in combat

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#234]
When pvping, if someone activates your coinflip, it takes over your screen and you can not close it.

**Comment by cyberpwnn** [comment]
#235

**Comment by SwiftSwamp** [comment]
Not something we can prevent, waiting on the Author: https://www.spigotmc.org/threads/coinflip-csgo-gambling-plugin-paid.148116/page-4#post-1961062
