### ISSUE TITLE
Booster Additions

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#24]
### General List

* Boosters share the same Database so if you bought say a Fly Booster, you could go onto Factions or Skyblock and use it (Once used, it's gone of course)
* Typing /boosters or /booster will open a GUI that shows you a list of all of your Boosters and how many you have of what booster and to use a booster you just simply click on the booster and it'll use one
* Make sure Boosters stack, say 2 people used the same booster it'd add the time onto it
* Boosters in the GUI are auto sorted / ordered based on the multiplier for the booster and booster type
* General Give Command: /booster give {username} {booster} {multiplier} {amount}
* General Give Global Command: /booster giveglobal {username} {booster} {multiplier} {time} (The username in this one is to say who's currently activated the on-going booster, if a booster is stacked.. it'll show the first one then once that time is up and it's moved onto the "next" guys booster, it'll switch to his name or just list all the names for the current activated boosters and remove them as theirs expires)
* /booster check - Will show you what current boosters are activated and by who
* Multipliers support decimals, i.e. 1.5

### Booster List 

* There are two types of Boosters, Global which anyone online during the Booster will receive the benefits then the normal / single type where only the person using them receives the benefits
* Sell Boosters, allows you to gain a bonus for items you sold
* Experience Boosters, allows you to gain a bonus for Experience Gained
* Spawn Boosters, increases the spawn rate of monsters (Global Only)
* Growth Booster, increases the growth rate of plants/trees/etc (Global Only)
* Fly Booster, gives everyone temp access to fly (I want the GUI for the booster but it's handled with pex timed permissions, so ability to set what command a certain booster might do?)
* McMMO Booster, gives everyone additional access to mcmmo experience gains (Same as fly)
* Prison Sell Multipliers (Same as Fly/McMMO)
* Kill Multiplier Booster, gives you a multiplier on the amount of money you get per kill (Same as Fly/McMMO/Prison)
* Drop Boosters, increases the drop rates or drop amounts (unsure) (Global Only)

**Comment by cyberpwnn** [comment]
This needs to be broken up into smaller issues.

**Comment by SwiftSwamp** [comment]
Oops, will do.
