### ISSUE TITLE
Reinforced 2 only gives damage resistance 1

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#240]
Reinforced 1 + 2 both give resistance 1, giving no difference between the 2.

The effect does not stay applied, it's at 0 seconds, then gone, then back at 0 seconds. When you open your inventory, your inventory is constantly shifting due to this.

**Comment by cyberpwnn** [comment]
Related to #233

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/9e12b65865f8dac6af331c6f79cbb0409bc5f32b
