### ISSUE TITLE
Spawner Mining / Items Disappearing 

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#243]
Spawners should go straight into your inventory when mined, this is very useful for Skyblock.. especially since the Islands are floating and people have non-stop lost their spawners. This would also of course be useful on Factions for people with grinders 40 feet in the air that always lose them :p

EDIT: Actually when dropping any item or mining things that go onto the ground, farms, etc.. they for some reason just randomly disappear, not sure what the cause might be.

**Comment by cyberpwnn** [comment]
I have kept chaining this block event to the point where its really difficult to do anything with breaking spawners. Also, i still would have to drop them when their inventories are full. Wheres the risk?

**Comment by GetDerpy** [comment]
Maybe make it so you need magnetic?

**Comment by CosmicFyre** [comment]
it currently does exactly that for cobblestone, it automatically puts the item in the inventory, is there a way to switch the cobble for spawners instead?

**Comment by cyberpwnn** [comment]
I could just make the itemstack not sway left or right.

**Comment by SwiftSwamp** [comment]
Sure, another main issue (Not sure if this is enchanted related or not..) when mining is they just vanish, poof.

**Comment by cyberpwnn** [comment]
I still dont know what is either removing or "vanishing drops" i need more information on this.

**Comment by cyberpwnn** [comment]
Try disabling action-cull-drops and increasing the value of it.

**Comment by cyberpwnn** [comment]
This likely has nothing to do with the magnetic enchantment or Effex at all.

**Comment by SwiftSwamp** [comment]
Ended up being React's drop culling,
