### ISSUE TITLE
Enchant lost

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#244]
Swift I just found another bug I have a glaical pick I put mossv on it and all the other enchant then 30 to 20 min later my mossv is gone then I put another mossv on it so if I lose it agian I have proof

**Comment by SwiftSwamp** [comment]
I'm sorry but I'm not sure what's going on, are you losing the enchantment Mossy off the pickaxe, is it disappearing entirely, or?

**Comment by dragonking1121** [comment]
It was working and then I realize my pick is not repairing I notice I lost my mossv and have to repair it agian

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/GlacialRealms/issues/226
