### ISSUE TITLE
Vacuum Hopper

### ISSUE THREAD

**Issue by TheBoy64** [cyberpwnn/GlacialRealms#246]
I can't craft a vacuum hopper, it will tell me I'm not allowed to craft hoppers :P

**Comment by SwiftSwamp** [comment]
Just waiting on the Authors response, may have to make our own quick thing if he takes too long: https://www.spigotmc.org/threads/stopcrafting.101596/#post-1963478

**Comment by cyberpwnn** [comment]
#214
