### ISSUE TITLE
Enchant book not working with normal books

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#247]
I enchant a whole bunch of books and intrude to put it on my axe a pick every time I do that my book is gone and no enchant was put on my pick or axe and my exp bar won't even update and every time I buy a enchant book from spawn it always updateds

**Comment by dragonking1121** [comment]
Updates

**Comment by GetDerpy** [comment]
Confirmed, only books bought from /xpshop are applying to items.

**Comment by SwiftSwamp** [comment]
Need more info, I bought books from the Enchanter at /warp enchant and was able to apply books like normal, the only time I lost any books is when I tried drop enchanting a NON enchanted book.

**Comment by GetDerpy** [comment]
@SwiftSwamp books purchased from /xpshop work, however, books obtained using enchant tables will not apply. Book vanishes, but leaves no enchant on the item.

**Comment by dragonking1121** [comment]
Yea and when ever u enchant a book ur exp stats don't update only when u do /exp but at spawn u can buy a book and it update right away

**Comment by cyberpwnn** [comment]
It may have to do weather it is an ENCHANTED BOOK or a BOOK with enchantments on it.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/de5f815a413c6358986a23ce1b3b238978eb74a7
