### ISSUE TITLE
Crates and Crate Rewards Overhaul [Factions]

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#248]
Love the current crate animation, however, when opening a large amount of keys, or if you're just an impatient person, there needs to be a way to quickly open them. Maybe shift clicking the crate with the key instantly gives you the reward, or exiting out of the animation GUI instantly ends it.

Spawners are currently too common from vote keys. I have witnessed someone with 14 vote keys walk away with 12 spawners, testing myself does show pretty high rates. Look at the rates and maybe lower them.

**Koth Crate**

- Add Frostbite Kit
- Add Fly boots
- Remove eff 8 axe, pick and shovel, merge into one Eff 8 Tools Kit
- Add 2x Koth Keys
- Add 100k XP
- Add 2x Item Rename
- Remove Sharp 5 Sword / Axe - Add Sharp 5 book
- Add Looting 5 Book
- Add Unbreaking 4 Book
- Add Punch 2 Book

**Crystal Crate**
Crystal crate is currently no better than a vote crate.

- Remove pig and cow spawners
- Add IG spawner
- Add 10x and 30x MCMMO
- Add 1x Item Rename
- Add 2x Item Rename
- Add 2x Crystal Crate Keys

**Frozen Crate**
- Add 1x Item Rename
- Add 2x Frozen Crate Keys
- Add 3x Item Rename
- Add 15x and 45x MCMMO

**Glacial Crate**
- Add 20x and 60x MCMMO
- Add 4x Item Rename

**Comment by SwiftSwamp** [comment]
* https://www.spigotmc.org/threads/mysterycrates-sale-cr-prime-preview-crates-archon-style-cs-go-style-most-customizable.47477/page-84#post-1966208
* They're already semi low.. I could raise the percents in the items that come before the spawners.
* Are you sure these are the items you want added / removed from the Crates?

**Comment by cyberpwnn** [comment]
Make a cyberpwn crate. Call it the **Sodium Crate**
