### ISSUE TITLE
Suggestion: AutoSell [Factions/Skyblock]

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#249]
Toggled via /autosell

When inventory is full, automatically sells everything that is sellable in your inventory. 

Would be obtained temporarily from crates. IE Daily crate could have a chance to give you 1 hour of /autosell, koth 2h, crystal 3h, frozen 6h, glacial 12h. Vote parties could also give access.

**Comment by cyberpwnn** [comment]
What if instead it would be a pickaxe enchantment that sells everything it breaks? It would consume a little more durability but it would sell everything you mine

**Comment by GetDerpy** [comment]
It's useful for more than just mining. Selling mob drops and stuff like that. Just open the chest, put the stuff in your inventory until full, BAM, auto sold all items.

**Comment by cyberpwnn** [comment]
What if its a multiblock structure that, any items put into it would be sold? That way not everyone right off the bat can just auto sell and perm-afk

**Comment by cyberpwnn** [comment]
You could then use hoppers to put items into it.

**Comment by SwiftSwamp** [comment]
I'm against auto selling, it's extremely op as is imo.
