### ISSUE TITLE
Staff chat in game

### ISSUE THREAD

**Issue by Spliggy** [cyberpwnn/GlacialRealms#251]
I was thinking that it'd be quite helpful to have an in game staff chat, within the regular chat feed. This way it'll be a lot easier to communicate with staff whilst playing, and would make it easier to tell them something that they may need to know, without having to go to skype.

It could be toggled with something like /sc (staff chat) and so it can turn on and off, and in chat, before the message, if it's in staff chat, it says [Staff] or [Staff Chat] or something..

Something that I think could be very handy for the staff members and could make some things quicker.

Thanks

**Comment by cyberpwnn** [comment]
Probobly do a channel system yeah. @SwiftSwamp open for discussion.

I was thinking you could have an option to mute all other chat channels

For example all staff members can see the staff chat, but you can have the option to mute the main chat for yourself so you can see only the staff chat

**Comment by CosmicFyre** [comment]
its already on the event server

**Comment by cyberpwnn** [comment]
So this isnt an issue?

**Comment by GetDerpy** [comment]
We only have it on event server because Jafforo and I have console access to it and add what we want. 

Could use this? https://www.spigotmc.org/resources/bungeestaffchat.12665/

Staff chat being global would be useful.

**Comment by GetDerpy** [comment]
Also a /chattoggle would be useful for ALL players. Turn off chat messages from other players and only show server messages and commands.

**Comment by Spliggy** [comment]
Yeah, it would be very helpful to have global

and I agree it'd also be helpful to be able to turn off chat or staff chat whenever, so you only see the other.

And yeah it could be helpful for all players to have it, some people turn off their chat, but then they don't get server messages ( @GetDerpy )

**Comment by cyberpwnn** [comment]
So now just make it so you can just turn off global chat unless you are a staff in which case it only shows staff messages?

**Comment by Spliggy** [comment]
Yeah sounds good..

Have you added the staff chat already?

**Comment by cyberpwnn** [comment]
I think it is implemented. Not sure though.

**Comment by Spliggy** [comment]
Whats the command?

**Comment by cyberpwnn** [comment]
Not sure though.

**Comment by Spliggy** [comment]
I don't think it has been added yet. They said its in event server, but not global.

**Comment by cyberpwnn** [comment]
Well i guess we will wait until it progresses.

**Comment by SwiftSwamp** [comment]
Waiting on Jafforo's reply, I'm not seeing what is being used on the event server.

**Comment by cyberpwnn** [comment]
Im closing this for now.
