### ISSUE TITLE
Bugs and Suggestions forum to redirect to this tracker

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#254]

**Comment by GetDerpy** [comment]
I personally feel like it would be better keeping this issue tracker staff only. Stuff gets added, stuff gets done. On the forums, there's more discussion and investigation. Half the people who post bugs don't have enough evidence or explanation. It would be better having this for certain people who are knowledgeable and active with helping resolve bugs.

**Comment by GetDerpy** [comment]
This area also has more sensitive information, such as dupes and glitches that shouldn’t be seen by the general population.

**Comment by cyberpwnn** [comment]
While that may be true, swift is plowing through the staff suggestions and volmitting them here anyways. The issue with the foums, you cannot mark duplicates as easily, moderating threads is a pain, and having the ability to tag things, and close issues is very powerful.

Also, both the forums and this issue tracker are public. People can post their findings however they like. Plus, i would rather have them come out and post the dupe. It makes us more likley to fix it faster.

**Comment by cyberpwnn** [comment]
This was initially posted on @SwiftSwamp's behalf, im just bringing it here.

**Comment by GetDerpy** [comment]
Do we really want it flooded with stuff like "My maxed out pickaxe vanished on prison, but I don't have evidence, can I have a new one anyway?" and stuff like that?

**Comment by cyberpwnn** [comment]
Yes, i can close them faster here. Its not as bad as you would think. The more issues the easier it is. You have a clear view of where the direction of the projects need to go and where they are.

I have managed AND been a part of far larger projects issue trackers. Its actually better in my opinion

**Comment by SwiftSwamp** [comment]
GitHub encourages me to go through Issues quicker as well and we can easily decline Suggestions if we don't feel like they're worth while.. also if someone get's really bad we can even block them from our repos.

**Comment by cyberpwnn** [comment]
Are we doing this or not? Im fine either way. Plus people are already contributing. We need to come to a decision on this.

**Comment by cyberpwnn** [comment]
Well this is dead
