### ISSUE TITLE
Technic Block Condenser

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#256]
Used in conjunction with vacuum and filter hoppers, could be a dropper maybe. 

Only condensible items pass through it. EG, iron, gold, diamonds, etc. Once items enter it, they will not leave it until the correct amount of items are in it to condense. So if 4 iron pass into it, it will wait until there is 9 iron, condense it into a block, then push it out.

**Comment by cyberpwnn** [comment]
Interesting. Seems good.

**Comment by cyberpwnn** [comment]
Could be designed to work with #465

**Comment by cyberpwnn** [comment]
On hold
