### ISSUE TITLE
Better Faction Warps System

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#259]
- = Required parameter.

All commands below can be used by faction admin only. 

/f setwarp [*warpname] [password]
/f setallywarp [*warpname] [*allyfaction] [password]

/f warp [*warpname] [password]
/f allywarp [*allyfaction] [*warpname] [password]

/f delwarp [*warpname]
/f delallywarp [_allyfaction] [_warpname]

Limit of 5 faction warps, and 5 ally warps per ally.

Setting a warp costs $25k.

Teleporting to a warp had a warmup of 5 seconds.

**Comment by cyberpwnn** [comment]
On hold
