### ISSUE TITLE
Party Chat

### ISSUE THREAD

**Issue by NoahOG** [cyberpwnn/GlacialRealms#261]
Party chat goes from skyblock 1 to skyblock 2 and the parties are combined.

**Comment by SwiftSwamp** [comment]
This will require a network reboot to fix, guess the last update the Author pushed.. they didn't test it before pushing it and it's half broken. It's fixed, just waiting for the reboot.

**Comment by cyberpwnn** [comment]
If the netboot isnt ready but the issue is fixed, ill close it.
