### ISSUE TITLE
Staff can override pvp on islands

### ISSUE THREAD

**Issue by NoahOG** [cyberpwnn/GlacialRealms#262]
Staff can pvp on skyblock islands, being a island member or just visiting does not matter.

**Comment by NoahOG** [comment]
Edit: only staff can.

**Comment by SwiftSwamp** [comment]
Yeah, that's meant to be like it for Mod+, they override protection, if I disable it then you guys can no longer do things like break Chest Shops, investigate certain issues, etc.
