### ISSUE TITLE
Skyblock 2 boundary issue

### ISSUE THREAD

**Issue by Dazzzza12** [cyberpwnn/GlacialRealms#267]
You can build outside the boundary of your island, if you don't get what I mean it's when you leave your island but you can still carry on building on ( if that makes sense )

**Comment by cyberpwnn** [comment]
Assuming you mean any block, not just multi blocks. Its probably something swift needs to change.

**Comment by GetDerpy** [comment]
You sure this isn't just cos you're admin?

**Comment by cyberpwnn** [comment]
Valid point. Needs confirmation.

**Comment by SwiftSwamp** [comment]
Cannot reproduce, protected like it should be. Closed as Dazz forget's he has bypass perms a lot :P
