### ISSUE TITLE
Stacked mobs dropping stacks larger than 64

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#270]
- I killed a zombiepigman by pushing off a great height and when it died i picked up these two stacks of items:
[http://imgur.com/a/6UvQp]

**Comment by SwiftSwamp** [comment]
Unable to reproduce, could you give me the coordinates of where you did this and how many were stacked in a mob?

**Comment by CosmicFyre** [comment]
right around -12, 297 on sb2, also i believe there were 650[ish] zps stacked

**Comment by GetDerpy** [comment]
Just tried with 1001 zp stacked a couple times, could not replicate

**Comment by SwiftSwamp** [comment]
Were you actually able to use the items or did they vanish / disappear when you went to touch them.

**Comment by cyberpwnn** [comment]
This could be a protocol issue. Typical bukkit doesnt even allow this unless it is a plugins doing.

**Comment by CosmicFyre** [comment]
upon clicking the items the stack continued to go back to normal size, dropping normal stacks as i did
[-111 to 0/256 to 64 [aka lots of items]]

**Comment by SwiftSwamp** [comment]
Great, closed. This tends to happen from time to time but as long as you can't actually dupe anything, seems fine.
