### ISSUE TITLE
Effects not truly being infinite

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#273]
On the test server.. we resolved this and you had set everything to about 30 seconds to keep recounting back up, however that's not the case again and everything is being set to 0 seconds still.

**Comment by GetDerpy** [comment]
/effect _Derpy 21 1000000 1 gives me the effect for **:** - why not just do that?

**Comment by cyberpwnn** [comment]
What Effect. Depending on the effect it is different. For example, night vision gets set to 30 every 20 ticks, and the damage resistance and strength push to 4 ticks every 1 tick.

**Comment by cyberpwnn** [comment]
The only reason they arent infinite right now is due to the issue with 3.0 the cycle tick was failing. However 3.1 fixes this. Problem resolved
