### ISSUE TITLE
Enchantapi

### ISSUE THREAD

**Issue by Dazzzza12** [cyberpwnn/GlacialRealms#278]
When you do /enchantapi book you get a free book, tested on skyblock don't know other servers.

**Comment by Steave0982** [comment]
Yeah, it gives you a book with a description of all the enchants

**Comment by cyberpwnn** [comment]
What is the problem?

**Comment by cyberpwnn** [comment]
Reopen if there is an issue with this.

**Comment by Dazzzza12** [comment]
You can edit the book, so if you wanted a book and quill you can just do that command and then remove everything inside and get a free book
