### ISSUE TITLE
Vacuums

### ISSUE THREAD

**Issue by gadboizzz** [cyberpwnn/GlacialRealms#279]
Your IGN (only if applicable): Gad

Bug: Vacuums cannot be crafted because there's a ban a hopper crafting

Server: Skyblock 2 (and presumably 1)

Proof (if needed):
![2016-10-17_20 52 27](https://cloud.githubusercontent.com/assets/22900214/19460751/88cdddfc-94ac-11e6-9465-ba31c3ad7ffa.png)

Extra (optional): I had to make an account for this... really?

This is just a longer version of this thread:
https://github.com/cyberpwnn/GlacialRealms/issues/246
With hopefully for info.

(Didn't see that thread or that Swift commented)

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/GlacialRealms/issues/214
