### ISSUE TITLE
Add Anti Factions Territory Logoff 

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#282]
https://www.spigotmc.org/resources/anti-factions-territory-log-off-factionsuuid-supported.13659/

It is a common strategy when raiding someone, to log alts off inside the valuable parts of the base, so that when the faction fixes up the base and starts using it again, you can simply log on the alt and raid it all again without having to cannon. 

This plugin will stop that.

Also stops people who get kicked from the faction still being in the base when they log on.

**Comment by SwiftSwamp** [comment]
I'm actually surprised that we've never thought of this before, added.. thanks!
