### ISSUE TITLE
Add No Water Flow Redstone

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#283]
https://www.spigotmc.org/resources/no-water-flow-redstone.15122/

One issue with cannoning is if one part of your cannon blows up, or you accidentally break a block, the resulting water flow messes up a lot of your redstone. This plugin prevents flowing water or lava from breaking the redstone on your cannon.

**Comment by SwiftSwamp** [comment]
This also adds back in Obsidian Generators :P Do we really want this ;p

**Comment by GetDerpy** [comment]
WorldGuard has the config option "disable-obsidian-generators". That should fix it?

**Comment by SwiftSwamp** [comment]
It was a joke, it's actually one of those bugs from 1.7 (like tnt) that just kinda was used as a legit feature but it was later patched in 1.8. Added though.
