### ISSUE TITLE
Salvager NCP

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#285]
Salvager NCP at spawn, clicking him opens up a chest GUI that is split in half.

Anything put in the left side is to be salvaged, the ncp puts in the right hand side what you would get as a result of salvaging. Buttons at the bottom to confirm or reject the salvage offer.

Salvager is used to salvage:
- CE Books
- Armor with CE's

Any CE book placed in the salvager will result in the salvager offering you an XP bottle worth 30% of the custom enchants value. So, with the current system, if you put in a book that was from a Scholar enchant you would receive an xpbottle worth 4344 XP.

If you put a piece of armor in the salvager p has custom enchants on it, you would recieve an XP bottle worth 20% of the value of each enchant. So if you had a diamond helmet with 2 Scholar level enchants on it, you would be offered 2 XP bottles worth 2896 XP each.

**Comment by CosmicFyre** [comment]
So an XP salvager, however i wouldn't do it for enchanted items, just enchanted books. It gives one more reason for people to raise thier salvage mcmmo

**Comment by GetDerpy** [comment]
@CosmicFyre does mcmmo even salvage the custom enchants?

**Comment by cyberpwnn** [comment]
On hold

**Comment by SwiftSwamp** [comment]
Moving the priority up for release, I believe it's important for the release for those mass purchasing Books after saving up to get ahead of the rest.
