### ISSUE TITLE
/wild putting you in peoples claims

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#286]
When doing /wild in the end, I have noticed on several occasions that it has put me inside another factions claim. Not sure if it happens in other worlds, but because the end is so small maybe that's why it's doing it. I am unsure if /wild would put me inside a factions base, so far it has only put me inside the claim.

**Comment by SwiftSwamp** [comment]
That's very odd, it shouldn't be. I'll check it out.

**Comment by SwiftSwamp** [comment]
Hmm, try now. May have been my bad.
