### ISSUE TITLE
Admins don't bypass Commune Cooldowns

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#289]
Admins do not bypass the command cooldowns in Commune.

**Comment by cyberpwnn** [comment]
What cooldowns. There is like 4 different cooldown things

**Comment by SwiftSwamp** [comment]
Modified issue with the proper info

**Comment by cyberpwnn** [comment]
If they have the permission ```commune.god``` they can bypass all commune commands.

**Comment by SwiftSwamp** [comment]
I'm still not bypassing Command Cooldowns and we're on Phantom E2 and Commune 8.7.

**Comment by cyberpwnn** [comment]
needs to be confirmed on the dev server later tonight
