### ISSUE TITLE
Disable Enchantment Table Hotkeying

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#290]
Disable the ability to use hotkeys out of an Enchantment table, instead of shift clicking or clicking an item out some people will use the numbers to quickly move an item from the enchantment table back into there hot bar which entirely ignores everything and just converts the item into a book with the items name on it.

**Comment by cyberpwnn** [comment]
Impossible.

**Comment by SwiftSwamp** [comment]
Other possible solutions than? It's eating items.

**Comment by cyberpwnn** [comment]
Need another way of doing this.
