### ISSUE TITLE
Xpbottles not giving xp

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#293]
Xpbottles do not give you xp if you throw them and they don't break on a block

**Comment by cyberpwnn** [comment]
Needs confirmation.

**Comment by cyberpwnn** [comment]
Right click a block when you place it.

**Comment by SwiftSwamp** [comment]
You know you wanna fix it ;p What about doing something where it'll say... "You need to be looking at a block in order to throw this!" as a temp fix?

**Comment by CosmicFyre** [comment]
They also dont give you xp if your not close enough to where they break

**Comment by MattMonkeyy** [comment]
I 'broke' the bottle whilst I was on the ground and 'broke' it onto the ground then i just the amount of exp I would get from a normal not the 218867 that was registered on it....
 http://glacialrealms.com/forums/threads/bug-skyblock-exp.2888/#post-27042

**Comment by cyberpwnn** [comment]
Look at the block you are standing on and right click it with the bottle in your hand.

**Comment by MattMonkeyy** [comment]
So I don't get a refund on my 218867 exp @cyberpwnn

**Comment by cyberpwnn** [comment]
Have swift get on that part. 

Im probably going to see a feature request for this crap anyways :P
