### ISSUE TITLE
Blocks with inventory don't drop inventory when blown up

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#294]
Chests, hoppers, droppers, dispensers, furnaces, etc do not drop their inventory when blown up by creeper egg or tnt.

This is a major problem as you often have to blow a chest up to get access to its loot when raiding a faction who have protected their chests.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/FAP/commit/98e12febc27f64abf60358a2fc64625bc78074c8
