### ISSUE TITLE
Give mods /god

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#295]
Can you give mods /god on skyblock please? i was grinding today and someone had a /home infront of me.. i couldnt see b/c i was inside a blaze at the time and ended up killing him...

**Comment by SwiftSwamp** [comment]
I'm not sure what God would do for Mods if the situation was you killing the apposing players, although Mods should already have access to Gods. To me it sounds like the bypass for Islands allowed you to kill someone else.

**Comment by cyberpwnn** [comment]
Close if resolved
