### ISSUE TITLE
Potions Drop unstacked on death.

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#296]
When you die with stacked potions they drop unstacked

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. While this may be low priority, 23 days seems unacceptable for a valid enhancement. @cyberpwnn

**Comment by cyberpwnn** [comment]
Cannot stack potions on death without stacking potions on pickup.

**Comment by cyberpwnn** [comment]
(impossible without a ridiculous amount of effort meaning cpu).... ehem, yes bukkit scan all of the chunks in a location added by a "guess vector" to where the items "could have gone" ignoring water and other physics just to scan for the drops in a radius of that point, then remove the items that could be stacked and then update the amounts. Not worth the effort, not worth the processing.
