### ISSUE TITLE
Weird island Lock glitch.

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#297]
I really doubt this is repeatable but anyway..
Skullblood had his alt afk-mining on his island. [skyblock2]. the island was locked yet the alt was still cooped.  at some point the alt had glitched and wasnt breaking blocks. Assumedly because of super-breaker. A suggested solution was to move the alt back using water, placing a block infront of it, then moving it back with water after it had broken the placed block. However, i believe the real cause was that the alt had somehow become un-cooped, and since the island was locked, the alt was expelled as soon as it moved. either way, as soon as the alt moved out of its current block it was sent to the nearest block outside the island and dropped in the void.. not good. is there a better way than simply dropping players in the void instead of /spawn?

**Comment by SwiftSwamp** [comment]
Hmm, that's very odd. I can report it to the plugin author but without being able to easily recreate he probably won't be able to do much, however I can send players to spawn on void drop.

**Comment by SwiftSwamp** [comment]
You should now teleport to spawn on void falling, however I wouldn't test this with armor on if you were going to :P
