### ISSUE TITLE
Randomly going into /v

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#298]
LOTS of the time players complain that i'm in /v when i'm not, i can tell since i don't have invis 2 effect on. Yet they still cant TAB my name, message me, see me etc.

**Comment by Coltxx** [comment]
All of the mods on skyblock 2 are stuck in /v FYI!

**Comment by SwiftSwamp** [comment]
Do you guys go into Vanish then get stuck in Vanish or do you just login stuck?

**Comment by cyberpwnn** [comment]
Log in vanish with the dumb lightning and bat crap on factions.

**Comment by CosmicFyre** [comment]
this is on sb2, i log on and everyone can see me etc, i never run the command and then some time later im apparently in /v

**Comment by SwiftSwamp** [comment]
That's extremely odd, we only have the Essentials Vanish on the Skyblocks.

@cyberpwnn The VanishNoPacket is only on Factions, however I'll look into other better overriding Vanish plugins.

**Comment by cyberpwnn** [comment]
YEAH

**Comment by cyberpwnn** [comment]
Is this still an issue
