### ISSUE TITLE
Commune AntiCrafting doesn't work

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#299]
The built in anti crafting you made for Beacons, Hoppers and Gapples does not work. Everything can craft and I'm using Commune 8.6, Phantom S9.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/40c9b94418e5dd4693eac736a490542926e4a5eb

**Comment by SwiftSwamp** [comment]
Deployed
