### ISSUE TITLE
FAP Causes Certain Blocks to not Function

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#301]
The latest version of FAP (1.5) causes Pistons to just ignore whatever is in front of it and push through it causing the entity / players to go inside the blocks thus resulting in broken Pistons, I didn't try this with anything else but that's as far as I know, I had to revert as no farms were usable due to this, the Pistons were just pushing through everything.

**Comment by SwiftSwamp** [comment]
Here's an image for clarity. https://gyazo.com/9b3c51fc60f631bec43983204952039d

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/FAP/commit/19d742506e47d0fb722954b2de9e15bb37187b6c

**Comment by SwiftSwamp** [comment]
Deployed
