### ISSUE TITLE
Drop Enchanting Hack and Slash

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#303]
You removed the blocking of Sharpness 5 on Axes back here #93 , however.. now you also need to do a hack and slash to allow the drop enchanting of Sharpness 5 onto Axes as it's not allowed by default Minecraft.

**Comment by CosmicFyre** [comment]
looting as well?

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/e462de6d75583fa0c2fceb694ce0e1d65f913e43
