### ISSUE TITLE
Koth tracking

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#31]
Add koth win tracking for Factions and a place holder for it (The /f who section is in the config so you can test if it works)

**Comment by cyberpwnn** [comment]
They are using apis i dont have access to. Ill have to try manually finding it.

**Comment by SwiftSwamp** [comment]
Alright, just let me know how it goes.

**Comment by cyberpwnn** [comment]
On hold

**Comment by SwiftSwamp** [comment]
This would be better suited for the stats system, thoughts ?
