### ISSUE TITLE
Cannot Drink potions on kitpvp unless moving

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#314]
http://glacialrealms.com/forums/threads/kitpvp-potion-bug.2879/

**Comment by SwiftSwamp** [comment]
Isn't much we can do about this, however there *is* a ViaVersion option to enable something to help** fix drinking on 1.10. I've enabled it but it probably won't take effect until a reboot as changing most of ViaVersion's features requires a reboot to properly enable.
