### ISSUE TITLE
Add MCMMO Potion Ingredients To Shop

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#315]
http://glacialrealms.com/forums/threads/mcmmo.2884/

Add the following to the brewing shop so people can brew mcmmo potions:

Slimeball B:70 S:0
Quartz (Not quartz block) B:30 S:0
Red Mushroom B:15 S: 5
Brown Mushroom B:15 S:5
Ink Sack B:100 S:0
Fern B:100 S:0
Poison Potato B:100 S:0

**Comment by SwiftSwamp** [comment]
Wouldn't adding those to the shop take out the fun of grinding :P

**Comment by GetDerpy** [comment]
You literally can not get some of the stuff in this list, and its only the same as having normal brewing ingredients in the shop?
