### ISSUE TITLE
Boosted Furnace Multiblock Structure

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#316]
Create some type of Furnace that's "Boosted" and or "Over Clocked" to push items through it faster, however at the cost of using up more fuel, you can also add a bunch of fuel to a chest that it'll eat up out of.. the fuel chest could be a Trapped Chest, Furnace is of course a furnace.. the actual increased speeds, unsure of.. open for discussion.

**Comment by cyberpwnn** [comment]
./mbh smeltery
