### ISSUE TITLE
Soul Eruption Removal

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#317]
What are the current rates of each Soul Eruption levels, it seems a bit op? (In a bad way, i.e. killing themselves quicker than anything else on just mobs)

**Comment by cyberpwnn** [comment]
Soul eruption is a pointless enchantment anyways. There is no gain. It cannot be overpowered.

Since you damage +2 damage, you take +2 damage. I can change the numbers but it doesn't change how "op" it is.

**Comment by SwiftSwamp** [comment]
When I say op, I mean towards yourself, at least towards mobs it kills you pretty quickly, what amount disabling it against mobs?

**Comment by CosmicFyre** [comment]
Alot of people dont use it [including me] because of this, and ive seen people say that its killed them even with a god apple on.

**Comment by cyberpwnn** [comment]
I say remove it, :P Claimed that from the start

**Comment by SwiftSwamp** [comment]
Yeah, go ahead and remove it.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/0d52253e522fce51bb7c945eaf1e2f84a88a0676
