### ISSUE TITLE
Forge is not always working

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#321]
Forge is not always working for me I mine whole bunch of ores and I'm still getting ore blocks forge work sometime like I'm still getting little inget but stack if ore block

**Comment by SwiftSwamp** [comment]
Please provide more details such as what you're exactly mining, how you're mining it, what all of the enchantments are on your pickaxe, what server this is on.

**Comment by dragonking1121** [comment]
Sorry I just figure it out
