### ISSUE TITLE
Glitched spawners lost when placing

### ISSUE THREAD

**Issue by EaglePlaysYT** [cyberpwnn/GlacialRealms#322]
I had a iron golem and 7 cow spawners and 15 hoppers and lost them all i saw them in my /chest 2 for a moment and when i tried to place them back they disapeered

**Comment by EaglePlaysYT** [comment]
Btw my Ign is EaglePlaysYT

**Comment by dragonking1121** [comment]
I prob need more details

**Comment by dragonking1121** [comment]
You*

**Comment by SwiftSwamp** [comment]
Was this Skyblock 1 or 2 and when did it happen ?

**Comment by cyberpwnn** [comment]
Give me a step by step how to reproduce your issue.

**Comment by EaglePlaysYT** [comment]
this was skyblock 1
and i checked to place  my spawners from my pv 2 because they got rolled back and when they were in my hand and i placed them i saw them flicker for  a second under the slab where i would place them and they just disapeered
i had 14 hoppers 7 cow spawners and 1 iron golem spawner

**Comment by SwiftSwamp** [comment]
Are you sure you didn't lose them during the small roll back?

**Comment by cyberpwnn** [comment]
No information. No confirmation. No reproduction. No issue.
