### ISSUE TITLE
Moss IV 

### ISSUE THREAD

**Issue by alego75** [cyberpwnn/GlacialRealms#323]
My name is alegofreak
and my pickaxe with moss IV is not fixing 
everything else is working just not my moss

**Comment by SwiftSwamp** [comment]
What server and what other enchantments do you have? Please provide more information.

**Comment by alego75** [comment]
cyber how do i  reopen it?

**Comment by alego75** [comment]
My name is alegofreak
and my pickaxe with moss IV is not fixing 
everything else is working just not my moss
this is on skyblock

**Comment by SwiftSwamp** [comment]
I need you to give me the information I asked for please, I can't do anything with that.

**Comment by alego75** [comment]
swift how do i edit the post i am new to github

**Comment by SwiftSwamp** [comment]
Post a new comment with the information that way I'm alerted.

**Comment by SwiftSwamp** [comment]
Applied some fixes and there has been no response from op, reopen a new issue if this continues.
