### ISSUE TITLE
Issue That happened liek  20 mins ago?

### ISSUE THREAD

**Issue by MrChimpyNuts** [cyberpwnn/GlacialRealms#324]
Welp the server rolledback and i kinda lost 4 spawners 2 of them were overclocked (blaze spawners all of them ) i would like to get em back coz the spawners were a gift.. to a grill thanks for ur time !! Have a nice day ~~MrChimpynuts

**Comment by SwiftSwamp** [comment]
Hello,

Sorry but there was a small rollback for everyone, whoever gave you the items will need to regive them back to you.
