### ISSUE TITLE
Sorry for not having  more info here is more Moss  not working

### ISSUE THREAD

**Issue by alego75** [cyberpwnn/GlacialRealms#325]
My name is alegofreak
and my pickaxe with moss IV is not fixing 
everything else is working just not my moss
ON skyblock2  on my island

**Comment by cyberpwnn** [comment]
Dont create another issue. Just reopen the old one

https://github.com/cyberpwnn/GlacialRealms/issues/323

**Comment by alego75** [comment]
how do i re open it
