### ISSUE TITLE
Blaze Stacks Despawning after only a few hits.

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#326]
IGN: Thesportsgamer
Bug: Whenever I hit blazes like 4-5 times the whole stacks disappers, from 50-1000!!!
Server: Skyblock Servers

From: http://glacialrealms.com/forums/threads/sb-blaze-problems.2910/#post-27332

others have also noticed this.

**Comment by SwiftSwamp** [comment]
resolved, open another issue if it persists.
