### ISSUE TITLE
Money notes and Xp Bottles Glitch

### ISSUE THREAD

**Issue by Coltxx** [cyberpwnn/GlacialRealms#327]
When you have a stack of multiple money notes or xp bottles and you try to use 1 its uses the whole stack and gives you the amount of only 1 xpbottle or 1 money note.

**Comment by cyberpwnn** [comment]
How did you get the money?
How did you get the notes?

**Comment by CosmicFyre** [comment]
./withdraw, this just happened to combatwombat010

**Comment by CombatWombat010** [comment]
I had 9x$234,588 notes withdrawn and I clicked on a chest with them, 1 not got put back in my bal, where the other 8 just disappeared. I'm missing $1,876,704 from this glitch.

**Comment by cyberpwnn** [comment]
Should we just make a better note system? I mean notes on their own cause problems because item stacks are not reliable.

**Comment by CosmicFyre** [comment]
ok i thought i had a way around. i didnt. long story short i just lost 8M [plz swift can i has?] But in doing so i found that when you redeem a money note it takes ALL notes out of your inventory and gives you the money from only 1.

**Comment by SwiftSwamp** [comment]
Removed as a Bug as I've deployed a new withdraw / deposit system.
