### ISSUE TITLE
Entropy Destruction

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#328]
### Entropy Singularity
The entropy singularity is created with rare drops found in ores and mob drops. This entropy, once created can be loaded into an Entropy detonator. 

### Entropy Detonator
The entropy detonator is a multiblock structure which loads in one entropy singularity and detonates it causing a small radius of blocks exploded out into all directions literally ripping up the terrain.

### Entropy Launcher
The entropy launcher launches entropy singularities at the given target. It only has 3 uses before the structure cannot withstand the force of the singularities anymore.

![image](https://cloud.githubusercontent.com/assets/10619135/19669862/b55eaf7a-9a30-11e6-84bb-28d09822380f.png)

**Comment by CosmicFyre** [comment]
Sooo.. it explodes and shoots blocks everywhere? looks more like a griefing tool to me

**Comment by cyberpwnn** [comment]
it pulls in blocks which orbit around an entropy point, then in about 5 seconds they explode out

**Comment by cyberpwnn** [comment]
![i318 cimgpsh_orig](https://cloud.githubusercontent.com/assets/10619135/19694616/11fe94ca-9aae-11e6-8844-05e591293406.png)

**Comment by CosmicFyre** [comment]
Could there be tiers? I, II,III , each with a bigger Structure, sucking in more blocks

**Comment by cyberpwnn** [comment]
Sure

**Comment by cyberpwnn** [comment]
Actually, this probably isn't a good idea for factions or skyblock. Ill probably use it on a new server  hint hint.
