### ISSUE TITLE
Purchasing Amount Shown Bug

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#335]
The max amount shown when purchasing / selling when it goes to tell you how much money you have left caps at 2.147b, as you can see I have way more than that.

![money](https://cloud.githubusercontent.com/assets/3534551/19709376/007c1b3c-9af4-11e6-827b-53c89e9e5a05.png)

**Comment by cyberpwnn** [comment]
Convert ints to longs

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/CurrencyShops/commit/fe71d389b2b6ae69f323c91f1c5bd9171baa4143
