### ISSUE TITLE
Iron grip is not working

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#336]
I was using my brother acc mining on sb2 since he was a member and don't have /God he die of hunger and the pick I give him have iron grip on it when I resplendent the pick was gone you can check lock that we traded the pick
Pickaxe enchant
Eff6
Unbreaking6
Fortune 3
Moss v
Essence3
Iron grip1

**Comment by dragonking1121** [comment]
Also forge 1

**Comment by dragonking1121** [comment]
I mean I died with iron grasp and it should've kept my pick when I die but it dident

**Comment by dragonking1121** [comment]
And when I repair my pick was gone

**Comment by SwiftSwamp** [comment]
Iron Grasp isn't a 100% chance that you'll keep the item. It's high but not 100%.

**Comment by SwiftSwamp** [comment]
Regarding the repairing, please open a new issue regarding that. Keep issues separate.
