### ISSUE TITLE
Coal Blocks bug out in furnaces.

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#343]
- The "flames" texture above the fuel slot does not appear but the furnace consumes the fuel and starts cooking. The block does change to Lit_Furnace tho
- Something caused the furnaces [when i used coal blocks] to bug out and only cook 2 items before the fuel ran out.

**Comment by SwiftSwamp** [comment]
This should have since been fixed, needs confirmation.

**Comment by cyberpwnn** [comment]
Reopen if still an issue
