### ISSUE TITLE
Silk Spawner Silk touch Spawners

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#347]
http://prntscr.com/czwdj8
Breaking a spawner, each time you break a spawner, and anyone who has silk touch.

**Comment by SwiftSwamp** [comment]
I read in the Group Chat that the guy actually just mined a normal spawner.

**Comment by cyberpwnn** [comment]
What?

**Comment by SwiftSwamp** [comment]
Not a bug, can't replicate. Guy probably mined a normal spawner.
