### ISSUE TITLE
Sync Queuing Failing

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#348]
Recently I've noticed (Thanks to you for rereminding me how pha n works) that if a server has no players on it when the sync command is done, it never get's sent to that command despite the queuing system.

**Comment by cyberpwnn** [comment]
It takes about 20-50 seconds possibly even more for a transmission that is queued to send to actually send to a server that was previously offline.

**Comment by cyberpwnn** [comment]
For a successful transmission
1. Server A and B must be online
2. Server A and B must be on the same bungeecord network
3. Server A and B must have at least 1 player on each.

**Comment by SwiftSwamp** [comment]
Hasn't been working like that, 24 hours could past with all servers online and if no one was on at the time of the queue it just never gets flushed out even when someone does end up joining it finally.

**Comment by cyberpwnn** [comment]
It might be trying to send it prematurely when a player does end up joining.

**Comment by cyberpwnn** [comment]
Phantom fixed it

**Comment by cyberpwnn** [comment]
For SOME REASON this is still an issue

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. @cyberpwnn

**Comment by cyberpwnn** [comment]
![images](https://cloud.githubusercontent.com/assets/10619135/20532848/7700fa96-b0a9-11e6-942d-cf6d02fffbcc.png)

**Comment by Puretie** [comment]
REDIS SAVE DAY WITH DAKKA DAKKA SYSTEM.

**Comment by cyberpwnn** [comment]
DAKADAKKADKAAAKDKADAKKAAAAA

**Comment by cyberpwnn** [comment]
DAKAKAKAKAKADAKKADAKADAKA

### Phantom Zenith 2
* Adds Higher order permission system
 * /pha zenith [add/remove/get] <player>
 * Can only be used via console (CHECK PEOPLES CONSOLE ACCESS)
* Adds CTN (Commands Through Net) 
 * /ctn broadcast simplicity
 * You will get a response when it has been executed and how long ago it was executed

![image](https://cloud.githubusercontent.com/assets/10619135/21740765/543aa564-d491-11e6-8a0c-b9b1e8fec0b6.png)

You need to configure the ppa.yml before you can use ppa packet connectivity.

**Comment by cyberpwnn** [comment]
This is officially resolved 

https://github.com/PhantomAPI/Phantom/commit/4ca1d861321354a5d829865deb8749dd80cf148c
