### ISSUE TITLE
Standing on lily-pads is glitchy - Sb2 PVP

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#349]
Standing on a lily-pad in the pvp arena of SB2 causes you to bug out and get stuck, it is impossible to get off without being knocked at the precise moment or warping out, which in a pvp arena..

From: http://glacialrealms.com/forums/threads/skyblock2-pvp-lily-pad-glitch.3105/
Tested and confirmed.

**Comment by SwiftSwamp** [comment]
Removed the Lilypads.
