### ISSUE TITLE
Hoppers disappear when mined with Magnetic

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#352]
If you mine a Hopper with Magnetic the Hopper disappears and if it has items inside they'll fall out.

**Comment by cyberpwnn** [comment]
So you dont get a hopper with magnetic?

**Comment by SwiftSwamp** [comment]
Correct, if it has items in it it'll drop them but the Hoppers just disappear, it eats them. Vacuum or Regular.

**Comment by cyberpwnn** [comment]
Re-open if still an issue after updating

**Comment by SwiftSwamp** [comment]
Not sure if a recent patch caused this to start happening again but it's happening again.

**Comment by Jayzunn** [comment]
This only occurs while using magnetic which is an enchant put on your boots, it is fairly self-explanatory.

**Comment by SwiftSwamp** [comment]
Jayzunn, I wanted you to provide information that was related to this issue but it wasn't just with Hoppers. You said that you can't place blocks with Magnetic Boots on either because they'll get sucked back up into your inventory.

**Comment by cyberpwnn** [comment]
I can place blocks with magnetic
