### ISSUE TITLE
Making the trade inv bigger 

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#356]
When do do /trade we don't have mush space I think it should be larger

**Comment by dragonking1121** [comment]
When do do /trade we don't have mush space I think it should be larger

**Comment by cyberpwnn** [comment]
How do you propose making the inventory larger than the max size?

**Comment by SwiftSwamp** [comment]
You can't, the inventory is as big as it's going to get, I removed 2 rows of useless buttons to increase the size when it was previously suggested.
