### ISSUE TITLE
Unable to enchant Looting 3 on an Axe

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#358]
https://youtu.be/Tlftkz5zwYE

**Comment by cyberpwnn** [comment]
Wasnt this resolved @SwiftSwamp

**Comment by SwiftSwamp** [comment]
Nope, still says invalid. Same with some other enchants.

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. @cyberpwnn, please review the video at hand, and reconfirm that it is still not working. Assigning @SwiftSwamp To gather more information regarding the other aforementioned enchantments.

**Comment by SwiftSwamp** [comment]
It's still an issue, a recommended solution instead of the white / black list is to just completely remove the per specific enchanting with vanilla enchantments as this was originally added due to Sharpness 5 books being easily obtainable which has sine been "fixed'.

**Comment by cyberpwnn** [comment]
So your down with knockback 2 sharpness 5 bows that also shoot infinite flaming arrows?

**Comment by cyberpwnn** [comment]
Suit yourself https://github.com/cyberpwnn/Effex/commit/79cf300a03da286ffb451d94c1c604c27b1f9bc0
