### ISSUE TITLE
When tpa expires, a new one can not be created.

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#359]
http://glacialrealms.com/forums/threads/tpa-glitch.3068/

**Comment by SwiftSwamp** [comment]
Is this still an issue? I've deployed a few things regarding Essentials teleporting system since.

**Comment by Nohaxnoskill** [comment]
Oh This did happen to me the other day

**Comment by SwiftSwamp** [comment]
I'm unable to reproduce it, I've tried it multiple times. Please record a video and reopen this issue if it happens again.
