### ISSUE TITLE
Make is coop stay

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#360]
If the person who coop the person leave the server or go to another server it uncool the person who's is cooped

**Comment by SwiftSwamp** [comment]
I'm sorry but I'm not understanding your suggestion.

**Comment by dragonking1121** [comment]
When u coop Someone to ur is it uncool them if u leave the server I think it shouldn't do that

**Comment by SwiftSwamp** [comment]
You have the ability to remove someone from your island if you no longer want them apart of it.
