### ISSUE TITLE
Cows don't get pushed by pistons 

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#361]
https://youtu.be/NrbR3XAOP7U

**Comment by cyberpwnn** [comment]
Confirmed FAP

**Comment by cyberpwnn** [comment]
#390

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/FAP/commit/0e1c3a50a51bc46a8900d3d4855fe703e7fa31b9
