### ISSUE TITLE
Redstone clocks dont work

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#362]
https://gyazo.com/565af80c78e65c7f132f81dee1e688bf
The redstone signal just freezes.

**Comment by SwiftSwamp** [comment]
Please provide more information such as what server this is on, when did it start happening and are you able to recreate it indefinitely?

**Comment by cyberpwnn** [comment]
Could be react

**Comment by cyberpwnn** [comment]
Reopen if there is more information
