### ISSUE TITLE
Water doesn't flow correctly 

### ISSUE THREAD

**Issue by Formalized** [cyberpwnn/GlacialRealms#364]
Skyblock2.
Place water down, let it flow, hit a block, remove the water. Some will be left.

**Comment by SwiftSwamp** [comment]
Tested it out, this was the cause of FAP 1.8.

**Comment by cyberpwnn** [comment]
![image](https://cloud.githubusercontent.com/assets/10619135/19839785/795e199c-9ebe-11e6-8be4-86120aa11f88.png)

How?

![image](https://cloud.githubusercontent.com/assets/10619135/19839790/975b10bc-9ebe-11e6-8c08-5dff89c83cd2.png)

**Comment by cyberpwnn** [comment]
Cannot confirm.

**Comment by CosmicFyre** [comment]
http://imgur.com/a/Zhn8a
My island skyblock2, underneath the IG grinder if u need to confirm

**Comment by SwiftSwamp** [comment]
Could you record a video of it happening from the moment you place the water until the end please. Unable to recreate on the Developer Server.

**Comment by CosmicFyre** [comment]
I have no idea how the hell i did it ._. I will try to recreate when i can

**Comment by cyberpwnn** [comment]
#390

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/4c7aac5635eb22b0e01e3f59fa45f69b1766e00c
