### ISSUE TITLE
Giving Titles to Offline Players

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#370]
Add the ability to give offline players titles, we spoke about it and decided to just make it a scheduling system.

**Comment by cyberpwnn** [comment]
```
new Task()
{
    public void run()
    {
         if(swiftOnline)
         {
              new S()
              {
                   giveTitle(swift, "Bad");
              };
         }
    }
};
```

**Comment by SwiftSwamp** [comment]
I found that more funny than I probably should of xD

**Comment by cyberpwnn** [comment]
You might need the uuid

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Titles/commit/07ced77359e5abaf76fe147ad9507d538c1cc6a1
