### ISSUE TITLE
Pistons not breaking non-solid blocks

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#372]
Simply pushes them.

**Comment by kotik1998** [comment]
Pistons are not working again on cows spawners.
![2016-11-02_09 30 51](https://cloud.githubusercontent.com/assets/23015769/19923416/3a40c7d2-a0df-11e6-8b7d-009722e0fcee.png)
![2016-11-02_09 31 24](https://cloud.githubusercontent.com/assets/23015769/19923426/3fc19cae-a0df-11e6-8181-525ff70a1ba9.png)
![2016-11-02_09 31 31](https://cloud.githubusercontent.com/assets/23015769/19923431/42f626ce-a0df-11e6-9ed6-4e1778a9b934.png)

**Comment by cyberpwnn** [comment]
I have a feeling that has to do with something completely different. It might have to do with pressure plates

**Comment by kotik1998** [comment]
how do we fix it then?

**Comment by kotik1998** [comment]
i tried wood and stone, both failed

**Comment by SwiftSwamp** [comment]
Are you sure this isn't default Minecraft Physics, same thing is happening locally without FAP.

**Comment by SwiftSwamp** [comment]
Try now

**Comment by kotik1998** [comment]
what type of them?
wooden , stone ?

**Comment by SwiftSwamp** [comment]
Anything, just let me know if it's still happening.

**Comment by kotik1998** [comment]
Tested right now .
Yes it's still does

**Comment by kotik1998** [comment]
Afk'ed for 10 hours on cow farm
still broken, but not worse than the other day  that (all of them we're broken).
![2016-11-03_09 31 37](https://cloud.githubusercontent.com/assets/23015769/19961080/7ff7754a-a1a8-11e6-8f35-804139ad5680.png)

**Comment by kotik1998** [comment]
Trying to do a redstone activation on all Piston, just to fix the Block out of the place. 
Fixed that with use of redstone and some flip flop torches to toggle them all, working fine. 
But still improve more on that glitch

**Comment by cyberpwnn** [comment]
#390

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/FAP/commit/66bf188963079a9ff16e63ddf055dc94c44377a3
