### ISSUE TITLE
Silk Touch not working with Magnetic boots

### ISSUE THREAD

**Issue by kotik1998** [cyberpwnn/GlacialRealms#375]
Silk Touch not working with Magnetic boots

**Comment by cyberpwnn** [comment]
Confirm for new update

**Comment by SwiftSwamp** [comment]
Still doesn't work, just drops onto the ground.

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. Please reconfirm the issue is still prevalent @cyberpwnn

**Comment by cyberpwnn** [comment]
There is no way in bukkit to just tell what its going to drop. So basically the only thing i can do is define a massive list of items and what they drop manually.

However since i have no idea what it drops, there is a high chance for many dupes or even worse. Closing.
