### ISSUE TITLE
Pvp in hub

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#376]
When you turn on PVP with the magma-cream, you still can't pvp in hub.

**Comment by cyberpwnn** [comment]
World Guard @SwiftSwamp

**Comment by SwiftSwamp** [comment]
Hmm, I had pvp set to true.. ahh I had invincible still set to allow, oops.. however now it says (!) Both fighters must turn on pvp (hotbar) even though it's on.

**Comment by SwiftSwamp** [comment]
Ahh, oops. I had the pvp flag enabled.. however invincible was still allowed.
