### ISSUE TITLE
Hoppers Won't Fill with ChestShop Assigned on the Filling chests.

### ISSUE THREAD

**Issue by kotik1998** [cyberpwnn/GlacialRealms#379]
Hoppers Won't Fill with ChestShop Assigned on the Filling chests.

Should i make a video or not?

**Comment by GlacialSean** [comment]
It's always nice to have a video showing it, so yea.

**Comment by SwiftSwamp** [comment]
Are you using normal Hoppers or Vacuum Hoppers?

**Comment by kotik1998** [comment]
Normal Hoppers

**Comment by CosmicFyre** [comment]
I believe this is 100% intentional as part of the plugin, You dont want someone to completely bypass the shop by just sucking all the items out of it, and you dont want someone to fill the shop with completely useless junk using a hopper either.

**Comment by cyberpwnn** [comment]
#390

**Comment by SwiftSwamp** [comment]
ChestShops are protected from allowing Hoppers to take / remove items to and from them, however if you think this should be disable on purely Skyblock make a suggestion, I'm against it as it can be used to untraceable take items from Chests.
