### ISSUE TITLE
Factions Sand bug

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#380]
https://youtu.be/TkDh3AwF26A
When there's an explotion, sand goes back up when it's supposed to drop.

**Comment by cyberpwnn** [comment]
#390

**Comment by cyberpwnn** [comment]
![image](https://cloud.githubusercontent.com/assets/10619135/20123538/cf2415ee-a5ed-11e6-9708-dbd2ea6a4368.png)

Cannot reproduce
