### ISSUE TITLE
Water Flow Glitch on Creative server

### ISSUE THREAD

**Issue by kotik1998** [cyberpwnn/GlacialRealms#381]
When u cover a water source the rest simply dont dissapear.

EDIT:
It create another source :/  i'm struggling building thing on creaive with water ussage

**Comment by SwiftSwamp** [comment]
Suggestion: Add Liquids as a bypass for Hadron's physics controllers

**Comment by cyberpwnn** [comment]
"Hadron's physics controllers"

No.

**Comment by cyberpwnn** [comment]
Cannot reproduce on development server, needs reproduction steps.

@SwiftSwamp ensure FAP is up to date

**Comment by SwiftSwamp** [comment]
We ended up figuring out this was because of Commune, I believe you released Commune with the fix but never closed this?

**Comment by cyberpwnn** [comment]
THEN CLOSE IT

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/GlacialRealms/issues/364
