### ISSUE TITLE
Kit PvP map needs to be changed back

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#384]
Needs to be switched back to normal, it's still halloween themed

**Comment by SwiftSwamp** [comment]
Need to also change Prison back.

**Comment by Coltxx** [comment]
Swift, its colt. If you would like me to change them back. I would not mind. But it would have to wait until Sunday afternoon around 1PMEST.

**Comment by SwiftSwamp** [comment]
New revamped map has been added in with the everything being ported over (i.e. shop, holograms, etc)
