### ISSUE TITLE
Physics Issues 

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#390]
* Water not draining correctly #364 
* TNT Not updating +1 range sand #380 
* Hoppers not self-updating #379 
* Pistons not pushing entities #361 
* Pressure Plates and Redstone not updating #377 
* Pistons not breaking non-solid blocks #372

**Comment by kotik1998** [comment]
Damn you work hard cyber gj bud ;)

**Comment by SwiftSwamp** [comment]
What did we end up figuring out when we discussed this?

**Comment by cyberpwnn** [comment]
Nothing. It wasn't discussed.
