### ISSUE TITLE
Event server needs Via Version

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#392]
Currently it is 1.8.8 and you can only join with 1.8 versions. Make it so you can join with 1.9 and 1.10 as well

**Comment by SwiftSwamp** [comment]
That's odd, ViaVersion should've been added a long time ago.
Yeah, just checked, ViaVersion is on it.

**Comment by SwiftSwamp** [comment]
Update: Yeah, I was able to join it just fine with 1.9 and 1.10.
What error are you getting when attempting to join?

**Comment by cyberpwnn** [comment]
Should close it if its not an issue

**Comment by SwiftSwamp** [comment]
I'm waiting for more information, I linked him it asking what he meant by this as I was able to join just fine with both 1.9/1.10.

**Comment by SwiftSwamp** [comment]
No response from the OP, closing.
