### ISSUE TITLE
Add Lucky & Cumulative Voting

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#395]
Add Lucky & Cumulative Voting for all servers.
Rewards are currently open for discussion.

#### Skyblock(s): ####
* Waiting for Discussion

#### Factions ####
* Waiting for Discussion

#### OP Prison ####

Cumulative Voting (rewarded once, days until is based off voting 3 times a day straight):

* 10 Votes (3.3 days of voting) - 500 tokens 
* 25 Votes (8.3 days of voting) - 1000 tokens
* 50 Votes (16.6 days of voting) - 3000 tokens
* 100 Votes (33.3 days of voting) - 5000 tokens
* 250 Votes (83.3 days of voting) - 3x frozen crate key 
* 500 Votes (166.6 days of voting) - 5x glacial crate key 

Lucky Voting

* 1/10 Voting Chance - 100 tokens
* 1/50 Voting Chance - 200 tokens
* 1/100 Voting Chance - Random Title?
* 1/250 Voting Chance - 1000 tokens
* 1/500 Voting Chance - frozen crate key 
* 1/1000 Voting Chance - Thinking Store Credit / Rank or something?

#### KitPvP ####
* Waiting for Discussion

#### Creative ####
* Waiting for Discussion

**Comment by kotik1998** [comment]
define this, what shoud we win when we're voting?

**Comment by SwiftSwamp** [comment]
Updated Prison.

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. Missing information, perhaps @SwiftSwamp could host a poll on the forums?

**Comment by SwiftSwamp** [comment]
You're absolutely right, needs more community discussion. Opened a thread for further input: http://glacialrealms.com/forums/threads/lucky-cumulative-voting.3853/

**Comment by SamGlacial** [comment]
I like it

**Comment by cyberpwnn** [comment]
Yeah, same. Why the hell is this not stale. or closed if its on the forums now.

Either keep this lovley stale tag or close it

**Comment by Puretie** [comment]
I'm going to actually put this on hold until we have compiled all the info from the forums and decided on a course of action. @SwiftSwamp will be left to open it when he has the necessary information.

**Comment by SwiftSwamp** [comment]
This was done, sorta...was moved to the forums anyways. Removing the On Hold tag.

**Comment by iiRedBullPvP** [comment]
so is this being added?
