### ISSUE TITLE
Setting Changes when PvP is Enabled

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#399]
When you Enable PvP in the hub the following should be set:

* Turn off Hub Movement (However you can turn it back on with PvP enabled, it's just turned off when first enabling PvP) 
* Give the player some sword of Sword & Bow (Not too op unless you want to equip them with armor, maybe cool random colored leather armor?)
* Give them an Infinite Stack of Snowballs (If this is possible, if not just give them a bunch)
* Remove any Server Selectors?
* Send a message saying "Turn off PvP to change servers!"

Sorry for the multiple in one but I didn't feel the need to make a separate issue for each, they kinda go together.

**Comment by cyberpwnn** [comment]
WORLD GUARD
