### ISSUE TITLE
Sync & Switch to LuckPerms

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#400]
Merge the databases together and switch to LuckPerms, much better for network wide perms while having per server group permissions separate from the rest.

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. Please see to this immediately, @SwiftSwamp, as high priority tasks should not be left to go stale!

**Comment by cyberpwnn** [comment]
Clearly this isnt a priority.

**Comment by SwiftSwamp** [comment]
On hold until we can figure out a better way to convert, clearly there is some issues with the migration or any system we've attempted to implement. Me and Dan spoke about a few things we could do, will try that in the next few days.

**Comment by SwiftSwamp** [comment]
Working with the author of SexyPex to help as there's some data issues. Closing.
