### ISSUE TITLE
Make XP useful on KitPvP

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#401]
Right now, you can get XP bottles from voting, however you can't use them for anything. Maybe make a /xpshop or anything?

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. Please follow up on this issue, @SwiftSwamp.

**Comment by SwiftSwamp** [comment]
What do you propose we add to this XP Shop?

**Comment by GlacialSean** [comment]
Non game changing custom enchants, like something that drops a head from the person you killed. 
Also maybe make a poll on the forums and ask what the players want?
(3-4 suggestions in poll + let them comment if they want something else)

**Comment by cyberpwnn** [comment]
So just cosmetic crap? We want xp to be useful but we dont want it to actually give anyone a benefit? Lovely.

**Comment by Puretie** [comment]
I propose the ability to transmute a certain amount of experience into an xp apple of sorts. Very minor, so as to make it balanced, of course. At least this way the player would have a balanced in-game way to spend their xp in a worthwhile manner.

**Comment by Pjinky** [comment]
Maybe Potion effects. Ex. you can buy strength for 5 minutes, etc. ?

**Comment by cyberpwnn** [comment]
Stale.

**Comment by SwiftSwamp** [comment]
Closing as this has been moved to my personal notes, will be deployed shortly.
