### ISSUE TITLE
EnchantmentAPI Placeholder Not Reverting

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#402]
We're currently using EnchantmentAPI Placeholder v4.27 due to the v4.28 being supposedly built against 4.28, however please still look into it to see if we can use v4.28 as it fixes a few important bugs such as "Fixed enchanting not reverting the placeholder sometimes" which is the biggest loss from enchantment items at the moment.

**Comment by cyberpwnn** [comment]
There is no api change, update it or dont, effex should comply either way.
