### ISSUE TITLE
Replace GlacialNote

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#407]
Find a replacement for GlacialNote and all of it's features

**Comment by dragonking1121** [comment]
To what

**Comment by cyberpwnn** [comment]
Yeah, be descriptive

**Comment by SwiftSwamp** [comment]
They're notes for me, not you :P

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. Please follow up with further information regarding this issue.

**Comment by SwiftSwamp** [comment]
Working on it now, however old Money Notes, Withdrawn EXP & McMMO Credits will have to be converted by Admins.

**Comment by SwiftSwamp** [comment]
This is ready to be deployed, just waiting on a question I asked Dan before deploying it.

**Comment by cyberpwnn** [comment]
What question.

**Comment by SwiftSwamp** [comment]
> Hey, is there a way I can get this exact one to copy into notepad++ to have the same arrow: \u25b6

**Comment by cyberpwnn** [comment]
Please give actual information and not todo's if it's going to stay open for more than a week.

**Comment by SwiftSwamp** [comment]
Closing, replaced iwth #543
