### ISSUE TITLE
Kitpvp doesn't have snow kit

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#409]
I was in kit pvp and realize I do t have kit snow their

**Comment by CosmicFyre** [comment]
make a store inquiry..

**Comment by dragonking1121** [comment]
I have kit snow on every server beside that I was wondering if it's a bug

**Comment by CosmicFyre** [comment]
Cyber i think he just means that he personally doesnt have it on kitpvp, ive seen snow kit on it before.

**Comment by SwiftSwamp** [comment]
GitHub is for Issues / Suggestions, not Server Inquiry's, you can make a proper one here: http://GlacialRealms.com

**Comment by dragonking1121** [comment]
Swift in kit snow in shop says we get potion
