### ISSUE TITLE
Mining Spawners with silktouch + Haste 2 break the spawners.

### ISSUE THREAD

**Issue by kotik1998** [cyberpwnn/GlacialRealms#411]
Lost 2 ZP spanwers , tested with magnetic and without magnetic.

**Comment by kotik1998** [comment]
found the error ,
Haste 2 is broke on mining spawners, tested on 2 cow spawners.

**Comment by SwiftSwamp** [comment]
I just mined with Haste from a Beacon + Silk Touch and received the Spawners every time.

**Comment by kotik1998** [comment]
well i mined with eff4 unb3 silk1 with Haste on me and didnt worked

**Comment by SwiftSwamp** [comment]
I just tried it with those enchants as well, was able to mine just fine too. 
Were the spawners overclocked and if so to what level.

**Comment by SwiftSwamp** [comment]
Update: I was able to mine Overclocked ones just fine as well.

**Comment by kotik1998** [comment]
im gonna recreate with 2 cow spawners.

**Comment by kotik1998** [comment]
well i'm not lying about this sittuation but seems it's working normaly again. Well RIP 2 cows and 2 ZP :/

**Comment by SwiftSwamp** [comment]
I'd be more than happy to refund you your Spawners, I just need to be able to recreate the bug properly.

**Comment by kotik1998** [comment]
i recreated myself the bug and they mined .......

**Comment by SwiftSwamp** [comment]
I understand that the bug happened to you but I need to be able to recreate it, if you can provide more details that would be great such as; What was going on at the time, any theories on what you think could have caused it since you were the one mining it, was there anything different with the way you mined these.

**Comment by kotik1998** [comment]
if it happens again il Post here a Reply on this topic. Saying the Timestamps what i did step-by-step.

**Comment by SwiftSwamp** [comment]
Alright, reopen the issue if it happens again with reproduction steps, I can't do anything if I'm unable to reproduce it.
