### ISSUE TITLE
Starting a CF takes your money and has no output

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#412]
Sorry for lack of details, was unable to get online and test it. Was told via skype chat. Creating a cf works fine, and its listed. when someone else tries to play it just takes the money, no chat output, no gui popup, nothing.

**Comment by kotik1998** [comment]
lost 500k due to this glitch ;/

**Comment by Nohaxnoskill** [comment]
Yes this is true Cosmic

**Comment by SwiftSwamp** [comment]
Sorry but I'm not fully understanding the issue, from what I'm hearing it's doing what it's meant to, it's just not telling you when it takes the money.
For example, you start a game and it takes say 500k that you added to it, it just doesn't tell you it's taking 500k, correct?

**Comment by Nohaxnoskill** [comment]
It doesnt say if you won or lost.

**Comment by SwiftSwamp** [comment]
That's not really a bug, so it's just not alerting you?

**Comment by kotik1998** [comment]
Swift do SB1 and do /cf and choose The__Vortex Coinflip look what happens

**Comment by Nohaxnoskill** [comment]
No like you dont even get money if you win...

**Comment by SwiftSwamp** [comment]
Ahh okay, reported to Author. Keep updated with the progress here: https://www.spigotmc.org/threads/ultimatecasino-cs-go-style-paid.159231/page-7#post-2009628
