### ISSUE TITLE
Hoppers Dont Fill The Right Chests

### ISSUE THREAD

**Issue by Nohaxnoskill** [cyberpwnn/GlacialRealms#413]
I've been noticing that when i come back from afking the 1 and 3 chest are full and not the 2 chest

**Comment by SwiftSwamp** [comment]
Could you please give me the coordinates , your username and what server this is on.

**Comment by Nohaxnoskill** [comment]
My IGN is nohaxnoskill and I kinda just rebuilt my ig farm and that is where the issue was so i will see if it still will happen

**Comment by SwiftSwamp** [comment]
Alright, please comment back on this Issue letting me know.

**Comment by Nohaxnoskill** [comment]
K Will do

**Comment by Nohaxnoskill** [comment]
Ok, This isn't me but this is xxxthe_beast profit shop also has the same issue as I stated above

**Comment by SwiftSwamp** [comment]
That still doesn't give me the server or coordinates, also are you trying to put items into a ChestShop?

**Comment by Nohaxnoskill** [comment]
One is a profit shop and one isnt

**Comment by SwiftSwamp** [comment]
Hoppers don't work with ChestShops.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/GlacialRealms/issues/379
