### ISSUE TITLE
Redstone Clock

### ISSUE THREAD

**Issue by Nohaxnoskill** [cyberpwnn/GlacialRealms#415]
So My redstone repeator clock won't work and its been this way for a bit and someone tried to fix it it still didnt work

**Comment by SwiftSwamp** [comment]
Please provide the server and coordinates of the clock in order for us to check it out to see what's going on, however Cyber is better with Redstone so leaving this open for him.

**Comment by Nohaxnoskill** [comment]
This is on server Skyblock 1 and the cords are X -5374.059 Y 49 Z-2335. Also its the clock on the creeper farm and i have other redstone like this around the island

**Comment by SwiftSwamp** [comment]
Since been fixed, ended up being because of React.
