### ISSUE TITLE
{bungeecount} Doesn't show amount of players in Hub when you hold tab

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#417]
https://i.gyazo.com/13a788a974558bf5510beee857fd5cca.png

**Comment by cyberpwnn** [comment]
The server has been offline (no players were on it for a while), give it about 30 seconds being online and it will correct itself. This isnt exactly a bug as much as it is a cosmetic thing. Although this will actually change soon, ill keep it open until then.

**Comment by SwiftSwamp** [comment]
This will fix with the addition of Icing (Skilling / Cosmetic System), it's being added momentarily.
