### ISSUE TITLE
React Won't Disable Reactions

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#419]
The main reason why I've barley had React on Skyblock is because of the Reactions and them not disabling, even with them individually being disabled or disabling them with the all function, they just won't disable. Right now the cull drops is happening again, same if I even crank it way up on top of disabling it drops will keep disappearing.

**Comment by cyberpwnn** [comment]
#415 is likely caused by this

**Comment by SwiftSwamp** [comment]
Sorta... fixed. You created UnReact.
