### ISSUE TITLE
Stealth Ability: Chameleon 

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#420]
### General
Chameleon simply changes the color of leather armor to CLIENTS INDIVIDUALLY depending on what is behind the player for that client specifically. 

For example, if Cyberpwn is in front of cobblestone in swift's view, swift will see cyberpwn as gray.
However, if Puretie is looking down on cyberpwn and cyberpwn is standing on purple wool, puretie will see cyberpwn as purple.

This is also applied individually per armor. So cyberpwn's lower half could be colored gray for stone, but his head and chest may be colored blue (if his upper area is near blue wool)

### Performance
As you could imagine, this would require lots of raytracing (if there are 6 people looking at cyberpwn, that would require 24 different raytraces), however the great part is **ALL OF THIS CAN BE PROCESSED ASYNCHRONOUSLY**

On top of that, raytracing will not be needed from the player to the chameleon player. Simply use the direction the player is looking at the chameleon and trace behind the player using that direction.

**Comment by SwiftSwamp** [comment]
This is freaking epic, do it up.

**Comment by Auxiio** [comment]
I cant wait daddy

**Comment by cyberpwnn** [comment]
Heh block texture mapping required (with transparency for color blending) https://github.com/PhantomAPI/Phantom/blob/master/src/main/java/org/phantomapi/texture/mapping.yml

**Comment by Puretie** [comment]
@cyberpwnn , get on it. You know what needs to be done.

**Comment by SwiftSwamp** [comment]
Hasn't this already been implemented?

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/4ac96bb972eccb31dc5f6851bb507a4875585b7a
