### ISSUE TITLE
Stealth Ability: Phantom

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#421]
A few things happen with the stealth ability
* Opening Chests do not make a sound
* Breaking / Placing Blocks do not make sounds
* Interaction (levers, buttons, flint and steel) do not make sound either
* Walking does not make a sound (sprinting does until max level)
* Eating & Potion consuming does not make a sound
* Water movement / splash does not make a sound

**Comment by Puretie** [comment]
You know what needs to be done.

**Comment by cyberpwnn** [comment]
No
