### ISSUE TITLE
Giving a Random Title Doesn't Send A Message If You Have All Of Them

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#422]
If someone receives a random title that already has all of them unlocked (thus not giving them anything), it should tell the receiver that "You already have all Titles unlocked!". Reasons: When they purchase a random title with vote points they'll think it's bugged and not working when in reality they just have all of them.

**Comment by cyberpwnn** [comment]
![image](https://cloud.githubusercontent.com/assets/10619135/20222980/5a1ccbdc-a805-11e6-8cbc-0cec6054e223.png)
Cannot confirm

**Comment by cyberpwnn** [comment]
Same for glacial realms hub

![image](https://cloud.githubusercontent.com/assets/10619135/20223022/93e40ae2-a805-11e6-9e31-623bdb6fa103.png)

**Comment by cyberpwnn** [comment]
![image](https://cloud.githubusercontent.com/assets/10619135/20231497/56433020-a830-11e6-8be6-3a17f43c63a7.png)

https://github.com/cyberpwnn/Titles/commit/c13c1ecb27682ba4e30bed529797ac0b5dfa897a
