### ISSUE TITLE
When You Rankup, What it Says..

### ISSUE THREAD

**Issue by 50ShadesOfEpic** [cyberpwnn/GlacialRealms#424]
When u rankup on prison, (beta) it says : You Have Ranked Up To (rank) Then
                                                                  Prestige I is 10T

Maybe instead of telling us the Price for prestige, tell us the next rank

**Comment by dragonking1121** [comment]
Once again suggestion on forum

**Comment by SwiftSwamp** [comment]
dragonking, the github is used for suggestions, bug reports, additions, enchantments, etc.

**Comment by cyberpwnn** [comment]
"Once again suggestion on forum"

No, please stop saying that. Suggestions and bugs are intended to go on here NOT the forums.

**Comment by SwiftSwamp** [comment]
It's just letting you know, I could always either completely remove it or change it to something you recommend.

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. Please follow up on this, @SwiftSwamp to ensure the problem is resolved.

**Comment by SwiftSwamp** [comment]
Closing for now, please reopen with a suggestion on what to change it to and why if you feel that it should be changed.
