### ISSUE TITLE
Faster Crates

### ISSUE THREAD

**Issue by 50ShadesOfEpic** [cyberpwnn/GlacialRealms#425]
It takes so long to open crates, maybe just make them a little faster or make a custom plugin that has the command /cratetype to u can pick fast crate which is just u press it and it opens or CS:GO crate which is what we have rn

**Comment by dragonking1121** [comment]
I made a suggestion about this on fourm this is for issue only

**Comment by SwiftSwamp** [comment]
I already lowered the opening rates from 7 seconds to 3, the author said he fixed it but may have not. I'll have to check it again myself and play around with it.

**Comment by cyberpwnn** [comment]
"I made a suggestion about this on fourm this is for issue only"

Please keep them on github if at all possible. There is no need to dupe. It makes our job harder

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. Please follow up on this, @SwiftSwamp and confirm that the issue has been resolved.

**Comment by SwiftSwamp** [comment]
This issue is unresolved, however you can keep up to date with the progress here: https://www.spigotmc.org/threads/mysterycrates-sale-cr-prime-preview-crates-archon-style-cs-go-style-most-customizable.47477/page-86#post-2020898
