### ISSUE TITLE
% Mined

### ISSUE THREAD

**Issue by 50ShadesOfEpic** [cyberpwnn/GlacialRealms#426]
On the scoreboard, u should see % mined so its easier to know when mines would reset.

**Comment by dragonking1121** [comment]
Put it in fourm suggestions not here

**Comment by SwiftSwamp** [comment]
dragonking, this is for suggestions too.

**Comment by SwiftSwamp** [comment]
I like it though.

**Comment by cyberpwnn** [comment]
"Forum suggestions please not here"

Actually, all of the forum suggestions should be going here. The only reason we are keeping the forum suggestions open is because not everyone has a github account

**Comment by 50ShadesOfEpic** [comment]
Itd be an ez addition and just easier in general.

**Comment by CosmicFyre** [comment]
how about making it hover above the mine center

**Comment by SwiftSwamp** [comment]
Added in, Scoreboard now tells you how much is left of the Mine. 
Regarding the rounding part, refer to issue #439

**Comment by cyberpwnn** [comment]
#461
