### ISSUE TITLE
Factions Has no Action

### ISSUE THREAD

**Issue by BobbyBoy12** [cyberpwnn/GlacialRealms#427]
Factions is getting boring no real intense battles it would be nice to add a few more koths late at night maybe staff can do events aka 1v1 events and get rewarded for who wins and factions needs more players maybe make a trailer and have people post it on their youtube channel we need a lot more players to make factions and other server within the community get more people and they can invite their friends right now im just grinding for no reason pretty boring no good raids not that many factions i can raid if the staff team can put a little more work in factions and other server that would be nice thanks have a great day 
-Bobby

**Comment by dragonking1121** [comment]
Forum suggestions please not here

**Comment by cyberpwnn** [comment]
"Forum suggestions please not here"

Actually, all of the forum suggestions should be going here. The only reason we are keeping the forum suggestions open is because not everyone has a github account

**Comment by SwiftSwamp** [comment]
We already have 3 KoTH's every 24 hours to accommodate for US, UK and AU, what timezone are you where you cannot make it to any?

What do you have in mind for events, however I'm against 1 on 1 event based at the moment. Factions is a "faction" type server, not 1v1. GROUP EFFORT! : D

We're currently working on a Trailer and we're bidding on another ad at the moment as well, the last one helped us hit 276 players but a lot of issues poped up right after so it was semi wasted. 

Yeah, we're trying to expand via Social Media, if you can find anyone please let us know (: We have a few we will be using shortly with the ad and some other things.

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule.

**Comment by SwiftSwamp** [comment]
No reply from OP, closing. Moving forward will the initial plan of more pvp based events, advertisement, youtubres and social interaction between Staff & Players.
