### ISSUE TITLE
Iron Golems spawners change to pig spawners

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#428]
https://www.youtube.com/watch?v=B7B5ziCeJzA
This was on skyblock 1, it possibly happens on other servers too, but I don't know about that.

**Comment by kotik1998** [comment]
I've tested same time when The player who got the glitched spawners.
I did it with cows mining them 5 in a row + tested OC ones + tested 1 IG OC , everything was fine.
But there probably smal chance to get that glitch that we saw in the video.

**Comment by SwiftSwamp** [comment]
Please keep an eye on #441 , we now know how to properly reproduce the bug.
