### ISSUE TITLE
Make vote create faster

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#429]
I think it takes way to long just to open a vote creat

**Comment by dragonking1121** [comment]
Create

**Comment by 50ShadesOfEpic** [comment]
why would u create this, u know i created one, and u commeneted on it...

**Comment by dragonking1121** [comment]
I though u mean crates not vote crate I'm deeply sorry for this

**Comment by kotik1998** [comment]
Close post and Yes i agree with @dragonking1121 make them faster cuz it's really slow IMO.

**Comment by SwiftSwamp** [comment]
There's already an open issue for this: https://github.com/cyberpwnn/GlacialRealms/issues/425 Please search other open issues before creating one.
