### ISSUE TITLE
Blazes Glitching

### ISSUE THREAD

**Issue by CombatWombat010** [cyberpwnn/GlacialRealms#437]
Skyblock glitch with blazes where they occasionally spawn and just stay stuck in mid air. You cannot hit them nor will they move until they despawn naturally.

**Comment by SwiftSwamp** [comment]
Could I have the coordinates of your Blaze grinder please.

**Comment by Ashleyyx** [comment]
This isn't mine but 
-8715, 23, 8150 skyblock one. (PandaGOD_Senpai'S island)

**Comment by GlacialSean** [comment]
Happening on Trimzr's island as well.  sb1   Coords: -5437 162 -3904.                                                         Take a look on the island, there's ZombiePigmen's, Creepers, Iron Golems and Cow's that do this as well on that island.

**Comment by SwiftSwamp** [comment]
What exactly is the issue, I've went to both Islands and it seems fine (It's possible that it was fixed in another update regarding Mobs)?

**Comment by cyberpwnn** [comment]
Should close this if it is resolved

**Comment by SwiftSwamp** [comment]
Found out the issue, was due to the lag from the server resulting in everything being slowed down. This is semi resolved atm with the lag being sorta resolved.
