### ISSUE TITLE
Drop Enchanting Dupe

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#438]
You can drop enchant items in the EnderChest GUI and it won't eat the book but it'll apply the enchantment, however I tried it with other things such as playervaults and it does not work, seems to only be the EnderChest.

Here's a video submitted by a player if wanted: https://www.youtube.com/watch?v=Q0vnZ6vGTnc

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/9269471adf5b1870efecc7202983301c2c11bb98
