### ISSUE TITLE
Rounding Placeholders

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#439]
As you can see, some placeholders tend to not round. You suggested a solution through Phantom's placeholder system to do so, make it happen.. God. 

![eww](https://cloud.githubusercontent.com/assets/3534551/20244237/a6b69bc4-a947-11e6-9939-311f7f4e7a6a.png)

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/GlacialRealms/issues/461

**Comment by cyberpwnn** [comment]
#461

**Comment by dragonking1121** [comment]
Abuse token 400k
