### ISSUE TITLE
Generic Spawner Resetting

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#441]
Spawners given by certain plugins causes the Spawner to become "Generic" and when placed resets it back to the default Spawner type which is a pig. Giving myself a spawner via Console, In-Game or buying one through /shop seems to work just fine, however if I receive a Spawner from a kit (Give spawner command is done that way) or through the Crates it'll turn Generic when placed, ideas?

**Comment by cyberpwnn** [comment]
Do the plugins allow commands instead?

If they dont, you may be screwed.

**Comment by SwiftSwamp** [comment]
I'm using commands through those plugins to spawn in the spawners, they run them via console just like myself or anything else which is odd, however I read that EssentialsX may be the cause of it as they do some things with Spawners too, time to decompile?

**Comment by cyberpwnn** [comment]
Essentialsx is doing it.

**Comment by SwiftSwamp** [comment]
Sure but any clues on a solution / fix?

**Comment by SwiftSwamp** [comment]
Currently only happens when giving a Spawner through Crates or Essential Kits, both are done via commands. However spawners bought through /shop or /votteshop work just fine, how are you running your commands different to them and is there anyway you intercept them or make your own command to run?

**Comment by cyberpwnn** [comment]
``` java
if(mbc.getMaterial().equals(Material.MOB_SPAWNER))
{
	Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "ss give " + p.getName() + " " + mbc.getData() + " " + sizes.get(k));
}
```

**Comment by cyberpwnn** [comment]
A few things to keep in mind while coming up with a way to fix this
* There is no event that fires off when a plugin gives a player an item (so i cant adapt the item if its a spawner)
* There is no way to check an item in the player's inventory if it was JUST GIVEN or they mined it. So you cant make the plugin give wool with custom id's in it and have me adapt them or players could just drop the item and pick it back up and get a spawner from it
* The only way that i can see going about this is by hacking into each plugin to change how they function

**Comment by SwiftSwamp** [comment]
This was fixed thanks to /phast's wait timer.
