### ISSUE TITLE
Revamp The Color Scheme

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#442]
Currently everything is almost themed around our whole Glacial Color Scheme of Aqua and Dark Blue. Color anything that isn't to match the theme then anything that already is needs to be updated to look right.. LIGHTER COLORS COME FIRST THEN DARKER!!

**Comment by Puretie** [comment]
Added stale tag due to lack of progress following the three day rule. @SwiftSwamp

**Comment by cyberpwnn** [comment]
Changing colors does not take more than half of an hour

**Comment by SwiftSwamp** [comment]
The main ETA was including the Thought Process and constantly reloading / testing to see what looks good as we're changing it, however.. what should the general color scheme be?
Light Aqua, Blue for Glacial/Realms and most related items.
Then follow the News Hubs for Alerts, Warnings, etc?
What about the Header / Footer of longer informational texts? (i.e. The top / bottom of the auto broadcasts instead of it just being a blank space, or having something that looks better with holograms)
Also, suggestions on how to "spice up" the MOTD or do you think it looks fine?

**Comment by cyberpwnn** [comment]
Use the chat to see what it looks like

**Comment by SwiftSwamp** [comment]
Deployed
