### ISSUE TITLE
Give Users a Prestige Title on the 10th Prestige 

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#447]
When players hit Prestige 10, give them the Title "Prestige".

**Comment by Puretie** [comment]
Due to a five minute ETA lasting three days without any further activity, this will be marked as stale for the time being. Furthermore, please provide a valid documentation on "Prestige" so that Cyberpwn and I understand what you are trying to communicate.

**Comment by SwiftSwamp** [comment]
On hold, Josh needs to add this one. He will when he has free time.

**Comment by SwiftSwamp** [comment]
Notes: Basically, add the ability to run commands once a player hits a certain prestige so we can give rewards for "Milestones".

**Comment by SwiftSwamp** [comment]
Just got the plugin, testing out in a few.

**Comment by SwiftSwamp** [comment]
Works, deployed.
