### ISSUE TITLE
Remove the Mine Resetting Global Message

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#448]
Even though no Mines are resetting, it still goes off every 10 minutes counting down "10...5...3...2...1..." suppress it.

**Comment by Puretie** [comment]
Added stale tag due to lack of progress following the three day rule. @SwiftSwamp

**Comment by SwiftSwamp** [comment]
Investigating what's causing this.

**Comment by SwiftSwamp** [comment]
Overlooked a setting, my fault. Resolved.
