### ISSUE TITLE
Reset Whitelist Data

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#455]
Reset all of the servers Whitelist data and deploy a whitelist that only has the admins in it

**Comment by cyberpwnn** [comment]
...

**Comment by Puretie** [comment]
**FIVE MINUTE ETA**

**Comment by SwiftSwamp** [comment]
Manually syncing Data now.

**Comment by SwiftSwamp** [comment]
Finished syncing the Administrative team to the whitelist across the network.
