### ISSUE TITLE
Highlight Dedicated Staff on Forums

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#458]
Setup the following Xenforo Addon to separate staff groups: https://xenforo.com/community/resources/icewind-staff.3629/

**Comment by cyberpwnn** [comment]
YEAH. MAKE ME ON TOP

**Comment by Puretie** [comment]
Added stale tag due to lack of progress following the three day rule. Also adding low priority, though it would be nice to see this implemented soon @SwiftSwamp

**Comment by SwiftSwamp** [comment]
BOOM: http://glacialrealms.com/forums/members/?type=iwd_staff
Also added a Staff Tab since there was room for quick redirects.
