### ISSUE TITLE
Sync Forum Accounts With In-game Accounts

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#459]
Setup MineSync to sync accounts with in-game minecraft accounts.

**Comment by Puretie** [comment]
Added stale tag due to lack of progress following the three day rule. Please add an appropriate priority level to this @swiftswamp

**Comment by SwiftSwamp** [comment]
Currently investigating a safe way to do this without effecting the current 1,500+ registered users and making sure their accounts don't get stolen..

**Comment by SwiftSwamp** [comment]
Will incorporate this on the reset, best time to do it to encourage users to sync their accounts, will also offer a crate key for those that do.

**Comment by SwiftSwamp** [comment]
Needs further testing, it's implemented just not live. Waiting for SexyPex's implementation before allowing users to use this.
