### ISSUE TITLE
Add Saron Developer to forums

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#463]
An actual tag shown below your avatar on posts in the black color { Developer } uses

Set it to "Saron Developer"

Please add
* Xanthous_
* Puretie (if he exists)
* Jess
* Me

**Comment by cyberpwnn** [comment]
Also Remove Testificate from Xanthous and Puretie aswell

**Comment by SwiftSwamp** [comment]
Don't forget to include Minecraft Usernames and what you want the in-game Title to say / be.

**Comment by cyberpwnn** [comment]
IT IS OF THE UP MOST IMPORTANCE THAT THIS HAPPENS NOW

**Comment by CosmicFyre** [comment]
"Saron" and so we learn more details of the project.

**Comment by Formalized** [comment]
My IGN is Formalized, js ^-^

**Comment by xPyroTex** [comment]
IGN is xPyroTex :P

**Comment by cyberpwnn** [comment]
IGN is cyberpwn

derp

**Comment by SwiftSwamp** [comment]
Oops, forgot to close.
