### ISSUE TITLE
Change kit snow

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#464]
Kit snow is a building kit so I think we should be getting a axe and shovel

**Comment by SwiftSwamp** [comment]
I completely agree that you should also receive an Axe and Shovel with the kit, updating kits now.

**Comment by SwiftSwamp** [comment]
Seems like this was only on Skyblock that it wasn't giving you a full tool set, updated and changed Buycraft Description to match accordingly.
