### ISSUE TITLE
Compressed Blocks

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#465]
Compressed blocks is slightly different than just putting 9 emeralds into an emerald block (the multiblock issue #256 is different)

For example, here is a crafting chain

> 9 Emeralds > 1 Emerald block
> 9 Emerald block > 1 Double Emerald Block  (lore: contains 81 emeralds)
> 9 Double Emerald block > 1 Triple Emerald Block  (lore: contains 729 emeralds)
> 9 Triple Emerald block > 1 Quadruple Emerald Block  (lore: contains 6,561 emeralds)

This can then be down crafted from 
> 1 Quadruple to 9 Triple blocks
>  9 Triple blocks to 81 Double blocks 
> 81 Double blocks to 729 Emerald blocks
> 729 Emerald blocks to 6,561 emeralds

These items cannot be sold, or placed they are for chest storage strictly.

All ore blocks can be compressed in this manner.

**Comment by Puretie** [comment]
Added stale tag due to lack of progress following the three day rule. @cyberpwnn

**Comment by cyberpwnn** [comment]
This will cause some issues more than it would help players. Putting this in the backlog. Closing for now.
