### ISSUE TITLE
Staff command packet spam

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#466]
![4eeb8047082c119a6c6d18606e62973d9118b35ab5cbc83673 tfile_urlpv](https://cloud.githubusercontent.com/assets/10619135/20247991/b5a09be2-a9a8-11e6-8ff7-b5687910fcd3.png)

Basically, if 2 or more players use /staff within a 50-100 millisecond window, the LAST person who sent it in that window receives all of the packets.

Suggestion for fix: Add the player uuid to the transmission packets

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule.

**Comment by SwiftSwamp** [comment]
Starting to get really annoying, happening really often now.
