### ISSUE TITLE
Spawners Losing Nest Data

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#471]
I'm not 100% sure if this is related with Nest or issue #441 or if it's happening because of the crashes but randomly at times someones entire spawner farm will be unright clickable to open up the Overclocking GUI, this has happened multiple times and only with spawners that have an overclock then when you go to mine them they come back properly and don't reset. It's more or less annoying because when this happens you have to replace them in order for them to keep spawning again.

**Comment by SwiftSwamp** [comment]
Update: Even replacing them after mining... they're still not spawning and cannot be right clicked.

**Comment by SwiftSwamp** [comment]
Update: Odd, spawning in ig's and placing them I can't even open the upgrade gui.

**Comment by SwiftSwamp** [comment]
Update: Spawning in a Cow and placing it brings it up and if I remine a glitched Cow upgraded spawner and place it, it then starts working. However it seems to be random at this point now..

Notes: Iron Golems are given the upgrade price through the spawner.yml in Technic, rest is through the shop.

**Comment by SwiftSwamp** [comment]
Glitched spawners also do not have the zero velocity, they go flying.

**Comment by SwiftSwamp** [comment]
Update: Even though the spawners are bugged, not spawning and replacing them doesn't fix it, if I don't shift right click onto another spawner it'll go back into my inventory as if it were opening the gui.

**Comment by WolfiezRawr** [comment]
Normal cow spawners don't seem to be working either atm.

**Comment by SwiftSwamp** [comment]
^It's not every single one in the server. It's happening at random.

**Comment by SwiftSwamp** [comment]
Hmm, not sure if this is what happened but I believe if you leave the chunk, let it unload and come back it fixes it.

**Comment by WolfiezRawr** [comment]
Update: Leaving the island and loading back the chunk doesn't seem to work

**Comment by WolfiezRawr** [comment]
Update: I've replaced a whole row with normal cow spawners and they all seem to be working fine

**Comment by SwiftSwamp** [comment]
Not sure what happened, unloading the chunk then reloading it doesn't exactly work.. so I wonder why some spawners randomly got data back again.

**Comment by cyberpwnn** [comment]
Nest data is not capable of saving after the server crashes.
Unless, ehem, sqlite.

**Comment by cyberpwnn** [comment]
Spawners are not loosing nest data. (inventory title length was higher than normal)

https://github.com/cyberpwnn/Technic/commit/4cf033e1dc66f211e320e0c59cefda258b685599

### Technic 3.1 Released
