### ISSUE TITLE
Non-donor mines not resetting at 40%

### ISSUE THREAD

**Issue by Pumbs** [cyberpwnn/GlacialRealms#473]
So basically, I noticed that the donor mines are resetting when it's mined at 40%, I don't know if they're all like that, but Crystal mine is where I mine at, and it isn't resetting even while being under 40%. It's kinda annoying, as you have to wait 15minutes for it to reset, I'd highly appreciate if this gets fixed.

Thank you, best regards- Pumbs.

**Comment by dragonking1121** [comment]
Prison king slow down ur in first place already

**Comment by SwiftSwamp** [comment]
They reset at 25% not 40%.
