### ISSUE TITLE
A few prison bugs / suggestions

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#475]
- Some ladders missing at pvpmine
 - pvpmine percentage is not shown on scoreboard

 - add /popup stfu for the full inventory popup, when mining in pvp its very annoying having it in your face 24/7. most people in pvp dont sell the obby or have autosell.

**Comment by SwiftSwamp** [comment]
Please keep issues separate, 1 issue per issue / suggestion. The PvP Mine isn't meant to recent after a percentage, it resets every 15 minutes.
