### ISSUE TITLE
Missing Ladders at /warp pvp

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#477]
Missing ladders at /warp pvp on Prison, 1070, 98, -2338

**Comment by cyberpwnn** [comment]
This is still happening #485

**Comment by SwiftSwamp** [comment]
Investigating now and bumping up ETA, not entirely sure what's going on. I suspect explosion from custom enchantments are removing them.

**Comment by SwiftSwamp** [comment]
Yes, it was the radius of custom enchantments extending outside of the denied regions. For some reason it was bypassing the usual block-break deny worldguard flags, forced it by using priority's with specifically defining Ladders.

**Comment by GlacialSean** [comment]
Still happening

**Comment by SwiftSwamp** [comment]
I need actual reproduction steps, I've patched this "three" times, without knowing exactly how to reproduce it 10/10 times I can't do anything about it, however you also should include all the information you have when commenting on here, please don't leave anything out.

> It's only happening on the side closest to the entrance, the other side has never lost the ladders.

**Comment by SwiftSwamp** [comment]
Take 3, reopen if it's still an issue after this.
