### ISSUE TITLE
Skywars block lag

### ISSUE THREAD

**Issue by Momedy** [cyberpwnn/GlacialRealms#478]
There's lots of block lag in skywars, ive lost a couple games to do that xD

**Comment by SwiftSwamp** [comment]
I'm not seeing anything wrong, could you give me better detail and or let me know if it's just you or if this is the right server.

**Comment by Momedy** [comment]
Whenever I use blocks to start building out to the middle circle or whatever it is, the blocks that I place sometimes disappear and then reappear, causing me to fall into the void. This has happened on many other server's skywars that I've played on. Also, the last time I played skywars and that happened was last week, I haven't been able to play a game this week yet. You might have already fixed it, though.

**Comment by SwiftSwamp** [comment]
Please test an issue and make sure it's still an issue before reporting, however it sounds like this is on your end and you have bad connect to the servers, I'd adviser running a speed test and traceroutes to the servers to see what it's like. If you need help on doing so, please try using Google first then asking me and I'll be glad to help you :P

**Comment by cyberpwnn** [comment]
This also could be clientside by the way (bad internet)
