### ISSUE TITLE
Cap Max Allowed Enchants

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#479]
This cannot be done via EnchantmentAPI, I've already checked. 
Basically, would like the ability to set the max amount of custom enchantments per item.
i.e. If you have a Diamond Sword with Sharpness 3, Unbreaking 2 and Shock 1, this would only count as 1. 
I think the cap should be defaulted to 3 since we're not including vanilla enchantments + 4 different armor pieces.

**Comment by cyberpwnn** [comment]
Line 4

**Comment by SwiftSwamp** [comment]
Drop Enchanting overrides that, that only applies for the enchantment table and anvils.

**Comment by Puretie** [comment]
Added stale tag due to lack of progress following the three day rule. Whatever's on line 4 needs to be amended to fix the override asap. @cyberpwnn

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/0f6939998bfabb17e569ab50781c66280340e2cd
