### ISSUE TITLE
Lag compensation for ping sensitive engagements. 

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#482]
### Generally
What i mean by this is simply by creating a packet delay between the client and server. Essentially what this does is merges packets together. 

So if you have a fight with this ping difference
* Player A: 12ms (AMAZING)
* Player B: 46ms (Great)
* Player C: 144ms (Ok)

All three of them would see packets in the same order, but at the same time. Essentially **If your ping is below 150 milliseconds, there is no drawback compared to someone with 0 milliseconds**

Almost half of all first person shooter games and rts games use this mechanic, but it does have a few drawbacks (which is why im only proposing it for pvp fights)

### The Drawbacks
* It creates a very very difficult to see echo effect. Basically, players will see you about 150 milliseconds behind you (3 ticks or so), What this means, is if you pop around a corner, the player on the other side will see you 150 milliseconds AFTER the player moving sees you. 

### Packet Witholding
Packets sent to the server (player move and look packets, along with combat packets) are receieved, however when the server tries to send the move packet to other players (so players see you move) the server will instead send it 150 milliseconds after.

But by just delaying packets, you wont get anything to change, still higher ping players will have a faster response time. All you have to do is subtract the ping like so.

```150 - [PING]``` = Packet delay milliseconds.

If the player ping is OVER 150 milliseconds, we cant help the player in any way, so dont withhold the packet, just send it since they are already lagging.

What this ends up doing is the following

1. Player A sends back a keep-alive packet
2. Player B sends back a keep-alive packet
3. Server reads Player A ping after 50 milliseconds
4. Server reads Player B ping after 130 milliseconds

Once the ping has been detected, here is how their fight would happen. Since player b is 80 milliseconds slower than player b, this happens

* Player A packets are not sent to other players until 100 milliseconds pass (150 - 50)
* Player B packets are not sent to other players until 20 milliseconds pass (150 - 130)

##### Player A
* Player A sends a MOVE PACKET
* Server gets the packet after 50 milliseconds
* Server WAITS 100 milliseconds to send the move packet for other players to see

##### Player A
* Player B sends a MOVE PACKET
* Server gets the packet after 130 milliseconds
* Server WAITS 20 milliseconds to send the move packet for other players to see

**PLAYER A AND PLAYER B SEE EACH OTHER MOVE EXACTLY AT THE SAME TIME INSTEAD OF 80 MILLISECONDS APART.**

**Comment by Puretie** [comment]
As much as I despise these kinds of systems in most games, especially the FPS variety (many people have learned how to take advantage of these things in ranged-combat games), I do believe this holds a very high potential to balance out melee-based pvp where literally inches count. Something like this should be, at the very least, drawn up and tested on the development servers.

**Comment by Puretie** [comment]
Adding the stale tag due to lack of progress following the three day rule. I'm also assigning @SwiftSwamp to get the community more involved in discussion on this one, as it is very helpful, but also highly controversial due to the compensation mechanics.

**Comment by cyberpwnn** [comment]
Waiting.
