### ISSUE TITLE
Ladders gone.

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#485]
#477 
Again.

**Comment by cyberpwnn** [comment]
Reopened #477

**Comment by cyberpwnn** [comment]
This is a protocol issue technically

**Comment by SwiftSwamp** [comment]
How would this be a protocol issue? I suspect Custom Enchantments. However it's only happening on one side of the Mine, every other Mine and the other side is entirely fine. I've tried reproducing the bug but I'm unable to. Without knowing how to reproduce it I cannot confirm if it's fixed or not, however I've tried a few more things so keep this issue updated.

**Comment by SwiftSwamp** [comment]
There usually would have been Ladders missing by now, everything seems fine. Closed.
