### ISSUE TITLE
Disconnecting sends info log of currencies saved.

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#487]
This is kind of annoying, here is an example log
```|CurrencyShops > PlayerDataController: {"votes":442}```

**Comment by Puretie** [comment]
Removing the too lazy tag, because it's on a 5 Minute ETA. Please have this done before it goes stale. @cyberpwnn

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/CurrencyShops/commit/86513d31187647084e9d1e1442bebf60bc0d6d9f
