### ISSUE TITLE
Spawners not being recieved from crates

### ISSUE THREAD

**Issue by SamGlacial** [cyberpwnn/GlacialRealms#488]
On factions spawners are not being gained after a crate key has been opened.

**Comment by SamGlacial** [comment]
https://youtu.be/Jtlnp6wqByo

Proof of bug

**Comment by SamGlacial** [comment]
This is across all servers with spawners.

**Comment by SwiftSwamp** [comment]
Investigating now, most likely cost.. certain plugins do not like phast at all. 
Notes: Used Phast to fix the generic spawner resetting bug from kit / crate spawners.

**Comment by SwiftSwamp** [comment]
Fixed, I put a : instead of a ;, I love being tired.
