### ISSUE TITLE
Admin Suffix On Prison (InfernosMC)

### ISSUE THREAD

**Issue by InfernosMC** [cyberpwnn/GlacialRealms#490]
Swift told me to make an issue. On prison I want my admin prefix to be my suffix so I can see my rank on prison.

**Comment by SwiftSwamp** [comment]
Change the chat formatting for Admins to display the suffix where the prefix goes while maintaining the prison rank if wanted.

**Comment by Puretie** [comment]
Bumping the ETA from 5 minutes to 20, as it will take some effort to make the suffix and prefix interchangeable. Regardless, please look into this sometime within the next 24 hours, as it should not take very long to implement. @SwiftSwamp

**Comment by SwiftSwamp** [comment]
There you go Infernos, tested in-game with Infernos.
