### ISSUE TITLE
Factions Itemrename glitch.

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#493]
Combining items via itemrename works as if it were an anvil... and then you get the second item back.

**Comment by cyberpwnn** [comment]
Needs Reproduction steps and a bit more explaining

**Comment by SwiftSwamp** [comment]
Nothing I can do about this, looks like it's already been reported to the author, I bumped it however with more information: https://www.spigotmc.org/threads/namemyitem-1-8-1-10-paid.92940/page-5#post-2024734
