### ISSUE TITLE
Pixelmon Hub Server

### ISSUE THREAD

**Issue by IBGnova** [cyberpwnn/GlacialRealms#496]
(As the title states, we need to make the Pixelmon hub server and setup a voting connection between the two servers!)

**Comment by SwiftSwamp** [comment]
Usually we would keep 1 issue / addition / enhancement per issue but Cross Server Voting for the two Pixelmon Servers is included in the Hub Server.

**Comment by SwiftSwamp** [comment]
Notes: Make sure to look for an old unused owned license key for Nova to remove his monthly bill.

**Comment by SwiftSwamp** [comment]
Finishing #404 before finishing this up.
