### ISSUE TITLE
Mob Spawner Drop Changes

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#497]
* Add the ability to change the drops from mobs when they die
* Add the ability to remove items from a mob, i.e. Zombie Pigmen drop Gold Swords & Bows, this is a waste of space. Would like to remove this.

Leaving open for discussion on what changes people think should be made to drops.

**Comment by kotik1998** [comment]
Swift they only drop sword and Ingots when u kill them (Human Kill)
When u make the farm for pigmen only drop Buggets and Rooten Flesh.

**Comment by cyberpwnn** [comment]
Killing them drops items. 
When they die, they drop nothing.
