### ISSUE TITLE
Christmas Event Suggestions!

### ISSUE THREAD

**Issue by WolfiezRawr** [cyberpwnn/GlacialRealms#498]
So I've been thinking about an interesting event we can do for Christmas and so far I've came up with a treasure "present"  hunt. So basically it can either be a minigame or a mine on Prison full of snow and players have to dig the snow with a shovel that can be named something cool like "The Snow Digger" or something. Players pretty much have to dig up the snow and find the hidden chest and they win something. Not sure what they would win (keys/money?) 

Another event could be another type of treasure hunt but on a basic snowy map. But instead of mining, you're walking around finding these items. You have a book filled with Christmas items to find like snowball, ice, prismarine crystals and we can rename these items "You found me!" so they know they found the right thing. Winners gets a prize :)

**Comment by Puretie** [comment]
Host a treasure hunt with a bingo board style list of 9-12 items.

**Comment by Puretie** [comment]
Marking this as stale as it has surpassed the three day rule without progress. Looks like it could use more community interaction before implementation. @SwiftSwamp

**Comment by SwiftSwamp** [comment]
The forums would probably be a better place for discussion regarding the Holiday Themed event, please make a post with any extra information then post it in this issue so we can close it and reference accordingly.

**Comment by cyberpwnn** [comment]
In which case, you should actually close it.
