### ISSUE TITLE
Login authentication for all staff

### ISSUE THREAD

**Issue by Puretie** [cyberpwnn/GlacialRealms#499]
I'm proposing that Google auth be necessary for all staff for the sake of professionalism and quality control. Google auth is insanely easy to use, and should provide seamless security among all staff, regardless of permissions. #443

**Comment by SwiftSwamp** [comment]
Yeah, I agree with it. However since it was just added, I'm going to manually work with each staff 1 on 1 to help get them setup instead of just forcing them to use it before they can even move.

**Comment by SwiftSwamp** [comment]
Will close this once I've made the post from #501 explaining that we're going to start enforcing this.

**Comment by SwiftSwamp** [comment]
It's been done: http://glacialrealms.com/forums/threads/mildly-enforcing-a-few-things.3759/

**Comment by cyberpwnn** [comment]
No.
