### ISSUE TITLE
An Endless Chest Multiblock Structure

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#500]
### Suggested Names: Tesseract, Dimensional Chest, Rift Chest, E.S.S. (Endless Santa Sack of Shit and tell players it stands for Endless Storage Supply), Vortex Chest, Bottomless, Hungry Hungry Hippo, Infinichest or an Infinium (Marvel Copyright, thanks @Puretie !)

The Dimensional Chest is a Multiblock Structure that provides infinite storage (essentially). Creating this Multiblock Structure is a High Priority for various reasons, one being the fact that it's the ultimate solution to the Hopper Lag (There were more than 70k Hoppers today with just 55 players...) with it being win/win for everyone. 

* Multiple players that are abusing the Hopper System (2-5k+ per Island) said they would rather have this and would replace the majority of their Hoppers if this was added in along with encouraging others to use them.
* Add some sort of "Durability" system where it needs to be fueled (Similar to how you add fuel to a Smeltery), however the fuel shouldn't be too expensive, something reasonable.
* You can add Hoppers anywhere on it much like the Smeltery as well.
* You'll have a GUI like system where it'll separate all items into groups i.e. "You have 495 Diamonds" or "You have 1,234 Blaze Rods", etc... and then someway to easily withdraw everything (Filling Inventory anyways).
* One concern is what happens if someone breaks it, if it has say 10k-15k items.. that's a LOT of entity's just suddenly in the world now. Should we give a warning that if you break the structure, it WILL eat all of your items? (Destroying the storage part, if part of it is destroyed and the storage section still exists, it should still keep track of all of the items in it, it just won't function)
* Needs to have some sort of cost for upgrading it with more storage, something reasonable cheap however, I'd much rather make fuel more expensive if anything
* Should ignore any items that are renamed / lores and pass them through normally instead
* It's EXTREMELY convenient for players and us

Sounds like this is also a job for your new serialization design

**Comment by SwiftSwamp** [comment]
Special thanks to PandaGOD_Senpai for suggesting this Multiblock Structure.

**Comment by CosmicFyre** [comment]
DSU - Deep storage unit. 
https://ftbwiki.org/Deep_Storage_Unit

**Comment by SwiftSwamp** [comment]
The Tekkit Copy was a joke, I'd like to have our own name :P

**Comment by CosmicFyre** [comment]
Void Crate - Stores items in an endless void for future use

**Comment by WolfiezRawr** [comment]
I vote on the name Rift Chest or InfiniChest and I also love this idea as it drastically decreases and improves the lag. This also leaves players with more free space instead of their island being filled with hoppers.

**Comment by Formalized** [comment]
" One concern is what happens if someone breaks it, if it has say 10k-15k items.. that's a LOT of entity's just suddenly in the world now. Should we give a warning that if you break the structure, it WILL eat all of your items? (Destroying the storage part, if part of it is destroyed and the storage section still exists, it should still keep track of all of the items in it, it just won't function)"
If there's more than a full inventory worth then make it eat the items or don't allow breakage of.
" Needs to have some sort of cost for upgrading it with more storage, something reasonable cheap however, I'd much rather make fuel more expensive if anything"
XP shop?


I personally like Infinichest out of all of them.

**Comment by cyberpwnn** [comment]
Using DSU's would be a better method of madness. It offers at least some creativity without just playing the game for them.

**Comment by cyberpwnn** [comment]
> One concern is what happens if someone breaks it, if it has say 10k-15k items.. that's a LOT of entity's just suddenly in the world now. Should we give a warning that if you break the structure, it WILL eat all of your items? (Destroying the storage part, if part of it is destroyed and the storage section still exists, it should still keep track of all of the items in it, it just won't function)

No.

Each DSU is linked to a serialized file. So mining it would have a meta link attached to it. Placing it again would still contain the same items.

**Comment by CosmicPyrex** [comment]
This is still a huge problem for PandaGOD_Senpai, he/she has loads of iron golem spawners and afk's them a lot. He/she also has a huge profit shop for them; the ingots never reach the bottom where the chests are. I'm sure you have more important issues, but just wanted to make sure this was being 'worked on' I guess you could say.

**Comment by SwiftSwamp** [comment]
Marking as On Hold for now, the main purpose behind this was due to the Hopper Lag, however we've resolved that for now and the server can handle tens of thousands of active hoppers. Main thing we're dealing with is Spawners / Entities. This should be added in before the next reset, however that may not be the case.

**Comment by cyberpwnn** [comment]
Issues that are on hold are not active. Reopen when ready.
