### ISSUE TITLE
New Graphics / Artwork

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#503]
Grabbing a better server icon, banner & logo from these guys: http://www.totallydrawn.com/Illustrations.html
If you have better suggestions, let me know.
Dans Description: MAKE SURE YOU TELL THEM "A banner that screams awesomeness and the privilege to play on GR, same for the Server Icon".

**Comment by cyberpwnn** [comment]
Dark, Snowy, Text punches and flashes, and it hits hard and goes fast. like that.

**Comment by SwiftSwamp** [comment]
Guy isn't responding... time to find a new one.

**Comment by Puretie** [comment]
Going to put this on hold while you are searching.

**Comment by cyberpwnn** [comment]
If its on hold, it isnt active. Reopen when ready to work on it.

**Comment by SwiftSwamp** [comment]
This was done.
