### ISSUE TITLE
New Thanksgiving Themed Tags

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#504]
Add the following new Limited Edition Tags: Thanksgiving, Gobble, Turkey, 
Add the following free tags in Crates: Thankful, Turkey, Family, Autumn

Open for discussion, Thanksgiving themed words are bad.

**Comment by WolfiezRawr** [comment]
Limited Edition: Gravy, Cranberry, PumpkinPie, 
Free Tags: Mash Potato, Acorn,

**Comment by cyberpwnn** [comment]
Add "Stufft"

**Comment by CondensateTribe** [comment]
Potato, AllTheStuffs, Travel, Stuft, WithTheFam

**Comment by cyberpwnn** [comment]
> Potato, AllTheStuffs, Travel, Stufed, WithTheFam
Yeah, its fine, just add my tag into your creative list.

**Comment by cyberpwnn** [comment]
---

This is a 

---

Test

**Comment by Puretie** [comment]
Marking this as stale following the three day rule. More discussion or ideas are still welcome!

**Comment by SwiftSwamp** [comment]
Decided on adding the following Limited Edition Titles: Gobble, Turkey, Autumn
Decided on adding the following Free Titles;
  * Prison - Thankful
  * Skyblock North & South - CandyCorn
  * KitPvP - Stufft
  * Factions - Gravy
