### ISSUE TITLE
Spawner Broken Again

### ISSUE THREAD

**Issue by kotik1998** [cyberpwnn/GlacialRealms#505]
https://www.youtube.com/watch?v=-kLmKdHIwdY&feature=youtu.be

RIP creeper spawners :/

**Comment by cyberpwnn** [comment]
Something is resetting their state

**Comment by cyberpwnn** [comment]
Keep up with #508

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/caeb6ece4640e14187ba78271aff4cc036710364
