### ISSUE TITLE
Out of stock on Skyblock change

### ISSUE THREAD

**Issue by WolfiezRawr** [cyberpwnn/GlacialRealms#514]
● So it's been brought to my attention that people are complaining that when their store is out of stock it says **"Your Diamond Block, shop is out of stock"** and people usually spam the sign and it fills up their whole chat saying **"Your Diamond Block, shop is out of stock"**

★ Suggestion!
- Make it say **"Your Diamond Block, shop is out of stock"** only **once** in chat.
- If that person keeps clicking the sign it won't say it anymore.

**Comment by SwiftSwamp** [comment]
You can toggle this by typing /ctoggle.

**Comment by WolfiezRawr** [comment]
That's an unknown command apparently
