### ISSUE TITLE
Make /fix hand available on prison

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#518]
Make fix hand available on prison, as it currently is not.

**Comment by dragonking1121** [comment]
I meant fixhand is not working in combact

**Comment by SwiftSwamp** [comment]
I'm assuming this is a suggestion, fix hand works in combat. From my understanding it's meant to be added in general?

**Comment by dragonking1121** [comment]
I tested on prison while I'm in combat and it dident work

**Comment by dragonking1121** [comment]
I just tested agian with Somone and it's not working in combact

**Comment by SwiftSwamp** [comment]
You can do /fix hand at all but not in combat? What's the message you get when attempting to do so in Combat.

**Comment by dragonking1121** [comment]
When I fix hand in combact it tell me I'm in combact and how much time left I have to wait until I'm out of combact

**Comment by SwiftSwamp** [comment]
Closed, please refer to #544
