### ISSUE TITLE
Get /p h back on prison

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#532]
I just realize that when you want to go to ur own plot or someone else it's not /p h anymore is /ps h
I been hearing a lot of player complaining about it and I want p h back too

**Comment by SwiftSwamp** [comment]
It's been like this for a while ever since the addition of Party, what I could do is remove the p alias, however a lot like the p alias for Parties. It's one or the other, leaving open for discussion.

**Comment by NotMannyyy** [comment]
Please remove the alias, its so annoying and would be easier to do /p h

**Comment by dragonking1121** [comment]
Yea /p h is way better then ps

**Comment by GlacialSean** [comment]
The party's aren't permanent therefor I don't like the party's. 
I'd like to have the /p command back for /plot

**Comment by dragonking1121** [comment]
I think instead doing p for party we can just type party for it

**Comment by dragonking1121** [comment]
Or we can use ps for party and ph for plot

**Comment by Ashleyyx** [comment]
/p should be used for plots. More people are familiar with it and it's overall easier.

**Comment by SwiftSwamp** [comment]
Will be removed as a Party alias and changed to /pc when the network reboots.
