### ISSUE TITLE
Replacement of SilkSpawners

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#533]
As you know, we've been having issues regarding Spawners losing data, becoming generic or just not spawning at all. Since the resets are coming up soon with any server that has Spawners + Technic, I was thinking of adding the following straight into technic.

* Ability to give spawners through a command.
* Ability to mine Spawners with Silk Touch
* When adding this in, be sure to change the Creeper thing in Factions+ accordingly with the explosion dropping and names

**Comment by SwiftSwamp** [comment]
SilkSpawners is just bloat and adds a lot of unnecessary stuff that we don't even use.

**Comment by cyberpwnn** [comment]
Alrighty

**Comment by SwiftSwamp** [comment]
This can actually be closed if you don't want to do it, SilkSpawners will still work for what we need now now that we've resolved all related bugs to monster spawners.
