### ISSUE TITLE
Weird Spawner Issue (Suspected Cause)

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#534]
To keep things organized, I'll explain what happened and what we suspected in order. 

* First chunks not loading suspected to be Technic being the cause so I downgraded it from 3.4 to 3.1 (Primarily due to the fact that any chunks that won't load seem to always have spawners in them (You can still the spawner flame particles))
* This was not the case, same with the mobs floating in the air. However, 3.4 causes Mobs to not stack despite testing it on the dev server with the same configuration / stacking plugin
* I then suspected ViaVersion 1.0.1 (1.11 push), this did not fix it either (At first, it seemed that way), however the mobs floating seemed to have stop.
* However, the remaining issues still exist in any version of Technic 3.1 ~ 3.4 and ViaVersion 0.9.9 ~ 1.0.: Mobs keep randomly quit spawning (Despite proper Nest Data, Probes show fine, can open the OC GUI) and will start spawning again once you replace the spawners down and chunks still randomly stop loading

**Comment by cyberpwnn** [comment]
* The reason you see particles is because the server is online and running well, technic is sending you packets for particles
* Floating mobs in the air i suspect are ghost entities that were sent by the server (highly likely it is via version)

**Comment by SwiftSwamp** [comment]
* The floating mobs part is ViaVersion, we established that.
* The remaining issues are chunks (Happening a lot more than usual..) randomly not loading (Only with spawners in them) and then the whole spawners not spawning mobs until you replace them.

**Comment by cyberpwnn** [comment]
> The remaining issues are chunks (Happening a lot more than usual..) randomly not loading (Only with spawners in them) and then the whole spawners not spawning mobs until you replace them.

Disable Technic and all phantom plugins. See what happens.

**Comment by SwiftSwamp** [comment]
Waiting 24 hours to see if we've resolved this issue, we've both made various changes / updates to the servers regarding any suspected causes for Spawners and Chunk Disappearances.

**Comment by SwiftSwamp** [comment]
So far so good, leaving open for one more night before marking as confirmed resolved.

**Comment by SwiftSwamp** [comment]
Spawner issue is resolved it seems, opening new issues regarding the chunk glitching and crashing.
