### ISSUE TITLE
Ladder missing in warp pvp on prison

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#538]
Warp pvp ladder some are missing

**Comment by SwiftSwamp** [comment]
Please use the search function and reopen an already existing issue next time.
However, without knowing exactly how to recreate this bug, I'm unable to fix it for now.
If someone can figure it out, please reply to this.

**Comment by CosmicFyre** [comment]
We cannot open closed reports [unless we are the creators]

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/GlacialRealms/issues/477
https://github.com/cyberpwnn/GlacialRealms/issues/485

I have reopened #485

**Comment by SwiftSwamp** [comment]
You're still able to comment on them for us to reopen :P 
However, I need a solid way to know how to reproduce this.
I did a few more things to see if that'll fix anything but I need to know how to reproduce the issue in order to know if I've fixed it or not.
