### ISSUE TITLE
Creeper Spawners not working

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#539]
They just won't spawn. Even when overclocked, it will still not work. I don't know how to explain this more, but they just won't spawn.

**Comment by SwiftSwamp** [comment]
Marking as resolved as this seems to fix itself on the last reboot. Please reopen if the issue still persists and we haven't changed any spawn rates. Also next time please search for the already existing issue and ask for it to be reopened.

**Comment by CondensateTribe** [comment]
Creepers have been fixed, now IGs won't spawn.
