### ISSUE TITLE
Spawner rate decreased? 

### ISSUE THREAD

**Issue by CowFTW** [cyberpwnn/GlacialRealms#540]
So on sb i see a lot of spawners are now slower. And what i thought is that Swift or some other admin decreased the spawn rates, but there was no mail sent that the spawn rates have been decreased. So can someone send out a mail if the spawn rates have been decreased or if this is an issue.

Thanks-Cow_FTW

**Comment by SwiftSwamp** [comment]
Marking as resolved as this seems to fix itself on the last reboot. Please reopen if the issue still persists and we haven't changed any spawn rates.
