### ISSUE TITLE
1.7 factions cannot connect

### ISSUE THREAD

**Issue by SamGlacial** [cyberpwnn/GlacialRealms#541]
http://imgur.com/78JAh1I
http://imgur.com/V4wVilU
"hi, when i try to login to factions it says outdated server, im still on 1.8.8 but its meant to be 1.7.10-1.11"

**Comment by GlacialSean** [comment]
Can't connect with 1.10 either

**Comment by cyberpwnn** [comment]
1.7 Cannot connect for sure. Its a 5 year old version, and its extremely difficult to do anything on the code side when we allow things like this.

As for 1.10 it should be open soon (you really could just use 1.8 lol)
