### ISSUE TITLE
Prevent Beacon concentration higher than 16 per chunk

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#542]
Do it

**Comment by Puretie** [comment]
Marking as stale due to lack of progress following the 3-day rule. Welcome back, @cyberpwnn

**Comment by SwiftSwamp** [comment]
What about decreasing the amount of particles per chunk instead for everything in general, is something like that possible?

**Comment by cyberpwnn** [comment]
Not all particles are spawned serverside. Some particles are spawned by the client. The only way to prevent them from spawning client particles is to remove the thing that is making the particles spawn. In this case, the beacon is causing minecraft to spawn its own particles. The server isnt doing that,
