### ISSUE TITLE
Physical Notes

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#543]
Needs to have three basic functions. The ability to withdraw Minecraft Vanilla Experience and Vault Balance.

### Withdraw Information ###
When withdrawing money from your balance into a note, it will label the Money Note as follows (Item is a piece of paper);
Name: &b&lMoney Note &8(&7Right Click&8)
Lore Line 1: &dValue UTF 8 u25b6 &7$AMOUNT
Lore Line 2: &dSigner UTF 8 u25b6 &7PLAYER/Server

Right clicking it of course removes it and adds it back into your balance.

* /withdraw - Help Command
* /withdraw <amount> - Withdraws money from your balance into a Money Note.
* /withdraw give <player> <amount> - Gives a player a Money Note signed by the Server.

### Minecraft Vanilla XP Information ###
When withdrawing experience from your balance into a note, it will label the Experience Bottle as follows (Item is a xp bottle);
Name: &a&lExperience Bottle &8(&7Right Click&8)
Lore Line 1: &dValue UTF 8 u25b6 &7$AMOUNT
Lore Line 2: &dEnchanter UTF 8 u25b6 &7PLAYER/Server

Right clicking it of course removes it and adds it back into your vanilla xp balance.

* /withdrawxp - Help Command
* /withdrawxp <amount> - Withdraws experience from your Minecraft Vanilla XP into a Experience Bottle.
* /withdrawxp give <player> <amount> - Gives a player a Experience Bottle signed by the Server.

Color combinations are open for change.

**Comment by cyberpwnn** [comment]
This is an addition

**Comment by SwiftSwamp** [comment]
Ahh, right. My bad.

**Comment by Puretie** [comment]
Marking as stale due to lack of progress following the 3-day rule. Choppity chop chop!

**Comment by cyberpwnn** [comment]
Make a list of features you want in it. 

More lists, more bullets, less paragraphs, less bullet-paragraphs

**Comment by SwiftSwamp** [comment]
Updated

**Comment by cyberpwnn** [comment]
I still disagree with this. You are using paperspigot.

**Comment by SwiftSwamp** [comment]
On a whole 1 server lol.

**Comment by cyberpwnn** [comment]
Was referring to the dupe.

**Comment by SwiftSwamp** [comment]
Changed priority to low, will just keep using what we're currently using and hope people don't constantly lose too much money / exp from the bugs with the current system.
