### ISSUE TITLE
Combat Tagging Whitelist Enhancement

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#544]
Add support for sub commands with the whitelist for Combat Tagging, I would like to allow users to do /fix hand while in Combat, however I do not want them to do /fix all. There are other commands but this is just an example.

**Comment by Puretie** [comment]
Marking as stale due to lack of progress following the 3-day rule.

**Comment by cyberpwnn** [comment]
```
tag:
  command-whitelist:
  - /fix hand

```

Allows fix hand ONLY, anything else is not with /fix ***

**Comment by Puretie** [comment]
Learn2configure

**Comment by SwiftSwamp** [comment]
Doesn't work lol, must've misread this notification.
