### ISSUE TITLE
Skilling- Butcher

### ISSUE THREAD

**Issue by Fizinq** [cyberpwnn/GlacialRealms#547]
I had about level 35 in the Butcher skill from grinding last night. Got on today and the level/shards got reset, but the looting is still leveled up from the shards that I originally had. Same thing happened with Stealth.
![2016-11-21_15 35 25](https://cloud.githubusercontent.com/assets/23522977/20499831/303d3d52-b001-11e6-8b76-f6e88dc50c0b.png)
![2016-11-21_15 35 20](https://cloud.githubusercontent.com/assets/23522977/20499830/2f0b403c-b001-11e6-83d7-689083d5d3c8.png)
![2016-11-21_16 05 31](https://cloud.githubusercontent.com/assets/23522977/20500710/9635ae34-b004-11e6-9939-57337b09b11a.png)
![2016-11-21_16 05 36](https://cloud.githubusercontent.com/assets/23522977/20500709/96311d7e-b004-11e6-9f34-1de1163a9dc6.png)

**Comment by SwiftSwamp** [comment]
I'm not entirely sure but this could have been before we fixed the saving issue, do you have a more exact ETA of how long ago that it did this, within the first 12 hours of release we had some issues with the data saving correctly how ever we've since fixed that.

**Comment by cyberpwnn** [comment]
We had a beta playthrough of it when you had your issue. This issue is no longer a problem. Harass swift if you want those levels back.
