### ISSUE TITLE
Topblocks NPCs

### ISSUE THREAD

**Issue by Pumbs** [cyberpwnn/GlacialRealms#549]
So I noticed that there's something wrong about the NPCs at spawn, not the Misc NPCs, but where the topblocks players are, I don't know why, but they keep looking at the ground for some reasons, it kinda look off to me, I don't know if it's meant to be like that, but I'd highly appreciate to see them being brought back like they were (Following you).

**Comment by SwiftSwamp** [comment]
Give it time to update for the following part but they're no longer looking into themselves.
