### ISSUE TITLE
Apparent Dupe

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#552]
I know there's a for sure Dupe on Skyblock as I found someone with a full inventory of stacked Zombie Pigman Spawners and more than 1 billion, that's impossible, he also had many other things. 

Apparently there's a bug that's been reported where if you drop items and leave the server at the same time then rejoin they dupe, someone sent code to recreate it: http://pastebin.com/9U2mFLbC

The premise of the client is, it drops the items, kicks you from the game, relog, items are in your inventory and on the ground

A faster version of a glitch that was supposedly fixed years ago

Thanks lapis_block for all of the information.

**Comment by SwiftSwamp** [comment]
https://a.pomf.cat/coiwnz.mp4

**Comment by SwiftSwamp** [comment]
Seems like it was fixed two days ago: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/95436219a588cec7497112c879487ce5d5cec73a

**Comment by SwiftSwamp** [comment]
https://github.com/PaperMC/Paper/issues/492

**Comment by SwiftSwamp** [comment]
Needs confirmation if this is happening on normal Spigot.

**Comment by cyberpwnn** [comment]
I highly doubt it. Its an issue on paperspigot and their own problems.

**Comment by Puretie** [comment]
Paper Spigot has a whole plethora of issues different from Spigot due to changes made. Hence why it's Paper Spigot and not just Spigot.

**Comment by cyberpwnn** [comment]
Im asking on that issue you referenced if its their problem or an actual spigot problem they diddnt cause this time lol.

**Comment by kotik1998** [comment]
How do you run the script?
Client?

**Comment by SwiftSwamp** [comment]
We're not using PaperSpigot remember? We're using Migot.

**Comment by SwiftSwamp** [comment]
Unable to reproduce this dupe on both Migot or Spigot, wondering how the player got the items. Still investigating.

**Comment by SwiftSwamp** [comment]
Not a dupe, figured out that an ex-admin actually abused.
