### ISSUE TITLE
smelting skill glitch

### ISSUE THREAD

**Issue by AtillaTheCreeper** [cyberpwnn/GlacialRealms#553]
I had Iron in a furnace and like i normally do I shift clicked it out only to realize after my inventory was full but to see chat say I leveled up in smelting.  Now  like i normally do I "Abused it" to make sure it wasn't a one time thing.

TO REPLICATE:

Smelt some items.
Make sure inventory is full.
Then shift click the smelted item into your inventory

-IGN AtillaTheCreeper

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/b6e6c264e760ab598d23852ead60749c0966a148

**Comment by cyberpwnn** [comment]
### Icing 1.2 Updated
