### ISSUE TITLE
Kit daily sb1 and 2 

### ISSUE THREAD

**Issue by SamGlacial** [cyberpwnn/GlacialRealms#554]
http://prntscr.com/dagsw7

Don't know if this is a recurring issue for other servers. Probably is.

**Comment by SwiftSwamp** [comment]
Currently disabled a part of Essentials that allows us to give commands through the kits, I'll possibly end up just making a server sign at the crates that you can click every 24 hours instead if this fixes the crash issue.

**Comment by SwiftSwamp** [comment]
This actually should only be happening on Skyblock 1, however it will fix with the reset.
