### ISSUE TITLE
Crates opening time

### ISSUE THREAD

**Issue by iiRedBullPvP** [cyberpwnn/GlacialRealms#555]
Your IGN (if applicable): iiRedBullPvP
Suggestion: Opening crates faster (idk if its possible) but if you could set a command to make a crate give you an item instantly, i think it will help a lot of people who dont play certain subservers and just want to open crates quickly to get titles or something EDIT: thought about the comments below, i agree with it, i think that there should be a command to set a time or when you press escape it just gives you a random item from the crate
Server it would be implemented on: all servers
How it could benefit GlacialRealms: explained above
Extra (optional): nothing to put here

I was told to just post this here :)

**Comment by kotik1998** [comment]
Agree.
Swift make a coommand so if u dont want the spinning but only the reward.

**Comment by SwiftSwamp** [comment]
I've reported the bug RedBull to the author as the option to change the crate opening times to make it quicker isn't working but he's ignoring my comments completely.
