### ISSUE TITLE
Blazes don't stack

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#556]
Since the last update, everything stacks accordingly except for Blazes, this is causing a lot of client and server side lag over the span of a few hours.

**Comment by cyberpwnn** [comment]
Technic does not stack mobs. MobStacker stacks mobs.

**Comment by SwiftSwamp** [comment]
Actually that's odd, Blazes suddenly stack now. Must've been a glitch with pha update, assuming in this case it required a reboot for the update to be flushed out properly.
