### ISSUE TITLE
skullblood's private fault's are bugged

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#559]
When player does /pv 1 or /pv 2 he gets the message: 
An internal error occured while attempting to perfom this command

When he does /pv 3,4 or 5 they work
Due to this he has lost 6-8 maxed pickaxes and alot of other stuff.

**Only on skyblock 1**

**Comment by SwiftSwamp** [comment]
Yes, we've been aware. Nothing we can do regarding this, it will fix on the reboot and this bug has already been patched.
