### ISSUE TITLE
Skill snatching makes you keep your items when killed 

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#560]
https://youtu.be/cTzWcuHxnO8

Also tried if it could be a dupe but that didn't work.

**Comment by SwiftSwamp** [comment]
This is intentionally, however I'll leave this open for discussion.

**Comment by cyberpwnn** [comment]
Snatch items when you kill them. They wont take everything.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/ccbffb94f24b5efcf86ef5182ffc2340f1f5abd8

Kay, broke the art of skill.
