### ISSUE TITLE
News Hub

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#565]
I noticed that if I logged onto an Alt, I wasn't be able to view any new changes and it wouldn't tell me that there was new changes despite the last update being an hour before I logged in, does it only tell people and let them view the changes if they're on when it happens?

**Comment by CosmicFyre** [comment]
Yes, this happens when i log onto my alt, i do not get an update log.

**Comment by SwiftSwamp** [comment]
Resolved in call, this will fix. It works.. just they need to get updated for the previous updates.
