### ISSUE TITLE
Confirmation Commands

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#566]
Adding onto the Item Drop Confirmation, command confirmation. Main purpose is when players accidentally tab up and do /ci, type it in because someone told them to and is being a dick, etc. If you want to hard code it, it's fine. I only see a use for it with /ci, possibly paying (Would get really annoying though) players and well really just /ci. i.e.
/ci
&8&l(&4&l!&8&l) &cPlease type /ci again to clear your inventory!
/ci
CLEARS INVENTORY, POOF

**Comment by cyberpwnn** [comment]
I dont even know how to reply to this..... I guess ill just do it and laugh and cry on my own.

**Comment by Puretie** [comment]
I'm going to take a disagreement stance on this one, and follow in the wise words of Mr. Darwin.

**Comment by cyberpwnn** [comment]
Perhaps a more ..... practical way of doing this is actually explaining how commands work to players. Thats a thought.

**Comment by SwiftSwamp** [comment]
Much bad, closing.
