### ISSUE TITLE
Combat Tagging not working, causes dupe.

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#567]
Not sure why or what's going on but you no longer get Combat Logged when you log out while Combat Tagged and this also causes your Experience to dupe: https://www.youtube.com/watch?v=n2xdFv-fmfs&feature=youtu.be

Yes, both players do not have any permission to keep experience (tried without). 

Just to confirm it was Commune's Combat Tagging, I also tried with and without it enabled. It stopped duping once disabled.

**Comment by NotMannyyy** [comment]
XP stopped duping like said, but logging out in combat allows you to keep your inventory, also it doesn't affect your KDR.

**Comment by cyberpwnn** [comment]
You diddnt explain anything

**Comment by cyberpwnn** [comment]
Generalizations don't help me fix duped

**Comment by SwiftSwamp** [comment]
You login, get into a fight (combat tagging yourself) then when you log during the fight you're not killed and your vanilla minecraft xp drops as if you lost it but you also keep it, duping the xp.

**Comment by cyberpwnn** [comment]
So something is preventing you from dying

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/1e894b11f4955ce1ce2969a0ed720ad82a871211
