### ISSUE TITLE
Crapples to Gapples Issue Found on Factions

### ISSUE THREAD

**Issue by SilverNShinE** [cyberpwnn/GlacialRealms#569]
This is possible the weirdest thing I have ever seen when it comes to glitches. What happens is if you are mining blocks and you have a golden apple on your hotbar, and while mining you quickly switch to the normal golden apple and attempt to eat it, it will then for whatever reason become an untextured god apple. 
BobTheBuilder and iTzChapo discovered this glitch.

**Comment by SwiftSwamp** [comment]
What Enchantments are they mining with, please provide as much detail as possible. Also, were they using a specific mcmmo or Icing skill?

**Comment by SilverNShinE** [comment]
There was no mcmmo or icing involved in the bug, and the enchantments were efficiency 8, fortune 4, unbreaking 4, moss 4, and blast 4.

**Comment by GlacialSean** [comment]
Reason is Blast 2, explained a bit more on this issue, Also sorry for making a new issue about it but i overlooked yours xd

https://github.com/cyberpwnn/GlacialRealms/issues/574

**Comment by cyberpwnn** [comment]
I know the cause. Just don't switch the items like that and it won't happen.

**Comment by GlacialSean** [comment]
But people can switch bad gapples to good apples?

**Comment by cyberpwnn** [comment]
What no. No. Its changing the durability value, not the data value. 

Try using /fix hand while holding it. This will resolve itself.

**Comment by SilverNShinE** [comment]
Cyber, I've just now tested it and the crapples to gapples still works. You even get the buffs from a god apple if you do this glitch.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/f8cdbbac478589ce9b14f39dae6f21416979b78f
