### ISSUE TITLE
New Icing Ability, Miner? Maybe

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#573]
Not sure what skill this would go under but something you could unlock that would auto sort your inventory / chests that you're looking at would be a highly grinded ability. It would sort the items based on the relevance to the item id and then stack any of the same items.

**Comment by cyberpwnn** [comment]
Why? What is the point? Use this https://minecraft.curseforge.com/projects/inventory-tweaks

No grinding needed.

**Comment by cyberpwnn** [comment]
> "If you dont agree with this close it"
K den
