### ISSUE TITLE
Ranks on forums

### ISSUE THREAD

**Issue by SamGlacial** [cyberpwnn/GlacialRealms#576]
First of I want to say my suggestion doesn't include special donor perks. 
So basically I think it would be cool to see people with banners around their names when MineSync is added.

http://prntscr.com/dc0rzh 

Obviously the colors can be changed.

**Comment by cyberpwnn** [comment]
Pretty sure this was already on here, but cant seem to find it.

**Comment by cyberpwnn** [comment]
Yup, found it #459
