### ISSUE TITLE
Prison - higher explosion levels mean lightning triggers less often

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#577]
both picks have maximum lightning [100]
Explosion 450: you can see very little lightning damage but the top is destroyed by explosion damage
![expl2](https://cloud.githubusercontent.com/assets/22468195/20645462/048658c0-b4c4-11e6-94c9-e30d952e0d75.PNG)
Explosion 161: you can see tons of lightning damage with some explosion damage
![expl1](https://cloud.githubusercontent.com/assets/22468195/20645465/21692aa8-b4c4-11e6-97c3-7db16ce30511.PNG)

**Comment by SwiftSwamp** [comment]
That's extremely odd, nothing changes with how often lightning or explosion goes off based on level, are you sure when you tried it it wasn't just a coincidence?

**Comment by CosmicFyre** [comment]
nope, ive noticed it slowly taking longer for me to reach the 40% reset mark, and decided to test my theory.

**Comment by CosmicFyre** [comment]
I have a suspicion as to what it is. I think that because explosion is exploding more blocks there are less blocks for lightning to activate on, making it less efficient the higher your explosion level. so not a bug. however explosion shouldn't decrease your efficiency, considering its expensive and a good enchant were lightning not a thing.

**Comment by Ashleyyx** [comment]
https://m.youtube.com/watch?v=SJHgr8PXtKo
First pick: 550 explo max light
Second pick: 250 explo max light

Judging on the physical lightning going off and such, I don't really think this is true. Seems the same in my opinion.

**Comment by CosmicFyre** [comment]
Could you try one with no explosion and one with 500 explosion?

**Comment by SwiftSwamp** [comment]
Tried again, still the same. I think you just had bad luck once upgrading :P 
Cannot reproduce, not deemed as a bug.
