### ISSUE TITLE
Enchantment Essence

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#58]
ExpBlast - When mining or killing mobs you'll receive more experience (Chance / tired based of course.. and remember we can withdraw exp so make sure people can't just sit their and kill someone with exp to "dupe" it or drop it and pick it up)

**Comment by cyberpwnn** [comment]
Renamed to Essence, if anyone has a problem with it, change it :P

**Comment by cyberpwnn** [comment]
### Ensure you turn off XP Stacking
https://github.com/cyberpwnn/Effex/commit/4dc7f47b613ba79a2f27e8bdc0550da11d121c23

**Comment by SwiftSwamp** [comment]
Does the plugin handle the experience stacking instead then?
