### ISSUE TITLE
Leather Armor

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#582]
Add all leather armor pieces to the shops on prison and kitpvp for a high price. purely a cosmetic item for the stealth ability camouflage

**Comment by SamGlacial** [comment]
This would be nice to see.

**Comment by SwiftSwamp** [comment]
Agreed;
KitPvP: Each piece being $100
Prison: Each piece costing 100 Billion?

**Comment by dragonking1121** [comment]
I think like 75b for prison and 75 for kitpvp

**Comment by SwiftSwamp** [comment]
Adding to Prison for 100 Billion and won't be on KitPvP, for now it won't be added however we will be adding plain diamond weapons / armor along with enchantment books onto Kit.
