### ISSUE TITLE
Prison should have kit potions

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#584]
I think kit potions should be on prison too since there pvp

**Comment by SwiftSwamp** [comment]
Sure.

**Comment by Ashleyyx** [comment]
That's fine, I don't think poison should be in it, however.

**Comment by SwiftSwamp** [comment]
What do you propose should be in it?

**Comment by Ashleyyx** [comment]
Same as kit, just w/o the poison tbh.

**Comment by dragonking1121** [comment]
Yea just don't put poison in it

**Comment by SwiftSwamp** [comment]
Added to Prison without Splash Potion of Poison and a 5 minute cooldown.
