### ISSUE TITLE
Spamming /back in pvp on Prison & SB 

### ISSUE THREAD

**Issue by Ashleyyx** [cyberpwnn/GlacialRealms#586]
/back in Skyblock 1&2 and Prison has no cooldown, and it instantly tp's you. This needs a cooldown and a wait time to tp you because it can be kinda of OP and rather annoying in pvp. 

----
Before this is fixed, please warn players that are doing this, and make sure they know continuing would be a 1 day ban.

**Comment by SamGlacial** [comment]
will do

**Comment by SwiftSwamp** [comment]
Combat Logging was temporarily disabled due to the EXP Dupe with it, however it was fixed last night. I just fell asleep before pushing it out.

**Comment by SwiftSwamp** [comment]
Wait, sorry. I may be misunderstanding the issue, are you talking about using /back to get out of pvp or back into pvp?

**Comment by dragonking1121** [comment]
She meant back in to pvp I was there

**Comment by SwiftSwamp** [comment]
Resolved
