### ISSUE TITLE
Add instant health potions to prison and skyblock

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#587]
We should add instant heals potions to prison and sb because sometime people Want to pvp with pots instead

**Comment by Ashleyyx** [comment]
Agreed, I noticed that people have used pots at times, however it will remain gap pvp

**Comment by dragonking1121** [comment]
I know it saying like when people want to 1v1 sometime they want to use pots instead of gap

**Comment by SwiftSwamp** [comment]
Instant Health 1 or 2 and splash or drinkable.

**Comment by dragonking1121** [comment]
Inst and health 2 splash

**Comment by SwiftSwamp** [comment]
Deployed.
