### ISSUE TITLE
Add unbreaking 1 to /kit pvp on prison

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#588]
I think kit pvp should have unbreaking since it would be better because it's only prot2

**Comment by Ashleyyx** [comment]
I thought that it was added, there should be the ability to buy unbreaking 3 imo

But do you mean unbreaking 1 on all the kits?

**Comment by dragonking1121** [comment]
Not all the kit I meant the non donor kits on prison

**Comment by Ashleyyx** [comment]
Sorry I read this wrong, yeah unbr 1 on it sounds fine.

**Comment by SwiftSwamp** [comment]
Deployed.
