### ISSUE TITLE
Kits from crates

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#590]
instead of getting the full kit instantly, get some sort of voucher that gives you the kit when right clicked

**Comment by cyberpwnn** [comment]
Why?

**Comment by dragonking1121** [comment]
Some people want to sell it or don't want to fill their inv

**Comment by CosmicFyre** [comment]
its extremely annoying to have your inventory suddenly filled with mostly useless gear when opening crates.

**Comment by SwiftSwamp** [comment]
Refer to #635
