### ISSUE TITLE
CurrencyShops Max Value

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#593]
The max value for a price in CurrencyShops is 2.147b, bit hard for OP Servers.

**Comment by cyberpwnn** [comment]
Deflate

**Comment by cyberpwnn** [comment]
Damn liberals.

**Comment by SwiftSwamp** [comment]
HOW IS THIS A SIX HOUR ETA, ISN'T ALL YOU'RE DOING CHANGING IT TO USE BIG INTS?

**Comment by cyberpwnn** [comment]
Learn java or realize that there isnt just one integer variable.

Realize that i would have to change many things into LONGS, and if even one INTEGER is still there (that i miss) it wouldnt work, still causing the cap at 2 bil.

Also realize that data needs to be stored in files and has to actually be read back into the plugin properly, more specifically parsing the massive config and currency data from players WHICH ARE ALREADY INTEGERS which means i need to make a converter or else i would "corrupt" all player data. 

There are a lot of things that you need to consider when just swapping an entire data type from the entire plugin. 

You dont just magically swap your system from 64bit to 32bit and magically expect everything you have on your computer to work do you? Sure your just changing a number, but programs rely on 64 bit.

**Comment by SwiftSwamp** [comment]
I wasn't being serious when I used all capitals. If it's to much work it's fine, it's not necessary, I'll go a different route for the items I'm selling over the max.
