### ISSUE TITLE
Help/Shop npc's don't move at prison

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#596]
https://gyazo.com/9c42d424cfe05ed32fc7e9422c5b61b0

All other npc's look at the closest person and move their head with the direction they go, however these 2 don't.

**Comment by cyberpwnn** [comment]
Interesting. Usually that can happen for no reason, but most of the time its just caused clientside.

**Comment by GlacialSean** [comment]
I've asked others too, happens for them as well. If thats what you ment with clientside :P

**Comment by cyberpwnn** [comment]
You can drag in images like so by the way

![9c42d424cfe05ed32fc7e9422c5b61b0](https://cloud.githubusercontent.com/assets/10619135/20756537/0884d95a-b6e1-11e6-94e5-e3d0a9298e8e.png)

**Comment by cyberpwnn** [comment]
Also, are they all looking in the same direction for each player seeing this?

For example, do you and another person BOTH see the "Help" npc looking at the fence? If so its still hard to tell if it is clientside or not, but it could be serverside in that case.

**Comment by GlacialSean** [comment]
Asked a player and he said they look at the same direction for him. Probably server side.

**Comment by cyberpwnn** [comment]
Well as i mentioned before there is no way to tell. For example, if the server sent a packet that froze the npcs all clients would see the same head look position even though its clientside

However on the other hand it could be server side. 

Are they still functional? Like can you right click them as normal?

**Comment by GlacialSean** [comment]
Still working as normal.

**Comment by cyberpwnn** [comment]
Did they ever look at you? I know other npc's do, but have those ever followed players? If they diddnt it might be a #BooSwift

**Comment by SwiftSwamp** [comment]
This isn't really a bug and there's nothing I can really do about it, however it's more than likely resolved in a newer version of Citizens for 1.11.
