### ISSUE TITLE
NPC's at Factions are under the ground

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#597]
https://gyazo.com/104e5103c9d3a4062fbae6bd4dfe4673
https://gyazo.com/656ad8a96d4ad375e2943ed222f6ffc3
https://gyazo.com/d0033a8104f0d736f48412f943032757

**Comment by cyberpwnn** [comment]
Please post images in github. You can literally drag the images into your text box like so 

![g1gc](https://cloud.githubusercontent.com/assets/10619135/20756422/a0ac2158-b6e0-11e6-92d5-619e127558b7.PNG)

**Comment by cyberpwnn** [comment]
This issue is common to happen clientside also.

**Comment by GlacialSean** [comment]
Didn't know, but ok.

**Comment by SwiftSwamp** [comment]
Resolved, reset the npcs *again*.
