### ISSUE TITLE
Cannot teleport you to :-> pvp-block (x)

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#598]
https://www.youtube.com/watch?v=e5bDgIEIuLI

**Comment by cyberpwnn** [comment]
Interesting. It appears that that region is denying ender teleports. However default minecraft will actually cancel your movements as teleports if you are breaking blocks too fast and moving into them at the same time. (this can happen in vanilla minecraft). This should fix within the next few days. Thanks!

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/e3b823363a1ae10915406d1f8e3557ef3fabb1d6

### This will be pushed to the servers later today
