### ISSUE TITLE
"You have promoted.... to moderator (in factions)" but I didn't.

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#599]
I'm not the owner of this faction, I'm just a moderator. However it said this. I think it should be changed to (owner/person who promoted someone) .... to (x)
![moderator fac](https://cloud.githubusercontent.com/assets/22965124/20771929/d2a3b7e6-b74b-11e6-820a-1026a5c493cd.jpg)

**Comment by SwiftSwamp** [comment]
This isn't exactly easily changeable, not sure why it does that but the same message that's sent to the user when they promote someone is also sent to everyone else in the Faction. Nothing I can do about this.
