### ISSUE TITLE
New Skyblock Challenges!

### ISSUE THREAD

**Issue by WolfiezRawr** [cyberpwnn/GlacialRealms#601]
**Nether realm challenges** (Not sure what the rewards could be upon completion)
● "Crybaby" - Kill a ghast and collect it's tear (inventory challenge)
● "On Fire!" - Collect 64 blocks of magma (inventory challenge)
● "#NetherMaster" - Collect a ghast tear, blaze rod, golden nugget, bone, magma cream and ender pearl (inventory challenge)
● "Time to Discover!" - Find a Nether Fortress (island challenge?)

**Comment by SwiftSwamp** [comment]
Thanks for the suggestions for the challenges, however as we do not have the Nether we won't be able to add these. Please reopen this issue or make a new Issue if / when we do.
