### ISSUE TITLE
AntiCheat

### ISSUE THREAD

**Issue by SamGlacial** [cyberpwnn/GlacialRealms#610]
http://prntscr.com/de7vpt they said they could see the anti-cheat. If this isn't a bug I would like to suggest that only staff can see so hackusation is kept low. Also it kicks people that aren't hacking.

http://prntscr.com/de7x41

**Comment by SamGlacial** [comment]
http://prntscr.com/de82mx more showing

**Comment by cyberpwnn** [comment]
### Solution 
* Dont kick for hacks (only prevent)
* Dont handle combat logging (Commune handles it)
* Dont show hack messages to anyone (Staff doesn't need to know about it)

**Comment by SwiftSwamp** [comment]
It should no longer kick, ban or notify anyone when someone is using hacks. It'll simply prevent them.
