### ISSUE TITLE
Essence Custom Enchantment On Factions

### ISSUE THREAD

**Issue by Assurinq** [cyberpwnn/GlacialRealms#613]
Essence is an Enchantment where it gives you additional exp when you kill a mob but it currently gives the same amount as a normal sword.

**Comment by cyberpwnn** [comment]
The amount per orb is the same, but it gives you xp right to your xp bar. Try it. Try to kill a mob without picking up any xp, you will notice your xp bar go up

``` java
new Transaction(new ExperienceCurrency()).to(p).amount(1 + 18 * Math.random()).noDiff().commit();
```

This means you could get an extra 1-18 xp per kill/ore mined depending on the item tool.
