### ISSUE TITLE
"I'm sorry, but you do not have permission to..." with every /p command on Creative

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#615]
With every /p command, you get a message that you don't have perms to do that command. The command still works though.
Also tested this on prison but it didn't happen there.

![5291697dda5cc65d022e959304b0c2c7](https://cloud.githubusercontent.com/assets/10619135/20845077/37c77360-b891-11e6-9290-b55ea5559ba9.png)

**Comment by SwiftSwamp** [comment]
Doesn't happen on Prison because Prison doesn't have VoxelSniper, we're using something to still allow the p alias on Creative, however it tends to also try the VoxelSniper command too.

**Comment by SwiftSwamp** [comment]
Without removing the command in VoxelSniper (or removing Voxel), doesn't seem like I can fix this unless cyber wants to make something.
