### ISSUE TITLE
Xmas Titles Suggestion!

### ISSUE THREAD

**Issue by WolfiezRawr** [cyberpwnn/GlacialRealms#617]
**Limited Edition/Crates Xmas Titles** 
●Jolly
●Grinch
●Elf
●Mistletoe
●Snowy
●Icicle
●Avalanche
●Snowman
●Frosty
●Santa
●Hot Chocolate

**Comment by GlacialSean** [comment]
Rudolph
RedNose
Reindeer 
xd
Christmas or Xmas
Noel
Icy
