### ISSUE TITLE
Mobs freezing on Skyblock

### ISSUE THREAD

**Issue by WolfiezRawr** [cyberpwnn/GlacialRealms#618]
[<a href="https://gyazo.com/1e5fa3266151534b6337fde472cbd795"><img src="https://i.gyazo.com/1e5fa3266151534b6337fde472cbd795.png" alt="https://gyazo.com/1e5fa3266151534b6337fde472cbd795" width="1362"/></a>](url)
[<a href="https://gyazo.com/67f2035e2acff312f7c08eb70d3e876c"><img src="https://i.gyazo.com/67f2035e2acff312f7c08eb70d3e876c.png" alt="https://gyazo.com/67f2035e2acff312f7c08eb70d3e876c" width="1366"/></a>](url)

**Comment by SwiftSwamp** [comment]
Not a bug, was testing something.
