### ISSUE TITLE
/skills Stealth Snatching 

### ISSUE THREAD

**Issue by CombatWombat010** [cyberpwnn/GlacialRealms#619]
If you have unlocked the Snatching ability for Stealth, you are able to pickup items on other players islands on skyblock.

**Comment by cyberpwnn** [comment]
Initially this was intended. But i guess some how it isnt anymore. #BooSwift

**Comment by SwiftSwamp** [comment]
Didn't you revert this already?

**Comment by cyberpwnn** [comment]
I diddnt revert anything. There is nothing to revert. It was initially created this way. Thats why im not hooking into skyblock in icing (or using phantom prot)

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/e518f98baeb3e42579cc35dea07f4511786341ae
