### ISSUE TITLE
Enchantment books losing their enchantment 

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#620]
i used 1 of 4 enchanted books to enchant the shown pick, the remaining 3 lost their enchant. i had used unbreaking 3 and the rest were eff. 5, unbrk. 3 and fort. 3.

![image](https://cloud.githubusercontent.com/assets/22468195/20859920/14a007da-b9d1-11e6-9b61-660a0a97ab9a.png)

**Comment by SwiftSwamp** [comment]
How did you receive the books and where all four books enchanted books and not just normal books with enchantments? Did you also rapid click them and did it say anything in chat when you went to enchant them? My theory is that the custom enchantment limit is getting affected by this even though it's meant to only limit the amount of custom enchantments per item.

**Comment by CosmicFyre** [comment]
the books were bought from /xpshop

**Comment by SwiftSwamp** [comment]
Is this issue still happening since the update with Effex? The update was for an unrelated reason but I wonder if the same issue was the cause.

**Comment by SwiftSwamp** [comment]
Please refer to #647 for further progression, the issues are related.
