### ISSUE TITLE
CurrencyShops Logger

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#621]
A flat file logging system would be great, a global and per person logger would be nice to have per server for currencyshops and then a global per currency logger too maybe ?

**Comment by SwiftSwamp** [comment]
Thought of a better way to do this and is easier on all of us which also allows other Admins to help resolve issues. 
Save the transactions in the database (With a purge data older than such and such of course) and save it like so: What they bought, how much it was bought  for, the before / after?, timestamp balances and what server it was on. The logger will be accessible global so we don't have to go to each server for it.. then when you type say /cs log <currency> <player> {server} will pull up a gui you can click through to see what they bought, when, how much, what server, etc...

**Comment by cyberpwnn** [comment]
> /cs logger dump - Will dump all the logs in a readable flatfile

Isnt it already in a flatfile? How am i supposed to store it?

**Comment by SwiftSwamp** [comment]
There's currently no logging system in place, if you're referring to the currencies stored that's done via MySQL? 

Regarding the per server logging reference, sure that works.

**Comment by cyberpwnn** [comment]
I was pointing out that /cs dump is pointless as it is logged in a flatfile already, dumping what data? 

Also, yes it will be per server. No need to transfer a load of data across servers when the player could just connect to it.
