### ISSUE TITLE
Certain Commands Won't Work With CurrencyShops

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#625]
For some reason certain commands will not work with CurrencyShops, I tried them in-game / console and they work just fine, however it says unknown command when CurrencyShops tries them. It seems so far to only be sync and x createboost, etc... they work fine in console / buycraft but not with CurrencyShops, rest also works. Refer to #53 for the config I'm testing with.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/CurrencyShops/commit/52085318425c8c3a5d7cd6f28570eafda55d257a
https://github.com/cyberpwnn/Commune/commit/5779c54e65c0f2d2697c50038407a5d0d2e6ee95
