### ISSUE TITLE
CurrencyShops Global Currency Not Syncing

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#626]
Same problem as previously, Global Currency will not sync.
If you go on Server A and receive 10 Credits then go to Server B, you will then have 0 Credits. If you go back to Server A you will also now have 0 Credits (Your results may vary as the times it syncs vary's, you could back to Server A and still have 10 on their and vice versa).
However if you go from Server A to a Hub then to Server B it'll sync properly (Assuming this is because of straight connections). 

What about doing what you did for Titles and wait a minute before loading / allowing the use of any currency?

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/CurrencyShops/commit/b97c9b4b6f599f98009ac313a6014327a3f45c7b
