### ISSUE TITLE
Negative Boost gives Insane XP

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#627]
Video says it all, some how you can get Negative Boost and it gives you insane amounts of xp. 

[xp boost.zip](https://github.com/cyberpwnn/GlacialRealms/files/629441/xp.boost.zip)

**Comment by CosmicFyre** [comment]
More info, this was me going from about 100% discred to 700%, sorry for low quality, but its good enough to know whats going on.
https://www.youtube.com/watch?v=xkY5Uts87vk&feature=youtu.be

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/45c6a73859eff298ed3350d2968afef92e8d5176
