### ISSUE TITLE
Add a "Welcome New Player" Plugin

### ISSUE THREAD

**Issue by WolfiezRawr** [cyberpwnn/GlacialRealms#632]
Whenever a new person joins a server we should have the chat say something like "WolfiezRawr has joined the server for the first time!" So that way we know who the new players are.

**Comment by dragonking1121** [comment]
That will be annoying ._.

**Comment by WolfiezRawr** [comment]
Lol how? It'll let us know when someone new has joined the server which is always nice to see 💯

**Comment by SwiftSwamp** [comment]
Sure, sounds good. It won't be annoying, it's only welcoming the player the first time they join.

**Comment by SwiftSwamp** [comment]
New players are now welcomed upon their first login along with what unique they are. Acts as a double win, everyone can welcome the new guys on top of us seeing how many new players there's been.
