### ISSUE TITLE
Redstone Issues (Skyblock)

### ISSUE THREAD

**Issue by Steave0982** [cyberpwnn/GlacialRealms#637]
For some reason, when ever a piston is used to push cobble in a gen, It makes everyone near it lag.

I changed our repeaters to 2 ticks and it still lags

**Comment by SwiftSwamp** [comment]
Could you give me the coordinates of your Island please, there's more than likely something else going on as a Piston pushing Cobblestone shouldn't lag anyone.

**Comment by SwiftSwamp** [comment]
Assuming this is client side as there has been no redstone issues since the post of this issue up until now. If you're still having issues please reopen this issue with the coordinates to your contraption along with your username.
