### ISSUE TITLE
SkillBooster (Bought) Barrely working (Cooldown Too fast)

### ISSUE THREAD

**Issue by xMCxSkillsx** [cyberpwnn/GlacialRealms#638]
Your IGN (only if applicable): xMCxSkillsx
 Bug: I think the cooldown is too fast for skill booster that have been bought, i think there shouldnt be a cooldown at bought skill boosters.
 Server: All
 Proof (if needed): https://youtu.be/in5s8QSBHAA
 Extra (optional): -

**Comment by SwiftSwamp** [comment]
I'm sorry but I'm not exactly sure what you're referring to, I'm not seeing anything wrong with that video.

**Comment by cyberpwnn** [comment]
Your discred increased past 100%, meaning you are being discredited 100% of all earned xp. Wait for it to go down.
