### ISSUE TITLE
Unknown SB dupe

### ISSUE THREAD

**Issue by Ashleyyx** [cyberpwnn/GlacialRealms#639]
If you go on SB and look at /baltop, you'll see:
https://gyazo.com/6203cd5ddd6b73516be5da4cc28c6bd0
https://gyazo.com/5e0381dcfe13a69948c919d1fcda43d0
I went on and looked at their islands with Sean, and in a chest in their house we found ~5 stacks of hoppers. In xxIceGoBoomxx's ender I found a stack of ender spawners, and in his inventory there was a stack of vote keys and 20 50million GlacialNotes. The island belongs to M_Rick77.

They were not on, so I left it all there to give them a chance to explain the dupe or else they'll be banned.

**Comment by Ashleyyx** [comment]
Learned how to do it, please msg me.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/d16943742487b04053f04a3189de8efd0644b507
