### ISSUE TITLE
Typo in EnchantApi Book

### ISSUE THREAD

**Issue by WolfiezRawr** [cyberpwnn/GlacialRealms#640]
Typo on the 26th page in the word "Travles" 
![69a54d898b2abfb536850c3d1235b831](https://cloud.githubusercontent.com/assets/10619135/21094683/1164591c-c026-11e6-875b-063105859308.png)

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/939e2b2861be317b569d589229fcfda2eb0a9dc5
