### ISSUE TITLE
No Pvp in section of pvp arena

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#641]
area above redstone has no pvp, temporary fix was filling the area with barriers
![image](https://cloud.githubusercontent.com/assets/22468195/20919114/169ede78-bbff-11e6-868c-9625aede50fc.png)

**Comment by SwiftSwamp** [comment]
Pleas provide more information such as what server this is on and the coordinates.

**Comment by SwiftSwamp** [comment]
Fixed and fixed the top of it.
