### ISSUE TITLE
Lost my credits

### ISSUE THREAD

**Issue by PixelCoded** [cyberpwnn/GlacialRealms#642]
Your IGN (only if applicable): PixelCode
Bug: So, yesterday, I went in hub1, I got my credits, then I played on the skyblock, then I disconnected because I had to go to sleep. This morning, I came on the server and I had no credits.. I did not use them/give them..

Sometime this bug happen too with the /votes. Most of the time it happen when I relog, but this time it happen with my /credits

Can i get my 50 credits back pliz ? :(

**If you want me to provide my logs, PM me on the FORUM**

**Comment by cyberpwnn** [comment]
This is an ongoing issue, dont worry, you wont be forgotten. We're working on a new data persistence system.

**Comment by cyberpwnn** [comment]
For the meantime refer to #661
