### ISSUE TITLE
[Skyblock] Going to island 

### ISSUE THREAD

**Issue by SamGlacial** [cyberpwnn/GlacialRealms#643]
Missing signs at....... 

It just says it whenever I warp there just my island (Have relogged)

https://youtu.be/Wkt8YzvTMZY

**Comment by SwiftSwamp** [comment]
Hmm, I was unaware that others were able to view this. My guess is that it's because of signs or ChestShop signs that were worldedited out or removed with an Island Reset. Have you recently reset your Island?

**Comment by SamGlacial** [comment]
No I haven't reset my island. We haven't really used chest shops either.

**Comment by SamGlacial** [comment]
This was resolved with Jayzunn and Swift on skype I think.

**Comment by SamGlacial** [comment]
This was resolved
