### ISSUE TITLE
Max Enchantment Upgrading Issue

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#644]
Similar issue to what we had before, if you have the max amount of enchantments on something and you try to upgrade an enchant it simply just won't work.

Reproduction: Enchant something with 8 enchantments with some not having the max level, try to upgrade them to a higher level and it won't enchant.

**Comment by cyberpwnn** [comment]
This wasnt supposed to work anyways.

**Comment by SwiftSwamp** [comment]
What do you mean by that, upgrading enchantments with drop enchanting was intended?

**Comment by cyberpwnn** [comment]
So you want them to upgrade?

**Comment by cyberpwnn** [comment]
#672
