### ISSUE TITLE
Enderpearl out of Skyblock PVP 

### ISSUE THREAD

**Issue by CombatWombat010** [cyberpwnn/GlacialRealms#645]
In /warp pvp on skyblock, you can enderpearl back into the safezone on skyblock during combat (or at all). Easy way for people to get out of dying and get out of combat mid fight.

**Comment by SwiftSwamp** [comment]
Seems that a way better for limitations on Enderpearls and or other things of the sort is to set what regions you cannot use it in instead of zones via Factions so it's useful among the servers, however it's not really a priority.

**Comment by SwiftSwamp** [comment]
My bad, this is actually already possible.

**Comment by SwiftSwamp** [comment]
Fixed.
