### ISSUE TITLE
XP Shop Blank enchants

### ISSUE THREAD

**Issue by CombatWombat010** [cyberpwnn/GlacialRealms#647]
When you buy multiple enchants from /xpshop, after you use the first enchant, the rest turn into blank books and don't work. If I buy four p4 books, and put 1 p4 book on my Helmet, the other 3 P4 books turn blank the second I use the 1st enchant and they become un-useable.

**Comment by SwiftSwamp** [comment]
This is a bug with Drop Enchanting, confirmed.

**Comment by SwiftSwamp** [comment]
I may know a "hotfix" for this.. testing

**Comment by SwiftSwamp** [comment]
What I've learned:

* Grab some normal enchantment books (Ones with random enchants, that title the book with a blue name)
* Grab a few plain Enchanted Books and use /enchantapi add Essence 3 (The name of these should be blue)
* Go to drop enchant them on something, all of your other enchantment books will become plain enchantment books causing you to lose every enchant in your inventory.

**Comment by cyberpwnn** [comment]
Inventory Thrashing

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/4d42510df41bea68011a0ce2f3b15ac2c14d18b6
