### ISSUE TITLE
Votepoints (/votes) reset on KitPvP, Skyblock, Factions and Prison

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#648]
On all these servers votepoints resetted, but not for everyone though.

**Comment by SwiftSwamp** [comment]
Can confirm this is randomly happening with Credits, Vote Points, etc... (any hard currency stored via MySQL). However Dan is currently working on a new data system.

**Comment by cyberpwnn** [comment]
Refer to #661
