### ISSUE TITLE
Armour Durability Can be damaged in Factions Spawn.

### ISSUE THREAD

**Issue by SilverNShinE** [cyberpwnn/GlacialRealms#656]
A player with maxed out unarmed skill showed me that you can damage armour in the factions spawn. He tested it on me and he was not able to do damage to me, but was able to wear down the durability of the armour that I was wearing while we were in spawn.

**Comment by SwiftSwamp** [comment]
Needs more information on how to reproduce.
i.e. Does it happen even when you punch him with fists, is it an Icing Ability, is it a specific enchantment causing it, does it happen with plain armor, what enchants did his armor have, etc.

**Comment by SilverNShinE** [comment]
It is an (from what I've seen) an icing issue. The person had very high unarmed skill and the armour that was used was Glacial Kit. I tried recreating it without having the unarmed skill and nothing happened. From what I know it works on all armour.

**Comment by cyberpwnn** [comment]
Confirmed

**Comment by SwiftSwamp** [comment]
Putting this as a personal note for when this is fixed, this is also the cause of players getting put into Combat Tag while in safe zones or areas you can't harm the other player (Same Territory land, spawn, etc)

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/ff5c460e1af5a84dd19b1fe76d4ad344d0e767d7
