### ISSUE TITLE
CurrencyShop Enhancements

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#657]
* Ability to check the balance of someones currency
* Ability to take away the balance of someones currency

**Comment by cyberpwnn** [comment]
* ```/<currency> give <player> <amt>``` **Give money**
* ```/<currency> take <player> <amt>``` **Remove money**
* ```/<currency> pay <player> <amt>```  **Give your money to someone else**
* ```/<currency> get <player>```               **Get balance**
