### ISSUE TITLE
Infinite Currency Fix Bug

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#658]
After the fix for the negative infinite currency bug, when someone goes to send Credits as normal or a currency, it'll send them but say you have no permission. However if you don't have the ability to send them (i.e. it's disabled), it won't send them. 

http://i.imgur.com/eqdZkcX.png

**Comment by cyberpwnn** [comment]
Try re-explaining. I have no idea what the problem is.

**Comment by SwiftSwamp** [comment]
Now anytime you do a command such as /<currency> give, take, etc... even if you have permission and it succeeds, it'll still say you do not have permission since you pushed that infinite currency patch.
