### ISSUE TITLE
Add unbreaking 5 to exp shop

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#659]
I think we should add unbreaking 5 to exp shop since no one know how u get them

**Comment by SamGlacial** [comment]
and sharpness 5

**Comment by SwiftSwamp** [comment]
What about adding it to Crates instead?

**Comment by dragonking1121** [comment]
I think we should add sharp 5 to crate not unbreaking 3 because people can damage unbreaking 3 armor easily

**Comment by SwiftSwamp** [comment]
The suggested Enchantment in this thread was Unbreaking 5, not 3 :p

**Comment by dragonking1121** [comment]
Then no we should put it in the enchantshop but cost more exp

**Comment by SwiftSwamp** [comment]
Closing as Crates / Shops are being revamped at the moment. Will refer back to this when I get to this part.
