### ISSUE TITLE
/xpshop gives enchanted book rather than book with enchants

### ISSUE THREAD

**Issue by xadistic** [cyberpwnn/GlacialRealms#660]
Spent 12k xp to buy 3 fortune 3 books and only got 1 fortune 3 and the rest are just enchanted books

![](http://i.imgur.com/jq35YQd.png)

![](http://i.imgur.com/gzseiFs.png)

**Comment by dragonking1121** [comment]
This happen when u have one or more enchant book I. Ur inv when u use it

**Comment by cyberpwnn** [comment]
#647
