### ISSUE TITLE
Over Spawning Spawners

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#665]
We spoke about this in the call and you explained what was happening but like I explained, it *shouldn't* be like that. 

* 3 150% Overclocked Iron Golems are spawning 10 - 20 Iron Golems per second.
* When you're out of the activation range for the spawners they'll still spawn but only like normal (As if they were 3x 150% OC IG's)

While I understand how you have it setup, they'll randomly start doing this and it becomes a hassle, however it's only happened at this one specifics Island, no one else has reported it happening (random when it does) and when it does happen, even if they break the spawners they won't quit respawning until a server reboot.

**Comment by cyberpwnn** [comment]
Theoretically it should fix. Technically the only possible way for this to happen is if nest has two references of the same spawner in the same block location. Try using //hrb wipe with the seelction then re-upgrading them. (you will need the player to place them)

**Comment by SwiftSwamp** [comment]
Did not work, they're still spawning.

**Comment by SwiftSwamp** [comment]
Update: When probing there's no data left but they're still spawning.

**Comment by SwiftSwamp** [comment]
Coordinates of where it's happening in the ASkyBlock World: -3565 177 1198
