### ISSUE TITLE
Vacuum hoppers not sucking up items

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#670]
Vacuum hoppers won't work. When you create it, like in the testing stages of the item, it won't suck in the items from the 4x4 radius like its supposed to be like.

**Comment by SwiftSwamp** [comment]
Confirmed, not exactly sure why it's happening.

**Comment by cyberpwnn** [comment]
If its not sucking up any items at all AND there is inventory space to add ANY item, try re-placing the block.

If it is sucking up some items, but the radius is off, i know why. Let me know the issue.

**Comment by SwiftSwamp** [comment]
Yeah, I made fresh Vacuum Hoppers, placed a crap ton, etc... just won't suck up anything.
What's the issue?

**Comment by cyberpwnn** [comment]
Most likley the chunk was loaded and unloaded then loaded again too quickly. There isnt an easy way to fix it. However this can easily be fixed ingame by either moving out of the chunk so it unloads for some time or by breaking and placing it. 

For the time being, this is a root issue with the NEST api, i will close this issue for now, but i will reference this issue when i redesign the nest system.

**Comment by SwiftSwamp** [comment]
It's happening to pretty much every Vacuum Hopper for future reference at the moment and ahh okay, I thought the NEST system was redesigned a few weeks ago.
