### ISSUE TITLE
Discred Caps Too Quick

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#671]
After testing it, on the average task Discred caps at 100% in less than ~30 seconds.
I believe it should take longer to cap or at least those that purchase Boosters... should be a while before it caps as it's essentially wasting them.

**Comment by cyberpwnn** [comment]
Im assuming your referring to mob farming. Im fine with removing it. However im keeping the discred for blocks as you can literally dupe xp with no effort. At least mob spawners have some effort.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/d18692952e67906327db24d53a552bda74fe0eb1

**Comment by SwiftSwamp** [comment]
Assuming you were going to wait for a response :P 
I like the discred effect on everything, it just seemed way to quick with Mobs.
