### ISSUE TITLE
Excavation Ability Bug 

### ISSUE THREAD

**Issue by Assurinq** [cyberpwnn/GlacialRealms#674]
The 'Nuker' under the excavation ability section is supposed to give you haste only when you're mining or breaking blocks but currently it gives you haste even when you hit something so I'm guessing this is a bug?
 https://gyazo.com/7b9f2efa33d02de2bd84ac90c6a92f7f https://gyazo.com/389b1d297592ed0fc3ffc51a31a3d42a

**Comment by cyberpwnn** [comment]
No, it's a feature.

**Comment by Assurinq** [comment]
Then you gotta change the description, its pretty misleading.

**Comment by cyberpwnn** [comment]
You mine faster. What does having it add haste before you actually mine have to do with the actual effect of the skill?

**Comment by Assurinq** [comment]
Yes you mine faster but are you supposed to receive the effect even when you're pvping?

**Comment by cyberpwnn** [comment]
You do realize that effect does nothing in combat right? Just because your hand animates faster doesnt mean you can hit faster.

You can still only hit an entity 2 times a second

**Comment by dragonking1121** [comment]
It true what cyberpawn said I have haste 4 and it doesn't hit faster it only allow me to hit 2 time per stack anything over it won't have any damage

**Comment by cyberpwnn** [comment]
Not a bug
