### ISSUE TITLE
Stacking Issue

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#675]
If I set MergedMob to only stack spawner mobs, nothing get's stacked as for some reason mobs from spawners are not considered spawner mobs (Technic?), this causes problems as mobs from Eggs get stacked which renders Creeper Eggs useless.

**Comment by cyberpwnn** [comment]
Technic doesnt spawn spawner mobs, it spawns mobs near spawners. There is a difference.

**Comment by SwiftSwamp** [comment]
Trying something else with using a different plugin that allows more fine tuning of what we can and cannot stack~

**Comment by SwiftSwamp** [comment]
Resolved with the new Mob Stacking plugin.
