### ISSUE TITLE
Placing Sticky Pistons on other islands

### ISSUE THREAD

**Issue by CombatWombat010** [cyberpwnn/GlacialRealms#679]
You are able to place sticky pistons on other people's islands, but not break them after. Sticky pistons seem to be the only block this works with.

**Comment by SwiftSwamp** [comment]
This is because of FastAsyncRedstone, disabling it for now until we can update a few other used plugins related to the plugin.

**Comment by SwiftSwamp** [comment]
Refer to the following issue for updates regarding this: https://github.com/boy0001/FastAsyncRedstone/issues/11
