### ISSUE TITLE
Telling you who owns a spawner bug

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#681]
The first spawner I tried to break / punched told me who owned but after that any spawner just told me I do not own the spawner and wouldn't tell me who owned a spawner.

**Comment by SamGlacial** [comment]
Could we add it so island owners can break the spawners as well please.

**Comment by SwiftSwamp** [comment]
That defeats the purpose of why Spawner Locking was even added.
