### ISSUE TITLE
Quick Buy Command

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#683]
While this would be extremely useful, I've marked it as a Low Priority as it's not really an important enhancement. However if you feel that it's pointless to even add, go ahead and close this.

Add the ability to quick buy items from the shop (Only Vault / or shops with Custom Counts) i.e. /buy <item> <amount>

**Comment by cyberpwnn** [comment]
Give me some command usage. How would i quickbuy? You mean like /buy apple 10?

**Comment by SwiftSwamp** [comment]
That's really odd, I thought I did. 

i.e.: /buy <itemname or id/metaid> <amount>

**Comment by cyberpwnn** [comment]
Well normally you would do /shop...

Should it be like this?

```/shop buy <item:meta> [amt/1]```

**Comment by SwiftSwamp** [comment]
Yeah sure, my bad lol.
