### ISSUE TITLE
Faction Fly Tweak

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#684]
Not a high priority but when you get around to it, also allow users with the ability to fly to fly in Allied land.

**Comment by cyberpwnn** [comment]
Please explain exactly where players can and cant fly. I have recoded that snippet 7 times to be configurable and hook into everything needed. Before i recode it again explain the conditions you want it to follow

**Comment by SwiftSwamp** [comment]
Could always add a few options to it i.e.;
allowEnemyFly: true/false
allowNeutralFly: true/false 
allowWildFly: true/false
etc... instead of a while "Allow only these places fly or anywhere".
