### ISSUE TITLE
Psycho title is spelled wrong

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#687]
It should be Psycho not "Pyscho"

**Comment by Ashleyyx** [comment]
Also, when you get #2017 you cannot redeem it. I tried giving it to BobTheBuilder__ and it wasn't registered as a title.

**Comment by SwiftSwamp** [comment]
Will have to wait for a complete network reboot to fix, pretty sure it wouldn't be a good idea to update the database live (I have to change everyone who owns the Title as well). 

@Ashleyyx Oops, didn't know you meant that, yeah 1 issue per issue please :P Fixed it anyways tho .

**Comment by SamGlacial** [comment]
Same for candycorn when redeemed spelt 'cnadycorn'

**Comment by SwiftSwamp** [comment]
I don't believe we're referring to the same thing.

**Comment by SwiftSwamp** [comment]
Ahh, the Coupon Messages were misspelled, not the Titles. I was going to say :p For the Titles to be out that long and someone is just now reporting the typo.

**Comment by WolfiezRawr** [comment]
Also same thing with the Mistletoe title. It's not misspelled but there's a slight capitalization error. In the chest it shows it as "Mistletoe" but when someone puts it on it's shown as "MIstletoe"
Proof: https://gyazo.com/276307e0774766258b0806bde4663e3b
