### ISSUE TITLE
Empty Potion Bottles Don't Disappear

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#690]
Correct me if I'm wrong but near the start we made it so when you drink a drinkable potion, it would just remove the empty glass bottle instead of adding it into your inventory, if that was the case then this feature is broken.

**Comment by SwiftSwamp** [comment]
Reason this was made a priority at all is because it can get quite annoying, especially when you're fighting multiple people at once, you drop one and your inventory fills up with useless junk instead of possible more unused potions to keep battling.

**Comment by cyberpwnn** [comment]
> Correct me if I'm wrong but near the start we made it so when you drink a drinkable potion, it would just remove the empty glass bottle instead of adding it into your inventory, if that was the case then this feature is broken.

What plugin is supposed to do that?

**Comment by SwiftSwamp** [comment]
At the very start, Commune had an addition where once you drank a potion it would automatically remove the glass bottle instead of giving you an empty one. I believe it was added along side the fix hand and all.

**Comment by cyberpwnn** [comment]
Show me the issue & commit

**Comment by SwiftSwamp** [comment]
We spoke about this in a Skype call lol.
