### ISSUE TITLE
Stealth Speed expl.

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#693]
https://youtu.be/NMmQDHg7DyA
Basically gives you an unfair advantage, works on wherever people have /fly

**Comment by SwiftSwamp** [comment]
Confirmed, the left over time from sneaking with the Stealth Skill is extremely op, is there a way you can make it only last a few seconds? @cyberpwnn

**Comment by cyberpwnn** [comment]
Disable it if its too op or you dont like it. Giving a temp speed boost would be more annoying than useful.

Might just be a better idea to disable speed while in flight.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Icing/commit/70ba407767ecf9e0bbed4c1d27b229b4a4ed604a
