### ISSUE TITLE
Jumping while EPearling Cancels it

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#695]
I know we spoke about this before but i'm not entirely sure what was said regarding it but you can't Ender Pearl while jumping, possibly check your position from the ground or can you check if they were up in the air from jumping?

**Comment by cyberpwnn** [comment]
With more cpu cycles and math, anything is possible.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/65f178a7f6af50eb9e9eb3c795f9292647ca0d35

**Comment by SwiftSwamp** [comment]
You just removed some stuff, you didn't add anything. Wouldn't that just add in some of the Ender Pearling Glitching doing that?
