### ISSUE TITLE
Vacuum Hoppers not working

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#699]
Once placed in the right area, they won't suck up items. Nothing really to test, they don't work.

**Comment by SwiftSwamp** [comment]
Confirmed, I thought this was already an open issue.

**Comment by cyberpwnn** [comment]
Try breaking it and re-placing it. 

Does that cause it to start working again (at least for some time) ?

**Comment by SwiftSwamp** [comment]
Nope, Vacuum Hoppers just aren't working entirely.

**Comment by Puretie** [comment]
Try to keep it on the original issue, guys. If it's not fixed, it's still an issue.
