### ISSUE TITLE
Mcmmo not working in Factions

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#701]
On fac mcmmo is not working and people with a lot of level will have a advantage so please make mcmmo work we can't level up our sword and stuff when grinding

**Comment by dragonking1121** [comment]
On fac mcmmo is not working and people with a lot of level will have a advantage so please make mcmmo work we can't level up our sword and stuff when grinding

**Comment by SwiftSwamp** [comment]
Just tested it, McMMO works fine to me. Please provide more information.

**Comment by dragonking1121** [comment]
I mean you can only level up mcmmo by killing natural spawn mobs not mobs spawned from spawner

**Comment by SwiftSwamp** [comment]
Plugins / Skills such as McMMO do not receive any experience from spawner mobs due to the way technic spawns them, please investigate Dan.

**Comment by cyberpwnn** [comment]
If mcmmo isnt listening on the spawner spawn event, i cant do anything about it. Im calling the spawner spawn event, meaning all plugins that handle spawner spawns will assume my spawns are SPAWNER spawns not just random spawns. 

* See https://github.com/cyberpwnn/Technic/blob/master/src/main/java/org/cyberpwn/technic/block/SpawnerBlock.java#L197

You might want to test and see if merged mobs is the culprit also.

**Comment by SwiftSwamp** [comment]
Will re-investigate and confirm again.
