### ISSUE TITLE
Put sharp5 and unbreaking 5 in xpshop

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#702]
We should add these enchant in the xpshop since there no way we can get them

**Comment by SwiftSwamp** [comment]
What server are you referring to? Only place I'm willing to add them to is Crates, XP Shop would make it extremely easy to obtain.

**Comment by dragonking1121** [comment]
Factions

**Comment by SwiftSwamp** [comment]
It's obtainable on Factions through Crates and has been prior to Beta.

**Comment by dragonking1121** [comment]
I know but u can only get it on koth keys and stuff I want it so u can optained through vote key or daily

**Comment by SwiftSwamp** [comment]
I feel as that would be to op.

**Comment by dragonking1121** [comment]
Maybe we can add to a kit or make a new kit with sharp 5 tools or we can add it just in vote key with a low chance at wining it

**Comment by cyberpwnn** [comment]
* If its in crates it should be in the xp shop. 
* If its too op it shouldnt be in crates
* If its not in crates and too op, reject.
