### ISSUE TITLE
Phantom itself causes Cannons not to work 

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#704]
Tested it on a test server, added plugins one by one... removed everything but Phantom. Still didn't work. Unloaded Phantom, reloaded the Cannon(s) and it fired just fine .

**Comment by SwiftSwamp** [comment]
iMayDie_ When the cannon fires everything else is fine except from the scatter which pushes up the hammer tnt to on top of the cannon.

**Comment by Kyle17** [comment]
When the cannon fires everything else is fine except from the scatter which pushes up the hammer tnt to on top of the cannon making the top of it blow up.

**Comment by SwiftSwamp** [comment]
Was caused by some old left over code attempting to add in features of PaperSpigot into a plugin.
