### ISSUE TITLE
Once all titles unlocked, no Title vouchers are given

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#706]
https://i.gyazo.com/160a1559610d5a64e9acaf28f83695cc.jpg

I still want titles to sell them to other people, but I can't get them anymore
(atleast from a title crate)

**Comment by SwiftSwamp** [comment]
Sell the Title Crate itself, it would be too much work just to make it give you a random voucher coupon from a separate plugin just to give you that when using it if you have all Titles unlocked.
