### ISSUE TITLE
Blast (facs) 

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#707]
https://youtu.be/XuHnIPYQ6c8
Basically you can mine shit without being a mod of your fac.

**Comment by cyberpwnn** [comment]
Phantom Protection does not support inter-faction regions. should blast only be usable in the wild? or add support?

**Comment by SwiftSwamp** [comment]
Add support, it would be useful when tearing down multiple rooms / areas of your base.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/62e41df7307e3665efc55a37d6a73e4f9547f273
