### ISSUE TITLE
Enchantment Obsidian Destroyer

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#71]
Obsidian Destroyer - Mining obsidian is 4 times as fast, but consumes 2 times the durability (only on obsidian)

**Comment by cyberpwnn** [comment]
There isnt exactly a good way to do this but ill see what i can do

**Comment by SwiftSwamp** [comment]
How can you go about doing it?

**Comment by cyberpwnn** [comment]
mass cancel interact events + block break animation packets

**Comment by cyberpwnn** [comment]
This one is kinda not useful anymore (blast)

**Comment by SwiftSwamp** [comment]
Yeah, closed.
