### ISSUE TITLE
Kit snow + /stack (KitPvP)

### ISSUE THREAD

**Issue by GlacialSean** [cyberpwnn/GlacialRealms#710]
If you do /kit snow on kitpvp and then buy a few potions and then do /stack, the potions that are normally 3 min. long turn into 8 min long as they get stacked.

**Comment by dragonking1121** [comment]
Everyone knows this but u get 8 min its only strenth 1 not 2

**Comment by SwiftSwamp** [comment]
Please report this again after the reset if it's still occurring as everything underwent a huge revamp.
