### ISSUE TITLE
Action Cooldown Chat Announcement

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#712]
Sometimes people like to be precise when battle with the Gapple Cooldown, Enderpearl or even command cooldown, it would be nice if a message went off in chat when you could use something that's cooled off again.

**Comment by iOGMohawk** [comment]
Hai der!

**Comment by cyberpwnn** [comment]
Due to the amount of cooldowns there are, i have chosen to store a "last used variable" instead of constantly counting, that way i only check what needs to be checked (for example if you try to use something)

However i could check every other tick. I dont see much drop in performance there.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/7afd2f7e078834a6861febc12581a455406847b1
