### ISSUE TITLE
Redstone Ticking Limits per Island

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#713]
Currently we've had issues with larger lump sums of players with Redstone, Redstone seems to be our last issue remaining on Skyblock that can still cause lag. Currently I've tried various ways to help limit lag, however doing per chunk or a global ticking limit screws up everything, even clocks that aren't ticking fast at all or are extremely slowed down still become broken and unusable. 

Suggestion: Add ticking limits per island for Redstone
Could you also post some examples of what kind of clocks tick at what outputs so I can gain a better idea myself as well of what's going on behind the scenes. I need some numbers to crunch.

**Comment by SwiftSwamp** [comment]
Unless we could work with FAR and try to knock out all of the bugs with it?

**Comment by cyberpwnn** [comment]
For far, keep testing new versions. But for the time being ill work on a island limiter (it will be compatible with far)

I hope your using FAP on skyblock, its going in there.

**Comment by cyberpwnn** [comment]
Its actually going in phantom.......

**Comment by cyberpwnn** [comment]
https://github.com/PhantomAPI/Phantom/commit/6b77fa14f5a4810565e1a833ca1c5c31671c6c77
https://github.com/PhantomAPI/Phantom/commit/d16f7c2c28d8ba1d53cf90a205023d68e469e184
https://github.com/PhantomAPI/Phantom/commit/0dd56d141f911a883abb5ad83a16f3ba81716904

----

### Scheduled for Phantom D8
