### ISSUE TITLE
Server Selector Whitelist Variable

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#715]
I'm not sure if this is possible, if it is mark it as a Low Priority.

It would be cool to have a Variable that can detect if a server is currently whitelisted or not.
If it's whitelisted it'll display "Currently Whitelisted"
If it's not whitelisted, it'll display "Open!"

Something like that would be cool so players can see if there are any Events, Beta Testing, etc.. going on select servers in the selectors.

**Comment by cyberpwnn** [comment]
Would have to use transmission to communicate information about the server back.

**Comment by cyberpwnn** [comment]
#721 Will be completed first
