### ISSUE TITLE
4th Vote link doesn't give a reward

### ISSUE THREAD

**Issue by CombatWombat010** [cyberpwnn/GlacialRealms#723]
The new 4th vote link doesn't give out any prizes (money, vote points or voting crate).

**Comment by dragonking1121** [comment]
Same I dident get mine

**Comment by cyberpwnn** [comment]
It might be because of the web server issues this morning. Can someone re-confirm this is still a problem?

**Comment by dragonking1121** [comment]
Confirmed I did it agian dident work

**Comment by SwiftSwamp** [comment]
The new Voting Site I added the server to seems to of had some issues, this is now resolved.
The Author was extremely quick about resolving it, so far I'm loving it :)
