### ISSUE TITLE
Iron Gasp Isn't Working Properly

### ISSUE THREAD

**Issue by TTBrady** [cyberpwnn/GlacialRealms#725]
So basically I was AFK mining with one of my alt, I failed and went through the floor and I died from high place. Although I had an Iron Gasp pickaxe, but it actually dropped, the enchant description says that it shouldn't drop on death. Therefore it should be fixed soon, as we don't want the players to lose their items because of this.

**Comment by SwiftSwamp** [comment]
Iron Grasp is actually only about a 80% chance of keeping the item.

**Comment by TTBrady** [comment]
Oh, alright I see. Maybe it should be added into the /enchantapi book ? Because apparently I wasn't the only one thinking it was 100% sure that we were keeping it.
