### ISSUE TITLE
Can't Combine on Kitpvp

### ISSUE THREAD

**Issue by Tenheartinq** [cyberpwnn/GlacialRealms#728]
I was trying to combine a p4 book to a p3 unbreaking 3 pair of boots and it kept glitching me and giving p3 unbreaking 3 instead of p4 unbreaking 3.. I even gave the items to a mod (Fizinq)  to check and it did the same. Please fix the error because i can't combine to make p4 unbreaking 3 until this is fixed.

**Comment by Fizinq** [comment]
Protection 3 is now the max instead of Protection 4. Found that out after you got off.

**Comment by Puretie** [comment]
Glad to see we've resorted this the easy way. Issue closed.
