### ISSUE TITLE
cant leave my island on skyblock

### ISSUE THREAD

**Issue by XxMrWolfxX** [cyberpwnn/GlacialRealms#731]
**i tryed /is leave /is restart**

**Comment by SwiftSwamp** [comment]
Are you trying to restart your island or are you unable to even go to /spawn?

**Comment by Puretie** [comment]
Need follow-up from poster on situation and status conditions.

**Comment by XxMrWolfxX** [comment]
Trying to leave my island so my friend can invite me to his

**Comment by CondensateTribe** [comment]
You can solve this just by that person inviting you to the island. Unless you are the owner, which then you need to make someone the leader.
