### ISSUE TITLE
Enchantment Iron Grasp

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#75]
Iron Grasp - On death, high chance of keeping the item with this enchant (Reason why high chance instead of perm.. is because that's just op)

**Comment by cyberpwnn** [comment]
Screw that, just lots of tasks!

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/2b2329eeb6a592ec2003234086e2c2bad32ffce7
