### ISSUE TITLE
Enchantment Drill

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#77]
Luck - Can be applied to TNT or Creepers.. Spawners blown up with this enchantment have a higher chance of dropping. 

This corresponds with: https://github.com/cyberpwnn/GlacialRealms/issues/50

**Comment by cyberpwnn** [comment]
Renamed to drill due to name collision with mc enchant Luck

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/6344a8da4944822dbaf371cd8ab5e2fa078fa06d

**Comment by GetDerpy** [comment]
Allow it to be placed on no more than 3 ceggs at once
