### ISSUE TITLE
Enchantment Hells Curse

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#87]
The Enchantment is an enchantment that allows you to fly anywhere except for the Warzone & Enemy Territory (How it was before the change back to land only). The enchantment can not be received from tired books, it's entirely unobtainable. It also can only be applied to Boots.

**Comment by cyberpwnn** [comment]
You could also just make a command /hellscurse.

**Comment by SwiftSwamp** [comment]
Alright, the blocking part is fine. This was made before I saw that in the EnchantmentAPI Configuration, I just need the enchantment itself :P

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/24ad584febe37b86a14c22fd0d391bff60560bbd
