### ISSUE TITLE
Drop Enchant Addition

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#90]
Please allow the same drop enchants to work on Axes as Swords
![](https://i.gyazo.com/47a8df9ff593d83529a9512117a0f805.png)

**Comment by cyberpwnn** [comment]
Which ones still do not work?

**Comment by cyberpwnn** [comment]
They should all work now actually.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/de5f815a413c6358986a23ce1b3b238978eb74a7
