### ISSUE TITLE
Add date formatting to dropped heads

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#98]
it would be good to do so

**Comment by SwiftSwamp** [comment]
Make sure not to include the hour / minute / second.

**Comment by cyberpwnn** [comment]
SwiftSwamp
Killed by cyberpwn on December 25th, 2016-2035

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/85dc991eb813ef440d82adee014e4a6f3e83e26a
